### ISSUE TITLE
Add community member role and add restricted depositing option for communities

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1006]
Some communities want to restrict the depositing process, and allow only their members to add records for these communities.

**Comment by thijscobben** [comment]
Easy part. B2ACCESS link covered in #1007

**Comment by thijscobben** [comment]
Assuming the option (deposit_members_only) can be set configuring the community via CLI (no UI required).

**Comment by emanueldima** [comment]
https://github.com/EUDAT-B2SHARE/b2share/commit/ee5e58c5069d129776bfdd0e4bbc4f6abec4013b
