### ISSUE TITLE
Add community administrator roles, allow them to manage community members

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1007]
see also #1006

**Comment by thijscobben** [comment]
API for admin assignment/creation
CLI 
Model enhancement adding members list to community
Link to B2ACCESS user database? Or e-mail based?
Web UI DataGrid that calls add/edit/delete/list operations

**Comment by nharraud** [comment]
@emanueldima @thijscobben Do we wan this for the update of CSC server or only in the final v2 version?

The main problem I see is designing a temporary REST API for that which is additional work and will probably be removed later in favor of a future invenio-team module, or invenio-accounts-rest on which @PaulinaLach is currently working on.

**Comment by emanueldima** [comment]
We need the community admin roles for the upgrade, but the option to manage the members can wait until the release.

**Comment by emanueldima** [comment]
The UI is postponed to 2.0.1

**Comment by emanueldima** [comment]
UI merged in https://github.com/EUDAT-B2SHARE/b2share/pull/1389, tested and working
