### ISSUE TITLE
Allow a user to create a new record based on an existing record

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1013]
This is needed according to the new record lifecycle for modifying the files in a record. Some communities require the new record to have the same PID as the old one (dynamic PID). The new record must clearly state that it is a new version of a previous record.

**Comment by dinosk** [comment]
*Note*: Copy the record metadata to the new version  iff the community schema is the same

**Comment by emanueldima** [comment]
solved in 2.1.0
