### ISSUE TITLE
Add checksums for files, in the API and in the UI

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1032]

**Comment by emanueldima** [comment]
Looks like invenio-files-rest version a8 will have them, we need to wait for its publication:

https://github.com/inveniosoftware/invenio-files-rest/commit/9fade5bcd313075d8e9ac08b4ba4ce5e1ae35b87

**Comment by nharraud** [comment]
There is a problem with checksum not being displayed when the record is closed-access.

**Comment by emanueldima** [comment]
fixed now that we switched to invenio-files-rest a10, see https://github.com/EUDAT-B2SHARE/b2share/pull/1121
