### ISSUE TITLE
Search UI: Add help content

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1045]
In the help section there is a special section for search, which needs to be filled in.

Also, the search bar has (in the left side) a help button, which should provide a popup with some help.

**Comment by hevp** [comment]
This information has been moved to the general EUDAT website:
- https://eudat.eu/services/userdoc/b2share-usage#UserDocumentation-B2SHARE-Searchanddownload
- https://eudat.eu/services/userdoc/b2share-advanced-search

Links will be added through ticket #1751.
