### ISSUE TITLE
Dockerize: 404 when using nginx for api calls

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1057]
Make docker work on local machines, currently we are experiencing proxy issues generating 404 on /api/ calls to the nginx URL within the docker.

Environmentalize (DTAP) docker instance, ie. make some easy mechanism (Nicholas has files/scripts?) to run different codebases (brances/tags/commits) in docker AND to specify different configuration files within one codebase.

**Comment by emanueldima** [comment]
**Analysis:**

Flask uses Werkzeug for routing. The routes are defined not only by url, but also by the hostname or subdomain. Source: https://github.com/tylertreat/webhook-test/blob/master/werkzeug/routing.py#L1403

To match a route, a request must have the 'Host' header equal with the declared 'SERVER_NAME' (including the port). 

When running in developer mode, we don't use nginx and we want Flask to serve everything and know about its hostname. So in this case the SERVER_NAME should include the port.

But when running as docker container proxied by nginx, the hostname should be set as the externally visible host, which does not include the port number. So probably the solution is to remove the port number from the SERVER_NAME here: https://github.com/EUDAT-B2SHARE/b2share/blob/evolution/dockerize/docker-compose.yml#L31

**Comment by lnielsen** [comment]
FYI: In general I never set ``SERVER_NAME`` in Flask manually as it usually always causes troubles, especially if you're in a load balanced environment. If you don't set ``SERVER_NAME``, the Flask will rely on the Host-header to set a server name (which means that you must be in a request context in order to use ``url_for()``.

**Comment by emanueldima** [comment]
see https://github.com/EUDAT-B2SHARE/b2share/pull/1071
