### ISSUE TITLE
Error message after importing large file

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1059]
The error should be informative. And maybe check before upload not after I think this is possible?
<img width="879" alt="screen shot 2016-07-28 at 12 01 10" src="https://cloud.githubusercontent.com/assets/7724267/17208948/2471e5aa-54bb-11e6-836b-6774df08e98d.png">

**Comment by nharraud** [comment]
related to #1095.

**Comment by emanueldima** [comment]
The error message is correctly displayed in RC6 (Error: Maximum file size exceeded). Checking the file size before uploading is a good idea, but more difficult to implement (as this should be configurable).

**Comment by emanueldima** [comment]
Closing this one, created another one for configuring the max file size: https://github.com/EUDAT-B2SHARE/b2share/issues/1146
