### ISSUE TITLE
Non-owner should be allowed to see metadata of a record

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1060]
Even if non-public access, metadata of a published record should still be visible to 'other'.
If non-public access then (only) the files cannot be downloaded by 'other'. (currently correctly implemented).

**Comment by emanueldima** [comment]
This is now fixed: https://github.com/EUDAT-B2SHARE/b2share/commit/a67f176615791bb6661974496dfd55f68b8a1d85
