### ISSUE TITLE
search: Enable lemmatisation in elasticsearch

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1064]
E.g. searching for 'diagram' should return records containing the plural 'diagrams'

**Comment by thijscobben** [comment]
As discussed, for now, 'just' define English language lemmatization. Make a new issue "involve users for search functionality feedback" and "open issues/backlog in search functionality".

**Comment by emanueldima** [comment]
see https://github.com/EUDAT-B2SHARE/b2share/pull/1127

**Comment by emanueldima** [comment]
with https://github.com/EUDAT-B2SHARE/b2share/pull/1132 plurals and verbal inflections should be handled
