### ISSUE TITLE
deployment: Use local clone of B2Share when building docker image

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1066]
**Problem:**
Current **Dockerfile** creates the image using a clean clone of B2Share from Github. This prevents us from testing code before sending PRs.

Thus the Dockerfile should use the local clone of B2Share.

**Comment by nharraud** [comment]
@llehtine This is the issue I was talking about. I'll create a first PR with the naive version. We can improve it later.

**Comment by llehtine** [comment]
Ok. Would this be modification for the current Dockerfile, or brand new one which would be using to setup the dev environment?

**Comment by nharraud** [comment]
This modifies the `Dockerfile` and the `docker-compose.yml`. It removes the `git clone ... b2share` and replaces it with copy of local files.


I am also adding some optimizations as the copying all the files is still too long for testing local code, it reinstalls everything at each modification. I just change the order of the commands and copy files only when needed in the container. Ex: copy of `setup.py` and `b2share/version.py` then run `pip install .[all]`.
That way `pip install` is ran again only when one of those files change. The rest of the files are copied later.
