### ISSUE TITLE
Add all b2share communities into the demo site

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1075]

**Comment by thijscobben** [comment]
LTER needs to be added.

**Comment by emanueldima** [comment]
See this file for the metadata fields required by LTER:
https://github.com/EUDAT-B2SHARE/b2share/blob/1.7/invenio/b2share/modules/b2deposit/b2share_model/metadata/ecology_metadata_config.py

**Comment by emanueldima** [comment]
The image file is here: https://github.com/EUDAT-B2SHARE/b2share/blob/1.7/invenio/b2share/modules/main/static/img/domain-lter.jpg

**Comment by thijscobben** [comment]
When I look at csc test/demo site LTER is there.
