### ISSUE TITLE
api: check schemas backward compatibility using inveniosoftware/doschema.

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1076]
We need to use the validation function in inveniosoftware/doschema for the validation of our block and community schemas.

The validation should be done in the programmatic API. The REST API should have an error handler which forwards the exception as a REST Exception [as it is done here](https://github.com/EUDAT-B2SHARE/b2share/blob/def0d0cce6d0677bab5c4354c44a7b81f478e467/b2share/modules/records/errors.py#L49).

Note: DoSchema is not released yet so the travis tests will work only in devel mode:
- Add `-e git+git://github.com/inveniosoftware/doschema.git#egg=doschema` in this file https://github.com/EUDAT-B2SHARE/b2share/blob/evolution/requirements-devel.txt
- Add doschema to setup.py.

The corresponding PR will of course be merged only once doschema is released so that the branch is not broken.

**Comment by emanueldima** [comment]
see also https://github.com/EUDAT-B2SHARE/b2share/issues/987

**Comment by nharraud** [comment]
@emanueldima Sorry I will rename this issue to make it more specific. The validation currently done by @thijscobben does not use doschema and is not sending any error response through the REST API.

As this one is blocked by doschema not being released I would separate the two Issues. One for a first "structure validation" of the schema, and another using doschema for backward compatibility.
