### ISSUE TITLE
deployment: use UWSGI server in docker image

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1090]
We are currently running B2Share with Werkzeug, which should be used only for testing, not for production environment.

@lnielsen gave a great feedback for UWSGI so I suggest that we go with this server. We can take a look at Zenodo's configuration.

**Comment by emanueldima** [comment]
see https://github.com/EUDAT-B2SHARE/b2share/pull/1173/files

**Comment by nharraud** [comment]
solved by #1173
