### ISSUE TITLE
issue while uploading mid-size file (500MB)

### ISSUE THREAD

**Issue by bne86** [EUDAT-B2SHARE/b2share#1095]
Hi,
when testing [1] with mid-sized files (500mb) the first upload bar disappeared without comment. Then i uploaded a small file to the same deposit, it is shown, and a second try to upload a larger file shows a error text. Find attached the screenshot.

Which file-size (max) will be supported?

best
benedikt

![screen shot 2016-08-22 at 11 23 23](https://cloud.githubusercontent.com/assets/5327850/17849908/31ea3706-685b-11e6-93d8-24f8a97d95b5.png)
![screen shot 2016-08-22 at 11 23 06](https://cloud.githubusercontent.com/assets/5327850/17849907/31e88bc2-685b-11e6-9c00-bb923587d48f.png)

**Comment by nharraud** [comment]
Thank you for the bug report @BeneDicere !

The RC-4 will soon be released. The max size is set to 1GB on the test server and 10GB for people deploying B2Share themselves as described in INSTALL.rst (with `export LOAD_DEMO_CONFIG=1`)

I could reproduce the bug you described as disappearing upload bar.
The corresponding error message in the console is:

```
server.js:219 PUT https://vm0045.kaj.pouta.csc.fi/api/files/fc3a553d-bd7d-498c-9775-fc2615da72a0/test-file-500m.random net::ERR_CONNECTION_RESET
value @ server.js:219
value @ server.js:553
(anonymous function) @ editfiles.jsx:332
ajax.js:14 --- ajaxGet: 137657 https://vm0045.kaj.pouta.csc.fi/api/files/fc3a553d-bd7d-498c-9775-fc2615da72a0 undefined
```

Myt intuitions tells me that the connection timeout is too low in the NGINX configuration.

This might not be fixed for RC-4 but will surely be in the next one.

**Comment by emanueldima** [comment]
In RC6, using a local installation, the bug cannot be reproduced. I tried with 2 files, 1.2GB and 3.75GB, uploaded in ~40 and ~120 seconds.

**Comment by emanueldima** [comment]
On the testing site, the upload correctly stops after a few seconds with an error message:

Error: Maximum file size exceeded.

So it looks like it was indeed an nginx conf error, which is now solved.
