### ISSUE TITLE
CLI for community schema management

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1098]
I removed code from modules/schemas/cli.py to link a (versions of a) block schema to a community via the json key/element "community_schema".
Now the CLI is incomplete to manage schemas for communities.
Discussion with Nicolas that we do not want users to have to manage this themselves in an explicit manner. The alternative would e.g. be that if a user adds a block schema it automatically becomes the latest in community schema.
Needs more discussion. Code is in older commits on my fork of cli_comm branch.

**Comment by thijscobben** [comment]
Requirements gathering. Study REST-API code by Paulina. 
My suggestion would be:
b2share update_community_schema <community_id> <path_to_jsonschema_file>
this would create a new block schema version of the provided jsonschema_file (a new block schema, version 0)
This would create a new community_schema version for the provided community which refers to the block_schema_version from the previous sentence.

**Comment by emanueldima** [comment]
should be solved by https://github.com/EUDAT-B2SHARE/b2share/pull/1384
