### ISSUE TITLE
global: Use standard PyPI version numbering

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1109]
We are currently using custom versioning like `2.0.0.rc4`. [Python's PEP 440](https://www.python.org/dev/peps/pep-0440/#pre-releases)  says that it should be `2.0.0rc4` (without the `.`)

**Comment by nharraud** [comment]
@emanueldima Can we change that for RC5?

**Comment by emanueldima** [comment]
Yes, of course. I didn't know about the PEP.

**Comment by jirikuncar** [comment]
@nharraud just make sure that users uninstall the previous RC version first, since it appears as a post-release of 2.0.0. Later it will be easier when you release 2.0.0.

```python
from distutils.version import LooseVersion
# 2.0.0rc6 < 2.0.0 < 2.0.0.rc5
LooseVersion('2.0.0rc6') < LooseVersion('2.0.0')
LooseVersion('2.0.0') < LooseVersion('2.0.0.rc5')
```

**Comment by nharraud** [comment]
@jirikuncar thanks for the advice !

**Comment by emanueldima** [comment]
closed by https://github.com/EUDAT-B2SHARE/b2share/commit/785728eb1f69d23eec91b1f0455f955ee8e5f74a
