### ISSUE TITLE
UI: Generated keyword link is not correct

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1110]
**Scenario:**
- Go to a record's page which has some keywords
- Click on a keyword
- The search page is not filtered by keyword

**Reason:**
It seems that the generated URL is using "query" instead of "q" for the query.

**Comment by nharraud** [comment]
Note that even like that the keyword filtering will still work in a strange way because it is searching in every field and not only in the keyword field.

**Comment by emanueldima** [comment]
updated in https://github.com/EUDAT-B2SHARE/b2share/pull/1148: correctly search for the keyword, but not just in the keyword field

**Comment by hevp** [comment]
This has been solved in the linked PR. Closed.
