### ISSUE TITLE
UI: cannot recreate file after deleting it

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1113]
**Scenario:**
- delete a file from a draft record.
- add again the same file in the draft record.
  => nothing happens

The file can be added again if another file has been added before or if the page is reloaded.

Nginx logs show no request sent to the backend when I try to add the file again. Thus it looks like a UI bug.

**Comment by hevp** [comment]
This is no longer the case. Issue closed.
