### ISSUE TITLE
doc: use https link for git clone command

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1115]
As not everybody has a github account we should use only https links in the documentation instead of ssh links.

```
git clone https://github.com/EUDAT-B2SHARE/b2share.git
```
Instead of
```
git clone git@github.com:EUDAT-B2SHARE/b2share.git
```

**Comment by emanueldima** [comment]
one link changed in https://github.com/EUDAT-B2SHARE/b2share/pull/1138
