### ISSUE TITLE
Migrate V1 records and users

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1159]
To enable switch of production server of b2share data from v1 has to be migrated to v2.
The requirements are:
1. all records must be migrated. Importer currently ignores records in the "CLOSED" (not open for public access) state these must also be migrated.
2. community specific metadata must be - in as far as possible - mapped to community specific metadata in v2. PROBABLY COMMUNITY ADMINISTRATORS NEED TO BE CONTACTED FOR THIS also to e.g. adapt the current metadata schemas.
3. in v1 there is the field "uploaded_by" containing an e-mail address. B2ShareV2 does not have such a field. But on the basis of this field the correct b2access account, that must be looked up or created (contact the user) must be linked (permission wise) to these records.

Questions:
- what do we do with deposits?
- what do we do with user accounts that login via b2access but are not present in "uploaded_by" field?
- what do we do with user accounts that login via username/pw ?
  Maybe separate (non-urgent?) tickets need to be created for these questions?

**Comment by emanueldima** [comment]
1. We don't migrate deposits, they are of a transient nature in v1. Each abandoned deposit is (or should be) erased from b2share v1 in 3 days. We must simply show a message on v1 announcing the coming update one or two weeks before.

**Comment by emanueldima** [comment]
see https://github.com/EUDAT-B2SHARE/b2share/pull/1214
