### ISSUE TITLE
Add 'Find own drafts' option to the user profile and HTTP docs

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1160]
To find the drafts of an user:
1. set the ‘drafts=1’ arg to a suitable http search call
2. filter out the drafts based on the status (set q=publication_state:draft)

https://vm0045.kaj.pouta.csc.fi/api/records/?drafts=1&q=publication_state%3Adraft

ALSO, update the rest documentation with the new option for searching in own drafts

**Comment by emanueldima** [comment]
http api documentation updated in https://github.com/EUDAT-B2SHARE/b2share/pull/1169

**Comment by SarahBA** [comment]
fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/1364
