### ISSUE TITLE
Importer: gzipped files seem to be automatically decompressed on download

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1163]
Test this with first file of https://b2share.eudat.eu/record/30. The declared file size, of the compressed file, is 1.5GB. The downloaded file keeps the same name and extension, but is more than 3GB in size. The 'file' utility reports that the downloaded file is just a .tar file, and not a .tar.gz file as it is on the server.

**Comment by thijscobben** [comment]
This was an issue with CHUNK_SIZE parameter of the read/write methods when saving a file.

**Comment by thijscobben** [comment]
This is fixed in Migrator PR
