### ISSUE TITLE
docker deployment does not work because of elasticsearch incompatibility

### ISSUE THREAD

**Issue by bne86** [EUDAT-B2SHARE/b2share#1164]
when deploying b2share via ```docker-compose up```, he is complaining 

> pkg_resources.ContextualVersionConflict: (elasticsearch 5.0.0 (/usr/lib/python3.4/site-packages), Requirement.parse('elasticsearch<3.0.0,>=2.0.0'), {'elasticsearch-dsl'})

you could pin elasticsearch to elasticsearch:2 in docker-compose.yml or fix/update the library.

**Comment by nharraud** [comment]
This will be fixed by pinning the version in `setup.py`.

We will make sure that this won't happen again by pinning automatically every dependency with `pip-compile`
