### ISSUE TITLE
api: validate record's REST API PATCH and PUT inputs

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1172]
**Problem:**
A record's JSON Schema can only check the resulting record structure and values. It does not check what if a modification is allowed.
We need to add some mechanism to forbid changes.

Here is an incomplete list of modifications which should not be allowed for a `draft`:
- [x] change the 'publication_state' to an invalid state
  - [x] change from `draft` to `published` or `submitted` when the community workflow does not allow it.
  - [x] change to invalid values. This currently already handled by the root JSON Schema but should be moved somewhere else if communities need to create completely custom workflows.
- [x] the community ID of a record should never be modified. Its schema depends on it.
- [x] internal fields should not be modified from outside. Those fields include:
  - `_pid`
  - `_files`
  - `_oai`
  - `_deposit`
  - `version`
- [x] inconsistent `embargo_date` and `open_access`. But this could be handled by the JSON Schema. This is currently automatically fixed, but a 400 error should be instead sent when a user explicitly asks for `open_access = True` and `embargo_date` in the future.

A published record has all the same constraint except for `publication_state` which should always be `published`.

**Comment by emanueldima** [comment]
@nharraud Can we close this one?

**Comment by nharraud** [comment]
@emanueldima Just the last one could be improved. Removing urgent tag.

**Comment by thijscobben** [comment]
Fixed by celery task that makes combination of open_access and future embargo_date consistent.
