### ISSUE TITLE
V1 record 297 gives status 410/Gone on webui not in api

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1176]
Go to:
https://b2share.eudat.eu/record/297
and you get a status Gone/410 in response.
But via
https://b2share.eudat.eu/api/record/297?access_token=...
it can still be retrieved
However, the files cannot be downloaded.
The current migrator hangs on this combination.

**Comment by emanueldima** [comment]
This is a bug in the v1 HTTP API. The API does not check the record status (which in this case is set to 'deleted').

**Comment by emanueldima** [comment]
the v1 API issues have been solved in this branch: https://github.com/EUDAT-B2SHARE/b2share/tree/1.7%23migration
