### ISSUE TITLE
Update HTTP API doc, answer review by Nuno Freire

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1182]
- [x] The possible HTTP Status codes of the HTTP API are not documented, neither in case of successful requests, nor in case of errors.
- [ ] Some of the API’s operations return complex responses in JSON, for which a JSON model is not available.
- [x] In case of errors, the B2SHARE API sends error messages. The JSON model of these responses is not provided.

**Comment by thijscobben** [comment]
The comment is https://docs.google.com/document/d/1kEyNpzGvA3dQBQUgxYhCi_5gY3nB9h8RrZ9CyDVJZuc/edit#heading=h.tt2wpzdhf9qc .

**Comment by hevp** [comment]
Source: https://github.com/EUDAT-B2SHARE/b2share/blob/master/webui/src/docs/rest-api.jsx

**Comment by hevp** [comment]
For returned errors: https://eudat.eu/services/userdoc/b2share-http-rest-api#Errors

**Comment by hevp** [comment]
For data structures, see:

- https://eudat.eu/services/userdoc/b2share-http-rest-api#Data_structures
- https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/deploy/10_Data_structures.md
