### ISSUE TITLE
http api: Add function to delete draft 

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1191]

**Comment by 7048730** [comment]
adding this feature would be much appreciated!

**Comment by nharraud** [comment]
From the REST API point of view it shouldn't be too difficult. [The permission](https://github.com/EUDAT-B2SHARE/b2share/blob/9bb0a9f1d596d3a17d303bd974b180db7ef2051e/b2share/modules/deposit/permissions.py#L316) already enables the owner and the super-admin to remove them]. We should just check that the files are properly removed.

**Comment by emanueldima** [comment]
solved in 2.1.0: An owner can delete an unpublished deposit with

curl -X DELETE https://$SITE_HOSTNAME/api/deposit/$DEPOSIT_ID\?access_token\=$ACCESS_TOKEN
