### ISSUE TITLE
UI: authors not displayed on the published record page

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1198]
**Problem:**
The "authors" are present inside the metadata returned by the backend but the frontend does not display them.

**Comment by emanueldima** [comment]
The UI seems to work correctly: https://vm0045.kaj.pouta.csc.fi/records/1033083fedf4408fb5611f23527a926d. I think the issue is that the migrator does not yet converts the authors.

**Comment by emanueldima** [comment]
migrator code fixed in https://github.com/EUDAT-B2SHARE/b2share/pull/1227
