### ISSUE TITLE
Local installation distribution

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1209]
- run_demo.sh? is it needed, should we rename it?
- review and improve the 'installation documentation' from 'basic' to 'first version'
- provision (and advise) external db (outside docker)
- make clear where to configure "local file storage" (I think it is hidden in config now?)
- create a record on b2share v2 where the tarball can be downloaded (to avoid git clone / pull issues on local installations)

**Comment by emanueldima** [comment]
should be mostly solved by https://github.com/EUDAT-B2SHARE/b2share/pull/1395
