### ISSUE TITLE
Embargo feature

### ISSUE THREAD

**Issue by stranak** [EUDAT-B2SHARE/b2share#123]
Allow submitters to set "release data" for the submitted record, I.e. set embargo (hide it) until that date. http://invenio-software.org/code-browser/invenio.websubmit_functions.Set_Embargo-module.html

Make sure we only embargo (hide) the data files, not the whole record, and display this information clearly in the GUI.

**Comment by cjhak** [comment]
* Data & metadata should be private (hidden) during embargo.
* "Private" should be the same as embargo.
* It should be possible to configure visibility, editability and deletability per role and domain for deposits under embargo.

**Comment by cjhak** [comment]
* End user documentation needed

**Comment by cjhak** [comment]
Relates to #530 and #531.

**Comment by cjhak** [comment]
http://invenio-software.org/wiki/Development/Modules/WebAccess
https://indico.cern.ch/event/183318/session/14/contribution/38/material/slides/1.pdf
