### ISSUE TITLE
CSC: curate B2Share.eudat.eu data before migrating to the final version of B2Share v2

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1256]
**Problem:**
Apparently there are some invalid data in b2share.eudat.eu. As we upgrade the server we will need for now to loosen some constraints on B2Share V2 release candidates. However we cannot release this in the final version. Thus we need to curate b2share.eudat.eu data before migrating to the final version of B2share v2.

Concerned fields are:
- [ ] `publication_date`: it was discovered as elasticsearch was refusing some records. (See the quick fix in #1255 which should be removed later)
- [ ] `creators`: for some document the array is empty.
- [ ] `publisher`: for some document this field is set to empty string.

**Comment by hevp** [comment]
This is no longer relevant. Issue closed.
