### ISSUE TITLE
migration: Remove new PIDs

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1277]
Hi,

Having talked to Mark he was a bit surprised we created new PIDs. We have never thoroughly discussed this, but indeed it makes sense to maintain the v1 PIDs as "main" PID. Since we have created the "v2 PID" we will have to keep it (but maybe even not 'advertise' it as alternate_identifier)

T.

**Comment by emanueldima** [comment]
ok, and we may combine this with https://github.com/EUDAT-B2SHARE/b2share/issues/1235

**Comment by nharraud** [comment]
Update:
- The new and old PIDs are now both redirecting correctly to the records.
- We still need to use the old PID as the main one. This is a work in progress.
