### ISSUE TITLE
migration: DOIs assigned to v1 records no longer work

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1280]
Some B2SHARE v1 records have been assigned DOIs (by third parties, but stored as 'alternate_identifier' in v1), pointing to the old record URL (/record/ID).

**Comment by thijscobben** [comment]
A redirector should be made redirecting /record/[0-9]{2,3}  to the new record URL.

**Comment by emanueldima** [comment]
This task seems to no longer be necessary. Only the RDA community used to assign DOIs to the old URLs of the objects, while in the other cases the alternate identifiers point to other web resources. And the DOIs belonging to the RDA community have been updated to point to the new (v2) URLs.
