### ISSUE TITLE
migration: alternate_identifier not migrated

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1282]
We have missed one field from v1 records, namely 'alternate_identifier'. In v1 record schema this field is of type string, and for some records it contains DOI identifiers. We must add this field from all the v1 records to the current list of alternate_identifiers in the corresponding records. An analysis of all the existing v1 alternate_identifiers is necessary to select their types (DOI or something else).

**Comment by emanueldima** [comment]
The list of the old (v1) alternate identifiers are in this file: [alternate_identifiers.txt](https://github.com/EUDAT-B2SHARE/b2share/files/671473/alternate_identifiers.txt)

**Comment by thijscobben** [comment]
A script should be made that does this internally via record/api.py .

**Comment by emanueldima** [comment]
Note: The `db.session.commit` is necessary for the changes to be persisted in the database.
````
    from invenio_records.api import Record
    from invenio_db import db
    rec = Record.get_record(_)
    rec['alternate_identifier'][0]['alternate_identifier'] = "updated"
    rec.commit()
    db.session.commit()
````

**Comment by emanueldima** [comment]
solved in prod
