### ISSUE TITLE
global: rename "evolution" branch as "master"

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1296]
There is now no reason to keep the "evolution" branch. We should switch back to the common practice of having a main branch called "master". Our branch workflow should also be documented so that people can rapidly understand how we work.
We need to make this change before @llehtine leaves the team, i.e during the next weeks, otherwise it will most probably break the deployment scripts.

@SarahBA @emanueldima @thijscobben @llehtine 

This will impact people who update their demo by merging the changes from upstream, Example: Heinrich.

**Comment by emanueldima** [comment]
solved by https://github.com/EUDAT-B2SHARE/b2share/pull/1470
