### ISSUE TITLE
B2SHARE create token

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#1325]
When a user requests a new token but forgets to type in a name the current error message is:
![screen shot 2017-01-16 at 13 59 40](https://cloud.githubusercontent.com/assets/8696302/21984054/5b3d69cc-dbf4-11e6-9ca0-38c58a3fbdc5.png)
This does not help the user to understand what is going wrong.

**Comment by SarahBA** [comment]
fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/1365
