### ISSUE TITLE
B2SHARE B2DROP Bridge - password

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#1326]
When entering your user name and password to connect to B2DROP, you need to explicitly click on the arrow next to the password to connect. The enter button does not work.

**Comment by emanueldima** [comment]
@chStaiger I just tested it and I cannot reproduce this, at least not in Chrome. After writing the password and pressing Enter the B2DROP dialog is shown. There is a lag (close to a second) between pressing the key and the screen update, could this be the actual problem?

**Comment by emanueldima** [comment]
not reproducible on 2.1.0
