### ISSUE TITLE
Citation widget

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1332]
**Problem:**
Researchers need to cite data easily.  There are multiple considerations:
- scientific journals have different constraints as to the citation format.
- datasets can have different PIDs. One need to be chosen.

**Requirement origin:**
- *Support tickets:* 10571

**Possible Feature description:**
A button "Cite this record" where you can configure citation to your needs. (Head or this Specific version? ePIC or DOI?) Maybe there is already Invenio code to do part of this.

Note: versioning can make the citation more complex. The Parent PID can be used to cite all versions. See Zenodo "Cite all versions?" on records.

**Implementation suggestions:**
Invenio already provide a module generating citations: [inveniosoftware/invenio-csl-rest](https://github.com/inveniosoftware/invenio-csl-rest)

**Comment by nharraud** [comment]
See support ticket n°10571

**Comment by nharraud** [comment]
Closing in favor of #978
