### ISSUE TITLE
Add a sitemap.xml to submit /api/records to google for SEO

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1342]
https://support.google.com/webmasters/answer/156184?hl=en

**Comment by nharraud** [comment]
Is it possible to do it without knowing the domain name?
If not, then we have to generate the sitemap.xml.

**Comment by nharraud** [comment]
There will be some work done in the next three months in Invenio for google scholar indexing. We might be able to use the result as is for B2SHARE because we have a custom UI, but we can at least take a look at it and do something similar.

**Comment by emanueldima** [comment]
Using the google console the site seems to be correctly indexed. Tentatively closing this.
