### ISSUE TITLE
B2FIND links to B2SHARE API records rendered as JSON

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1345]
The ideal behaviour is to be redirected somehow to the b2share UI

**Comment by hevp** [comment]
Example: http://b2find.eudat.eu/dataset/fc7e02d6-af79-5f83-bf56-36d1f21d4b4f

**Comment by hevp** [comment]
The source field in B2FIND refers to the actual data source. Clicking on the DOI or EPIC PID lands the user on the equivalent UI page.
