### ISSUE TITLE
Documentation / local installation

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1356]
Hi,

While documenting "local installation" we ran into a few issues:
- Only dockerize is sort-of working
- Script complains about "load_config -f" that is setup.cfg is already there; docker stops
- load_data automatically executed: we want a situation where db is empty after install and
- instructions to create community + community schema into the docker (attach to the docker and use the CLI? HTTP API?)

If we have this, we can execute (hence document) the Use Case "Local installation for community".

**Comment by emanueldima** [comment]
https://github.com/EUDAT-B2SHARE/b2share/pull/1395 would solve the first 3 issues.
