### ISSUE TITLE
views: wrong query when listing own drafts

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1412]
**Problem:**
The query of the URI to which the user is redirected when he clicks n "List of your draft records" is  wrong. It is `q=publication_state:draft&owners:2` instead of being `q=publication_state%3Adraft%20owners`

**Effect:**
None for now as we don't allow users to see others' draft records

**Comment by SarahBA** [comment]
fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/1413
