### ISSUE TITLE
deployment: docker is bypassing iptables firewalls

### ISSUE THREAD

**Issue by bne86** [EUDAT-B2SHARE/b2share#1423]
Hi,
due to the fact that docker is bypassing a linux firewall (on the host that we deploy b2share to we are dropping all connections that we do not explicitly allow), elasticsearch, rabbitmq, etc. are available via network. Due to the fact that we use some default credentials at some places, we should not expose the ports via docker-compose and instead only use the internal link mechanism.
There were some examples in the past where unprotected elasticsearch/mongodb servers were attacked, we should not make similar mistakes.

**Comment by emanueldima** [comment]
already fixed? see https://github.com/EUDAT-B2SHARE/b2share/issues/1399

**Comment by bne86** [comment]
No, you removed the explicit port mapping. Then he randomly uses other ports and those ports are still available to connect to.

**Comment by emanueldima** [comment]
more info: https://github.com/moby/moby/issues/22054
bne86's solution is correct

**Comment by emanueldima** [comment]
should be solved by https://github.com/EUDAT-B2SHARE/b2share/pull/1462, which includes @bne86's fix
