### ISSUE TITLE
global: Create a clear upgrade path from one B2SHARE version to another

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1428]
- [x] Add alembic script creating B2SHARE tables
- [x] Add a script initializing the `alembic_version` table as if alembic was the one who had created the tables in the first place.
- [x] Document how to upgrade. For any upgrade from 2.0.0 (and probably 2.0.x) there will be a special case as the init script will need to be called. For the following upgrades the existing alembic CLI command will be enough.
- [x] Add test for upgrading from a version containing the alembic scripts to another one.
- [x] Add test for upgrading from version 2.0.1, which is the last version before the addition of the alembic scripts, to the latest one.

**Comment by dinosk** [comment]
PR #[1469](https://github.com/EUDAT-B2SHARE/b2share/pull/1469) is opened for this feature. The development follows the pattern used for alembic in invenio modules. As [Flask-Alembic](http://flask-alembic.readthedocs.io/en/latest/) is used we can omit some alembic specifics such as env.py files and the alembic.ini. More documentation for this can be found in the Documentation.mdown file that is a WIP.  
- [x] Add alembic script creating B2SHARE tables
   In each of the modules that contain models (schemas, communities) an alembic directory is added that includes the scripts required to create the different versions of the models in the db.
- [x]  Add a script initializing the alembic_version table as if alembic was the one who had created the tables in the first place.
  For this requirement, the upgrade module is added in B2Share, which adds the `b2share upgrade run` command. This brings up the state of the DB to where alembic upgrades can be used, and handles the following:
   - upgrading from versions <= 2.0.1 which do not include the alembic scripts, but have already in place a working DB.
   - naming of constraints, required by alembic that may be missing.
- [] Document how to upgrade. For any upgrade from 2.0.0 (and probably 2.0.x) there will be a special case as the init script will need to be called. For the following upgrades the existing alembic CLI command will be enough. Will be extended until this is finished.
- [x] Add test for upgrading from a version containing the alembic scripts to another one.
  This is the easy case and the test is generic:
      - build the db with `alembic upgrade heads`
      - destroy it with `alembic downgrade *root*`
  Every in-between version is visited as revisions are linked.
- [ ] Add test for upgrading from version 2.0.1, which is the last version before the addition of the alembic scripts, to the latest one.
   This is the more complicated case, which includes testing of the upgrade module.

**Comment by emanueldima** [comment]
solved in 2.1.0
