### ISSUE TITLE
interface: editing records with multiple values only shows first

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1451]
When editing a record, only the first value for a possibly multivalued element is shown in a text field, no other text fields are visible. For example if a record has multiple titles.

**Comment by emanueldima** [comment]
possibly solved by https://github.com/EUDAT-B2SHARE/b2share/issues/1425, investigation needed

**Comment by emanueldima** [comment]
fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/1435
