### ISSUE TITLE
Disciplines UI vs API

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1479]
We should make it more clear how to add "disciplines" to the API calls. 
Apparantly there is a file /suggest/disciplines.json . This is not merely a 'suggestion', the UI actually does only accept these values.
 But I don't think the API validates on these values?

So, the test case is:
- submit a draft via API with "disciplines":["test value"]
- go to the draft URL via UI : disciplines is empty
- go to the draft URL via API: disciplines is filled
- publish the draft via UI or API
- there is still a difference where UI still does not display values that are not in disciplines.json

Proposed solution is to allow free-text disciplines via UI and indeed only have suggest/disciplines.json as suggestions.

**Comment by emanueldima** [comment]
Indeed; this issue is also part of https://github.com/EUDAT-B2SHARE/b2share/issues/1453

**Comment by thijscobben** [comment]
Duplicate issue.
