### ISSUE TITLE
Update API doc

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1487]
https://github.com/EUDAT-B2SHARE/b2share/blob/master/webui/src/docs/rest-api.jsx#L439

Here we should add some explanation that reference to the schema-id of the community specific metadata schema is required (if such a schema exists for the particular community) otherwise the record won't pass validation for publication.

**Comment by emanueldima** [comment]
related to https://github.com/EUDAT-B2SHARE/b2share/issues/1477

**Comment by hevp** [comment]
This is addressed in issue #1615.
