### ISSUE TITLE
UX: improve usability

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1489]
**Problem:**
The Aalto University has kindly done a usability test of B2SHARE last year. The results show that there are many issues to fix.
Refer to the report and slides from the Aalto university.

**This is a quite urgent task as the Aalto university is ready to do again some usability tests once we tell them B2SHARE is ready for it.**

**Comment by hevp** [comment]
Many things have changed for B2SHARE and therefore the assessment needs to be redone. Issue closed for now.
