### ISSUE TITLE
[Questions] - Starting

### ISSUE THREAD

**Issue by goncaloGIT** [EUDAT-B2SHARE/b2share#1493]
Hello EUDAT community

So i have a few question about b2share.

1- I have installed b2share with docker, but its a demo, so lets say i want to pass to production, how do i manage to do this ? i have to use the _v2-prod-instance_ right? but how ?

2 - When i try to login in b2share, this points me to B2ACCESS (https://unity.eudat-aai.fz-juelich.de:8443/home/home) , how do i point to my B2ACCESS instance, from what i understand i know i have to configure this file b2share.cfg, where do i find this file? ( in the demo or the production )

These questions are preety simple, but the instructions i found regarding to these two question were not clear.

Best Regards 
Gonçalo Barata

[EDIT]
i have already found  the b2share.cfg file, but when i change SITE_FUNCTION to production, gives me internal error, and i dint find anything related to b2access.
Also found this
>The provided docker-compose file is not production ready. 

My question still remains, how to go to production?

**Comment by emanueldima** [comment]
Thank you for your interest in the B2SHARE package. Switching a B2SHARE installation to production requires a good understanding of all its components and how they interact. The v2-prod-instance repository is only an example of how the configuration may look like, but is not complete. Backing up the database and the file data, for instance, is not covered. 

You may get more answers related to B2SHARE or other EUDAT services by using the ticketing system: https://eudat.eu/support-request.

**Comment by emanueldima** [comment]
discussion moved to the ticketing system
