### ISSUE TITLE
Deleting a record seems to not be possible due to various errors

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1501]
Deleting via HTTP DELETE triggers a server error:

````
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/views.py", line 296, in inner
    return f(self, pid=pid, record=record, *args, **kwargs)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/views.py", line 339, in need_record_permission_decorator
    verify_record_permission(permission_factory, record)
  File "/Users/edima/.virtualenvs/b2share-evolution/lib/python3.5/site-packages/invenio_records_rest/views.py", line 314, in verify_record_permission
    if not permission_factory(record=record).can():
TypeError: __init__() got an unexpected keyword argument 'record'
````

Deleting via the command line does something, but the record is still visible in the UI, even after reindexing or restarting. Deleting a record twice fails (`no row found`).

**Comment by nharraud** [comment]
related to inveniosoftware/invenio-pidstore#106 and inveniosoftware/invenio-records#173

**Comment by nharraud** [comment]
We need to mark all the linked PIDs as deleted. We should also decide if we delete the deposit and the files.

**Comment by nharraud** [comment]
The delete on the REST API needs to be implemented here:
https://github.com/EUDAT-B2SHARE/b2share/blob/bb5e553486f6826add4b046b59a618b7cddf0dcf/b2share/modules/records/views.py#L296
You can take a look at:
https://github.com/zenodo/zenodo/blob/pre-versioning-20170524/zenodo/modules/deposit/views.py#L150
Take care to delete from elasticsearch too:
https://github.com/zenodo/zenodo/blob/pre-versioning-20170524/zenodo/modules/deposit/views.py#L163

Only admin should be allowed to do it. We need to change the permission factory here:
https://github.com/EUDAT-B2SHARE/b2share/blob/bb5e553486f6826add4b046b59a618b7cddf0dcf/b2share/config.py#L171
with this one:
https://github.com/EUDAT-B2SHARE/b2share/blob/bb5e553486f6826add4b046b59a618b7cddf0dcf/b2share/modules/records/permissions.py#L71

To test the permission:
- authenticate to B2SHARE => create a user
- add administrator access => https://github.com/EUDAT-Training/B2SHARE-Training/blob/24e6796668a7c3f4bf38baeedf855ba83af41cd8/deploy/09_User_management.md#set-the-super-administrator
- try to delete a record
- try the same with a normal user and anonymous user.

**Comment by emanueldima** [comment]
closed by https://github.com/EUDAT-B2SHARE/b2share/pull/1529
