### ISSUE TITLE
File corruption after upload via API

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#1515]
When you upload an image file via WUI and you download the file the browser shows the picture. When you do this via HTTP API (upload) then the browser displays an error (corrupt image format). If you download that file via curl it seems to have added some MIME like header and the filesize indeed is about 100 bytes more than what was put in. The is read in 'rb' mode and submitted just as the API doc says. Also probably the checksum doesn't match.

The following code led to the observation: 
r = requests.post('https://trng-b2share.eudat.eu/api/records/',
                    params={'access_token': token}, data=json.dumps(metadata), headers=header)

res = r.json()
record_id = res['id']

header = {"Accept": "application/json", "Content-Type": "application/octet-stream”}
upload_file = {"file": open('EUDAT-logo2011.jpg', 'rb’)}
params = {'access_token': token}

r = requests.put(res['links']['files'] + '/EUDAT-logo2011.jpg',
                    files=upload_file, params=params, headers=header)

**Comment by nharraud** [comment]
I think there is an error in the documentation.
It should be:
```
curl -X PUT -H 'Accept:application/json' -H 'Content-Type:application/octet-stream' --data-binary @TestFileToBeUploaded.txt https://$HOSTNAME/api/files/$FILE_BUCKET_ID/TestFileToBeUploaded.txt?access_token=$ACCESS_TOKEN
```
Instead of:
```
curl -X PUT -H 'Accept:application/json' -H 'Content-Type:application/octet-stream' -d @TestFileToBeUploaded.txt https://$HOSTNAME/api/files/$FILE_BUCKET_ID/TestFileToBeUploaded.txt?access_token=$ACCESS_TOKEN
```

Note the `--data-binary` instead of `-d`

**Comment by nharraud** [comment]
It seems to me that the above code is trying to send a `multipart/form-data` with a `"Content-Type": "application/octet-stream"`. See [`requests` library documentation](http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file)

Multipart is supported but not like this. See [invenio-files-rest example](https://github.com/inveniosoftware/invenio-files-rest/blob/e0a5d9eb32e4240d92af7f6c944ee90fbe9c1fbb/examples/app.py#L142).

Can you try to do the upload [like this](http://docs.python-requests.org/en/master/user/advanced/#streaming-uploads) instead? This will still require the header `"Content-Type": "application/octet-stream"`.

**Comment by thijscobben** [comment]
Nicholas gave the right pointer. The last two lines now read:

f = open('IvankaMaxima.jpg','rb')
r = requests.put(res['links']['files'] + '/IvankaMaxima.jpg',
   data=f, params=params, headers=header)

and that resolves the issue - training material can be updated.

**Comment by hevp** [comment]
Training material: https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/api/05_Create_new_record.md#add-files-to-your-new-draft-record
Documentation: https://eudat.eu/services/userdoc/b2share-http-rest-api#upload-file-into-draft-record
