### ISSUE TITLE
Enable file checks task

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1538]
**Problem:**
We currently don't have anything checking that the files have not been corrupted. We need to have a task running on a regular basis which will notify the admin in case a file is corrupted or missing.

**Solution:**
Invenio-files-rest provides the code doing this check. We should enable it.

**Comment by emanueldima** [comment]
Could you point to the invenio-files-rest function/code that does it?

**Comment by nharraud** [comment]
Something [like this](https://github.com/zenodo/zenodo/blob/d89c9a83f3885b7067a30834baf1b16bac4b96e5/zenodo/config.py#L169) but we need to check exactly the parameters. Zenodo uses a different pyFileSystem driver.

**Comment by nharraud** [comment]
We also need a small test to check that it works correctly. This is critical feature. Test could be:
- upload a file
- check the checksum
- modify the file directly on the filesystem
- check the checksum and catch whatever warning is sent.

We need to see what warning is sent, if there is any. I know that there is a UI to see files in Invenio but we don't have it so we might have to implement the warning ourselves, and maybe add later a UI for the admin.

**Comment by dinosk** [comment]
Addressed by https://github.com/EUDAT-B2SHARE/b2share/pull/1543. This can be closed afterwards.
