### ISSUE TITLE
docs: Update rest api documentation

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1541]
- [x] document changing published record's metadata
- [x] JSONPath `/title` mentioned in the doc is not correct anymore, replace with `/titles/0/title`
- [x] show examples for community specific fields

**Comment by janiheikkinen** [comment]
https://b2share.eudat.eu/help/api :
"The patch format contains one or more JSONPath strings. The root of these paths are the metadata object, as this is the only mutable object. For instance, to update the title field of the record, use this JSONPath: /title"

The correct, relative path to community specific metadata is in form "/community_specific/<community_specific_uuid>/<field> ?

**Comment by emanueldima** [comment]
@janiheikkinen Yes, the path to a community specific metadata field is `/community_specific/<community_specific_uuid>/<field>`

**Comment by hevp** [comment]
Source: https://github.com/EUDAT-B2SHARE/b2share/blob/master/webui/src/docs/rest-api.jsx
