### ISSUE TITLE
api: add bucket id to the record results

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#1547]
**Problem:**
- Some communities need for security reasons to generate the URLs to the B2SHARE REST API instead of using the ones returned by this API.
- The only way to know the files bucket ID of a record or draft record is to parse the URI in the "links" field or in the header.

**Discussion:**
This requires some discussion. Do we want to add the bucket ID in the response, and if yes, where do we put it.

**Requirement origin:**
- *Support tickets:* 11177

**Comment by hevp** [comment]
The files section of the record API response contains a bucket field for each file, this should be enough. Issue closed.
