### ISSUE TITLE
Add EUDAT ToU on the front page of production/training/test server

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1560]
[Request from Johannes]

The agreed ToU is here:
http://hdl.handle.net/11304/e43b2e3f-83c5-4e3f-b8b7-18d38d37a6cd

I kindly ask all of you who are responsible for one of the B2services or
the operational services, to expose this link (as hyperlink) under the
name *EUDAT Services ToU v1.1*.

This ToU, which basically serves as a disclaimer, should be widely
acceptable.

This links should also be used as pointer to the ToU which is one field
in the service descriptions of the service catalogue.

**Comment by dinosk** [comment]
I think that the PID of the file in this [record](https://b2share.eudat.eu/records/398e55b3f2c44b89bacce36f4764cee2) in prod doesn't work. It doesn't seem to redirect anywhere.

**Comment by emanueldima** [comment]
@dinosk The PID of the record should point to the record page, and the PID of the file should point to the file content. Is this not the case?

**Comment by dinosk** [comment]
@emanueldima Yes it works now. Not sure what was the issue.

**Comment by emanueldima** [comment]
https://github.com/EUDAT-B2SHARE/b2share/pull/1571
