### ISSUE TITLE
Bad community admin URL shown in user profile page

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1575]
The community admin page (displayed next to the admin role in the user profile page) points to /communities/undefined/admin

**Comment by SarahBA** [comment]
@emanueldima For which communities you are getting this wrong URL? I only have this issue for 'Aalto' community. The rest are ok.

**Comment by emanueldima** [comment]
@SarahBA Yes, that seems to be true. I'm not sure what can cause such a bug.

**Comment by emanueldima** [comment]
also reproduces on a clean installation of v2.0.1

**Comment by SarahBA** [comment]
Fixed in https://github.com/EUDAT-B2SHARE/b2share/pull/1620
