### ISSUE TITLE
Update docs for uploading files (problem with image files)

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#1591]
When uploading .png files with the API one receives an http 415 error while when uploading the same file through the web interface works.

**Comment by emanueldima** [comment]
I wonder if this is related: https://github.com/EUDAT-B2SHARE/b2share/issues/1515

**Comment by chStaiger** [comment]
Hi Emmanuel,

Yes that actually did the trick. Everything works now by setting the  headers appropriately:

```sh
headers = {'Accept':'application/json','Content-Type':'application/octet-stream --data-binary'}
```

Issue solved.

**Comment by hevp** [comment]
Source: https://github.com/EUDAT-B2SHARE/b2share/blob/master/webui/src/docs/rest-api.jsx

**Comment by hevp** [comment]
Updated API documentation:
https://eudat.eu/services/userdoc/b2share-http-rest-api#upload-file-into-draft-record
