### ISSUE TITLE
Update user documentation for B2Share 2.1.0

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#1616]
B2Share 2.1.0 is now released. This issue will list all the things which need to be modified/added/removed.
@emanueldima @thijscobben @SarahBA @dinosk Don't hesitate to add anything I missed.
The training server is already updated so it is possible to take screenshots.

CC @hevp

Upgrading
========

- [ ] How to upgrade from 2.0.0 or 2.0.1 => 2.1.0

Versioning
========

B2Share now enables the creation of new versions of a given record. All versions of a given record are linked.
- Every version has its own PIDs.
- The files of the last version are referenced in the new version without copying the files.

API
---
- [x] NEW Possibility to create a new version of a record.
  - Without metadata -> copy the metadata of the last version.
- [x] NEW Listing versions of a given record (new element in the "links" section).

User Interface
--------------
- [x] NEW Button "Create New Version" enabling the creation of a new version of a record. It is only visible on the last version of a record.
- [x] NEW Dropdown on any record page listing all the record versions.
- [x] NEW Warning displayed if the currently displayed record is not the last version.

UI and API
----------
- [x] CHANGE The record search only returns the last version of every record.

Statistics
=======

- [x] NEW The number of file downloads are now displayed next to each file.
  - If the count is 0, it is not displayed.
  - The statistics update is not realtime. The goal is long-term statistics.
  - The statistics are deduplicated. It will only be incremented once if a user downloads multiple-time the same file in a 10 seconds window.

- [x] CHANGE The elasticsearch database must also be backuped as it is used to store and compute statistics.

File Checksum Verification (Fixity check)
==============================

- [x] NEW A regular task is ran by Celery in order to check that the files are not corrupted.
- [ ] NEW An email is sent to the administrator if some files are corrupted or if they cannot be checked (ex: file system is not accessible).

B2Note integration
==============

- [x] CHANGE B2Note can now be integration in production mode too (previously only testing deployments could enable it).

New Handle API (minor change)
=======================

- [x] CHANGE The new B2Handle API is used instead of the old EPIC API.

Record deletion via REST API
=====================

- [x] NEW Super Administrator can now delete a record via the REST API. Previously only the draft records could be deleted.
 - This deletes the draft record too.
 - The files are not removed from the filesystem. A garbage collector will be added later.

User Interface Customization
=====================
- [ ] NEW document customisation of UI for communities (by creating a new docker image)

**Comment by hevp** [comment]
Completed
