### ISSUE TITLE
Community specific metadata description missing after schema update

### ISSUE THREAD

**Issue by janiheikkinen** [EUDAT-B2SHARE/b2share#1619]
After updating the community specific metadata schema, the specific part is not shown in the schema description page <base>/communities/ . v.2.1.0 and v2.0.1.

**Comment by emanueldima** [comment]
see https://trng-b2share.eudat.eu/communities/EISCAT, check the console (error)

**Comment by emanueldima** [comment]
Displaying the metadata schema and creating a new records do not work if the block_schema is updated, but work correctly if an entirely new block_schema is created and used to define the new community schema.

**Comment by emanueldima** [comment]
This is caused by a missing items declared in the EISCAT schema: the presentation order contains the 'position' property, but this property is not actually available in the schema. An additional check which would fix this problem is in the linked PR.

**Comment by nharraud** [comment]
Note: this is also related to #1623
