### ISSUE TITLE
Wrong bucket ID in versioned record returned metadata after submitting through REST API

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1633]
After submitting a PATCH request for a versioned draft record to B2SHARE through the REST API with a change in `publication_state` to `submitted`, the __returned__ metadata contains the old draft file bucket ID, which is no longer valid thereafter. In the B2SHARE web interface of [that record](https://trng-b2share.eudat.eu/records/2ff3f5815db3494a840e6b3f1e6a6542) the right file bucket ID is used for the file links. Is the former intended or a bug? Also the file metadata is missing.

See the [B2SHARE training documentation on record versioning](https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/api/08_Record_versioning.md#submitting-a-json-patch-to-publish-the-new-version) on the returned metadata.

**Comment by emanueldima** [comment]
I would classify this issue as a documentation defect. What is actually being returned is the draft record, and not the published record. The draft record obviously contains reference to the draft bucket, and because it's not yet published (could still change, depending on the curation results) does not have information about the files. I'm not sure how we can improve the submission step for this to become more obvious.

**Comment by nharraud** [comment]
Yes this is indeed the intended behavior. One of the core REST API principles is "1 URL = 1 entity". A PATCH request on a draft URL will always return the draft, even if the PATCH operation also publishes the record.
In the documentation I would present this as follow:

Doc suggestion
---------------
The draft record and the published record are two separate entities. They have separate URLs:
* draft record: `https://<B2HOST>/api/records/<RECORD_ID>/draft``
* published record: `https://<B2HOST>/api/records/<RECORD_ID>``

The `RECORD_ID` is the same in both cases. A PATCH operation on a draft will always return the draft object. If the operation also publishes the record, the draft record will have a link named `publication` corresponding to the published record URL.

cc: @hevp

**Comment by hevp** [comment]
Understood. I have updated the training documentation on [record creation](https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/api/05_Create_new_record.md) and [versioning](https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/api/08_Record_versioning.md) to clarify this.

**Comment by nharraud** [comment]
@hevp Great work ! 👍  The documentation looks really good.
