### ISSUE TITLE
Serializer doesn't check for owners when filtering internal fields. 

### ISSUE THREAD

**Issue by dinosk** [EUDAT-B2SHARE/b2share#1636]
The serializer when filtering the [internal fields](https://github.com/EUDAT-B2SHARE/b2share/blob/master/b2share/modules/records/serializers/schemas/json.py#L44) doesn't check if the request is coming from the owner of the record, so it is not easy to hide the external_pids when a record is embargoed.
We could always show it, exposing keys and PIDs for external files but hide it from the search results as a middle solution.
The output wouldn't be identical anymore for search results and individual records though.

**Comment by thijscobben** [comment]
OK I have a question here: what we show is not so much the external PID but the file bucket with the key to the PID ? The external_pid is only used to create / patch a draft?

**Comment by dinosk** [comment]
In the UI link we show the bucket and key, but when sending a GET to the records rest API you would get the external_pids list with the ePIC_PIDs and everything even when the user was unauthorized. This is what I'm currently working on in https://github.com/EUDAT-B2SHARE/b2share/pull/1640

**Comment by hjhsalo** [comment]
I think this has been fixed in #1640
