### ISSUE TITLE
Metadata dumps

### ISSUE THREAD

**Issue by raquelribeirogithub** [EUDAT-B2SHARE/b2share#1670]
I am a Master's student at the University of Porto.
I'm working on a project of datasets classification and I need a file with metadata of public datasets. Can EUDAT provide me such a file or metadata dumps?

Also, is it possible to retrieve record metadata from B2SHARE in XML or RDF format? I need to know the exact metadata descriptors used in the records. For example, titles is a metadata descriptor with many possible values (it is an array when I retrieve it from the API); how do I know if it corresponds to the DC Title descriptor and not any other?

Sincere appreciation.

**Comment by hjhsalo** [comment]
Hi @raquelribeirogithub 

> I'm working on a project of datasets classification and I need a file with metadata of public datasets. Can EUDAT provide me such a file or metadata dumps?

If other formats than XML or RDF are an option for you, you could try B2SHARE REST API and see if it fits your needs. It outputs record metadata in JSON.

> Also, is it possible to retrieve record metadata from B2SHARE in XML or RDF format?

EUDAT B2SHARE provides an [OAI-PMH](https://www.openarchives.org/OAI/openarchivesprotocol.html) endpoint at `b2share.eudat.eu/api/oai2d` which outputs record metadata in DublinCore or MARC XML formats. Note that currently community specific metadata is not exposed through OAI-PMH.

>  I need to know the exact metadata descriptors used in the records. For example, titles is a metadata descriptor with many possible values (it is an array when I retrieve it from the API); how do I know if it corresponds to the DC Title descriptor and not any other?

Unfortunately the export / serialization of record metadata in a specific format such as DublinCore or MARC XML is currently not documented in a presentable way.
However, if you need to have this information now, you could check source code of e.g. DublinCore serializer used in EUDAT B2SHARE (https://github.com/EUDAT-B2SHARE/b2share/blob/master/b2share/modules/records/serializers/schemas/dc.py#L46) and map that with the key names of JSON-Schema description of non-community specific metadata (https://github.com/EUDAT-B2SHARE/b2share/blob/master/b2share/modules/schemas/root_schemas/root_schema_v0.json) and with an API response of `/api/records/<RECORD_UUID>`.
