### ISSUE TITLE
Clean up wiki

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1675]
The wiki contains a lot of outdated information and pages. This needs to be clean up. Also a lot of information is available elsewhere, therefore we need to decide which location is leading and whether only a single location is preferable.

Pages that can potentially be removed:
- https://github.com/EUDAT-B2SHARE/b2share/wiki/How-to-add-new-communities (obsolete)
- https://github.com/EUDAT-B2SHARE/b2share/wiki/REST-API (shown in service docs)
- https://github.com/EUDAT-B2SHARE/b2share/wiki/Release-Notes (this is shown at the releases overview)

Deprecated pages should have a deprecated message on top of the page.

**Comment by hevp** [comment]
Wiki updated

@hjhsalo can you review the changes?

**Comment by hjhsalo** [comment]
Reviewed. LGTM. Closing
