### ISSUE TITLE
Make /api/communities/COMMUNITY_ID a public endpoint

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1677]
The endpoint `/api/communities/COMMUNITY_ID` is currently private. It requires authentication and specific permissions.

This information is public (as it is supplied in the `/api/communities` data) and should be accessible without authentication.

**Comment by hjhsalo** [comment]
Check

https://github.com/EUDAT-B2SHARE/b2share/blob/520326cd8eccc5e1e14bebc60a4db0c7a50732e4/b2share/modules/communities/views.py#L238

https://github.com/EUDAT-B2SHARE/b2share/blob/520326cd8eccc5e1e14bebc60a4db0c7a50732e4/b2share/modules/communities/views.py#L74
