### ISSUE TITLE
Remove or modify Horizon 2020 grant information from B2SHARE UI

### ISSUE THREAD

**Issue by hjhsalo** [EUDAT-B2SHARE/b2share#1678]
This should probably be removed or at least changed since EUDAT B2SHARE doesn't receive funding from Horizon 2020 grant anymore. 

![issue_eudat2020_grant_screenshot](https://user-images.githubusercontent.com/9445833/51464799-160c7000-1d6f-11e9-8960-43eafaf80b1b.png)

**Comment by hevp** [comment]
This has been addressed in a 2.1.x release.
