### ISSUE TITLE
Missing documentation for dockerize installation

### ISSUE THREAD

**Issue by pagecp** [EUDAT-B2SHARE/b2share#1690]
When testing the dockerize version, there is no documentation on values to use for:
B2SHARE_POSTGRESQL_DBNAME= 
B2SHARE_POSTGRESQL_PASSWORD=
B2SHARE_RABBITMQ_USER=
B2SHARE_RABBITMQ_PASS=

**Comment by hevp** [comment]
Documentation has been clarified.

Please see: https://github.com/EUDAT-Training/B2SHARE-Training/blob/master/deploy/04_Installation.md
