### ISSUE TITLE
Community listing is not sorted on many occassions

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1705]
The drop-down element to set a community filter on the search page is not sorted.

<img width="374" alt="Screenshot 2019-08-02 at 12 26 09" src="https://user-images.githubusercontent.com/4790568/62364027-cd552100-b520-11e9-92e5-3fee9ba94c8b.png">

This makes it difficult to find the right community with many communities in the list.

This also applies to:
- The communities overview page: https://b2share.eudat.eu/communities
- The API endpoint: https://b2share.eudat.eu/api/communities/
- The create new record page: https://b2share.eudat.eu/records/new

Solutions:
- Add sorting to the [query](https://github.com/EUDAT-B2SHARE/b2share/blob/master/webui/src/data/server.js#L32)
- Sort the [result](https://github.com/EUDAT-B2SHARE/b2share/blob/master/webui/src/components/search.jsx#L113) in ReactJS code

**Comment by stefan-wolfsheimer** [comment]
Fixed in the communtiy api end point: communties are ordered by name.
Tested:
* search select box
* community page
* api list community
