### ISSUE TITLE
Expired staging certificate

### ISSUE THREAD

**Issue by pgancarski** [EUDAT-B2SHARE/b2share#1706]
staging_b2access.pem expired on July 9, 2019.
Causes b2share to fail to accept replies from https://unity.eudat-aai.fz-juelich.de/ when USE_STAGING_B2ACCESS is enabled

**Comment by hjhsalo** [comment]
Hi @pgancarski 
Thanks for reporting the issue.

Commenting out lines 29-31 of 'b2share.sh' will fix the problem (https://github.com/EUDAT-B2SHARE/b2share/blob/a19da6362f30405fde116a34bf2e83da72865034/dockerize/b2share.sh#L29-L31).

We will fix the issue for next version of B2SHARE, but in the meantime have a look at EUDAT-B2SHARE/dockerize#10 which includes a one possible workaround for now.

**Comment by pgancarski** [comment]
Replacing the certificate with the latest one from the  https://unity.eudat-aai.fz-juelich.de/ website fixes the issue.
[staging_b2access.pem.zip](https://github.com/EUDAT-B2SHARE/b2share/files/3502548/staging_b2access.pem.zip)

**Comment by hjhsalo** [comment]
Thanks.
We will probably include the update cert in an updated Docker Image.
I will leave the issue open until this Docker Image is released.

**Comment by hjhsalo** [comment]
Closing since B2SHARE v2.1.3 has been released and it removes the unnecessary certificate file altogether. Dockerfile available in Docker Hub. EUDAT-B2SHARE/dockerize updated.
