### ISSUE TITLE
Community landing page must throw error on non-existent community request

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1720]
Using a random name for the community landing page, no error is thrown: https://eudat-b2share-test.csc.fi/communities/Non-existingCommunity

Instead 'Loading...' is shown and nothing ever happens.

**Comment by apw1388** [comment]
Also belonging to this, the community name could be case insensitive. E.g. the community with capital letters exist: https://eudat-b2share-test.csc.fi/communities/EUDAT but with small letters is loading: https://eudat-b2share-test.csc.fi/communities/eudat
