### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by CENER-EPR** [EUDAT-B2SHARE/b2share#1730]
B2SHARE fails with any version of IE.
To fix we can import a polyfill script to `/webui/src/main.jsx`

`import './browser-polyfill.min.js'; `

The file is available at:
[browser-polyfill.min.js](
 https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js)

Tested to work with Win10, IE11

**Comment by hevp** [comment]
IE11 is EOL. Not implemented.
