### ISSUE TITLE
Adding small files from B2DROP in B2SHARE record form fails

### ISSUE THREAD

**Issue by hevp** [EUDAT-B2SHARE/b2share#1748]
From helpdesk #13086:

Adding files from B2DROP to B2SHARE record in B2SHARE interface.

PDF-files works fine. However, when adding a txt or json-file,
the file-upload stops with the message "Error: Internal Server
Error".

**Comment by hevp** [comment]
The following error occurs:

```
File is bigger than expected.
```

It appears that the offered file is gzip-encoded, therefore the file length is different than the reported file length.

**Comment by hevp** [comment]
Workaround: do not provide an expected file size for encoded files, as handled by Invenio.

**Comment by TillF** [comment]
Workaround for users: upload the small files from local disk instead of B2DROP.
