### ISSUE TITLE
Facilitate finding own records / drafts

### ISSUE THREAD

**Issue by TillF** [EUDAT-B2SHARE/b2share#1749]
After logging on to B2SHARE, I can see links to "Create Record" and "Latest records" (of other people), but no link to *my* records nor drafts - however, this is presumably the reason why I logged on. 
I know my records can be found under "my name" -> "Profile", but I think this is an awkward place to look for them.
I suggest to have them linked right at the landing page of b2drop.

**Comment by hevp** [comment]
Two links have been added in user dropdown menu, that should help plenty.

**Comment by TillF** [comment]
I am not sure what you mean with "user dropdown menu". In my case, I can only see the link "Profile", which then leads to the list of records (see screenshot). 
![b2share](https://user-images.githubusercontent.com/11060560/74518684-91aa0380-4f14-11ea-82c6-a53c58d07bfc.png)

My point is that I would expect to find account specific settings under "Profile", not the records.
Conversely, when logging into B2SHARE I am want to "Store and Publish [my] research data" (as stated on the page heading). As such, I don't see much use in having presented "Latest Records" of other people. "Create record" (already in place) and an overview of the personal records (still missing) would make more sense to me.

**Comment by hevp** [comment]
Although I get your point, for now we will keep this structure on the front page, even after logging in.

B2SHARE is not meant for solely personal storage of research data, instead it allows publishing of data sets and thus share it with others. Therefore the front page contains an overview of the latest published records.
