### ISSUE TITLE
Show PID or DOI even if one of them is missing.

### ISSUE THREAD

**Issue by defnull** [EUDAT-B2SHARE/b2share#1839]
The current UI logic in https://github.com/EUDAT-B2SHARE/b2share/blob/master/webui/src/components/record.jsx#L324 hides both PID and DOI if one of them is missing. Is there a reason for that? Could we replace `&&` with `||` so that available handles are shown?

**Comment by hevp** [comment]
Hello, thanks for reporting.

This has been addressed in code for the next release and will be available soon.
