### ISSUE TITLE
Export OpenAIRE metadata via OAI-PMH

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#302]
see this link for details: [OpenAIRE_Guidelines:_For_Data_Archives#Use_of_OAI-PMH](https://guidelines.openaire.eu/wiki/OpenAIRE_Guidelines:_For_Data_Archives#Use_of_OAI-PMH)

Alessia Bardi <alessia.bardi@isti.cnr.it> is the metadata expert to contact if needed

**Comment by cjhak** [comment]
Postponed till EUDAT2020

**Comment by lnielsen** [comment]
FYI I'm editor of the guidelines so I can easily help you. E.g. in Zenodo I already have a XSLT that does the transformation that you can use as a start.

**Comment by emanueldima** [comment]
Depends on this one: https://github.com/EUDAT-B2SHARE/b2share/issues/303

**Comment by cjhak** [comment]
Closing this issue as OpenAIRE metadata will be handled in B2FIND and not in B2SHARE.
