### ISSUE TITLE
Add new community/domain extension: OpenAIRE

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#303]
The metadata details can be found here: 
[OpenAIRE_Guidelines:_For_Data_Archives](
https://guidelines.openaire.eu/wiki/OpenAIRE_Guidelines:_For_Data_Archives)

Alessia Bardi <alessia.bardi@isti.cnr.it> is the OpenAIRE metadata expert to contact if needed

**Comment by cjhak** [comment]
Postponed till EUDAT2020

**Comment by cjhak** [comment]
Closing the issue; OpenAIRE metadata will be handled in B2FIND and not in B2SHARE.
