### ISSUE TITLE
Travis: inveniomanage doesn't collect b2share static assets

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2SHARE/b2share#319]
For some reason b2share/modules/*'s static assets are not collected by "inveniomanage collect" during the Travis runs.

This worked before modules/b2share was split into b2share/modules.

To check whether this reproduces, look for the following error in the Travis output: `Missing asset file: css/b2s-common.css`

**Comment by emanueldima** [comment]
Didn't have any problems lately, even more so after we migrated to invenio2
