### ISSUE TITLE
Help page not showing search fields etc.

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#408]
The help pages, like `help/search-tips` and `help/search-guide` are not showing the search input (among other things). I think it's not clear to users how to proceed.

![screen shot 2014-09-19 at 12 26 47](https://cloud.githubusercontent.com/assets/395001/4333984/be626f3a-3fe7-11e4-9f0c-d08a5005ecbf.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
