### ISSUE TITLE
Search options `simple and advanced` not intuitive

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#410]
The search input extra controls seems to have simple and advanced tabs reversed.

![screen shot 2014-09-19 at 12 39 09](https://cloud.githubusercontent.com/assets/395001/4334085/38813282-3fe9-11e4-9ac7-0c99a7faa83d.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
