### ISSUE TITLE
Search advanced options `+ Add to search` not working

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#411]
Search options `advanced` tab is showing the `+ Add to search` button, but when pressing it the site redirects to some sort of overview, not adding any keywords to the search. I basically don't understand the working of the feature.

![screen shot 2014-09-19 at 14 21 12](https://cloud.githubusercontent.com/assets/395001/4335067/db716742-3ff7-11e4-8247-17ff8bde99e6.png)

**Comment by emanueldima** [comment]
As the UI will change completely in B2SHARE2, this issue is no longer relevant.
