### ISSUE TITLE
Firefox search bar text-input width too small

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#415]
In firefox the text-input field is not set to the full width of its container:

![screen shot 2014-09-22 at 11 01 39](https://cloud.githubusercontent.com/assets/395001/4353742/15d3b980-4237-11e4-9a6d-2f962bf155f2.png)

This issue has a side effect, advanced search options are now redering inline with the text-input:
![screen shot 2014-09-22 at 11 02 31](https://cloud.githubusercontent.com/assets/395001/4353757/4b4e2bea-4237-11e4-9acf-f759eb0d915d.png)

If we increase the width of the text-input, this issue should be solved.

**Comment by emanueldima** [comment]
On Firefox 34, now, both production and test site are correctly rendered.

**Comment by dblommesteijn** [comment]
With the #600 Invenio2 merge this bug reappeared.
