### ISSUE TITLE
Mobile: header logos don't fit

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#416]
On mobile devices the headers are not visible. To fix this we need the original designs. Below is a screenshot with the issue. 
Original issue: https://github.com/EUDAT-B2SHARE/b2share/issues/297

![screen shot 2014-09-22 at 15 58 41](https://cloud.githubusercontent.com/assets/395001/4359078/3759e61e-426f-11e4-9378-dc3e254957ec.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
