### ISSUE TITLE
Mobile: footer offset for pages is not aligned correctly

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#417]
On mobile devices, footer text is not aligned properly, as shown below.
Original issue: #297

![screen shot 2014-09-22 at 15 59 19](https://cloud.githubusercontent.com/assets/395001/4359134/97181436-426f-11e4-8852-c0c65d398a3b.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
