### ISSUE TITLE
Mobile: login page placement below deposits

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#418]
On mobile devices the placement of login information is below the list of latest deposits. Moreover, the width of the box is to wide to display correctly.
Original issue: #297

![screen shot 2014-09-22 at 17 49 05](https://cloud.githubusercontent.com/assets/395001/4359187/01329288-4270-11e4-87cb-3ee78e5d4576.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
