### ISSUE TITLE
Mobile: b2share logo inline overflowing text

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#419]
On mobile devices the (inline) b2share logo is overflowing headers and text. 
Original issue: #297

![screen shot 2014-09-22 at 16 02 11](https://cloud.githubusercontent.com/assets/395001/4359214/34ea9c24-4270-11e4-9eb2-c1737000ce53.png)

**Comment by cjhak** [comment]
Resolved by new design.
