### ISSUE TITLE
Mobile: search-bar not collapsing, placeholder not visible

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#420]
On mobile devices the search-bar is not collapsing into it's bootstrap build-in collapsed form: http://getbootstrap.com/components/#navbar
Original issue: #297

![screen shot 2014-09-22 at 16 11 06](https://cloud.githubusercontent.com/assets/395001/4359260/8998914a-4270-11e4-93cc-1603e66d3d4a.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
