### ISSUE TITLE
Mobile: search-bar `add to search` and `options` dropdown expand

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#422]
On mobile devices, when expanding both `add to search`, and `options` (right dropdown menus), the containing div doesn't expand to contain both option sets.
Original issue: #297

![screen shot 2014-09-22 at 18 00 59](https://cloud.githubusercontent.com/assets/395001/4359433/adce70ce-4271-11e4-95b4-c575253eba9b.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
