### ISSUE TITLE
Russian language on buttons and dropdown

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#423]
On the test server, some option-selects and buttons on [search tips](https://test-eudatis.csc.fi/help/search-tips) page appears in Russian. I think it's a locale setting issue.

*The production (and local development) environments don't show this issue.*

![screen shot 2014-09-23 at 10 07 29](https://cloud.githubusercontent.com/assets/395001/4369183/b00ef3fe-42f8-11e4-9b8a-5fbd454f9d0c.png)

**Comment by dblommesteijn** [comment]
On [help-central](https://test-eudatis.csc.fi/help/contents) on the test server it still shows Russian links. Locale settings wrong?

**Comment by cjhak** [comment]
Moving issue to B2SHARE 2.0, to be followed up when 2.0 is deployed on the test server.

**Comment by llehtine** [comment]
Tried to reproduce it now, and it seems that atleast contests is rendering correctly. Can this be closed?
