### ISSUE TITLE
Mobile: search-help examples don't resize

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#424]
On mobile devices `help` pages are not optimised. On [search guide](https://test-eudatis.csc.fi/help/search-guide) for example, the examples should be replaced by images, which can resize, for example.

**[Search-tips](https://test-eudatis.csc.fi/help/search-tips):**
![screen shot 2014-09-23 at 10 10 46](https://cloud.githubusercontent.com/assets/395001/4369204/2804eb5c-42f9-11e4-89ca-b905baa69b21.png)

**[Search-guide](https://test-eudatis.csc.fi/help/search-guide):**
![screen shot 2014-09-23 at 10 12 05](https://cloud.githubusercontent.com/assets/395001/4369214/52eeda58-42f9-11e4-9222-8dbefa7499f0.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
