### ISSUE TITLE
Help central missing

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#427]
The main help page `help-central` is missing. Perhaps we should add a page redirect from: https://test-eudatis.csc.fi/help to https://test-eudatis.csc.fi/help/contents.
![screen shot 2014-09-24 at 10 51 47](https://cloud.githubusercontent.com/assets/395001/4385703/08f0868e-43c8-11e4-9279-c98d60a50191.png)

**Comment by cjhak** [comment]
Fixed by Invenio upgrade.
