### ISSUE TITLE
Change b2share code and structure to conform to the Invenio overlay docs

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#433]
See http://invenio.readthedocs.org/en/latest/index.html and http://invenio.readthedocs.org/en/latest/getting-started/overlay.html
Suggested changes:
- [ ] rename main to base
- [ ] add b2share/base/config.py, populate with settings from install_b2share.sh which are not site-dependent
- [x] move css/js assets definition from jinja to python
- [ ] add version.py
- [ ] move templates from core to module

**Comment by emanueldima** [comment]
Irrelevant, closing it for now

**Comment by jirikuncar** [comment]
> Irrelevant

I'm trying to understand why? The majority of projects using Invenio *next*/*2.0* is already using the recommended overlay structure. Do you have any specific problem that prevents you to make the migration?

**Comment by emanueldima** [comment]
I can't say I have a complete picture of how the overlay structure works in details, but I assume that it's not possible to change the behavior of the invenio python code using an overlay. For instance, we modified the invenio `records/views.py` file in our fork. Can we get the same functionality using an overlay? And if we can, how much does it cost us now (in term of code complexity and developer time)? The approach I'm taking here is to wait until both b2share and invenio will become more stable (a slower rate of code changes).

**Comment by jirikuncar** [comment]
@emanueldima I understand your concerns. CDS/Zenodo had similar problem that they needed to modify context of given endpoint without editing the file. Please check following issue https://github.com/inveniosoftware/invenio/issues/2009 and PR https://github.com/inveniosoftware/invenio/pull/2026. I hope it will help you in the future.
