### ISSUE TITLE
views-error from the production system

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#440]
Hello:

This exception has already been seen 1 times
    last time it was seen: 2014-10-02 10:54:51
    last time it was notified: 2014-10-02 10:54:51
- 2014-10-02 10:54:51 -> TypeError: 'NotImplementedType' object is not callable (views.py:131:members)

*\* User details
                                     agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0
                        dashboard_settings: {'orderRight': u'WebTagSettings', 'orderLeft': [u'WebAlertSettings', u'WebMessageSettings'], 'orderMiddle': [u'WebAccountSettings', u'WebSearchSettings', u'WebBasketSettings']}
                                     email: r.pool@vu.nl
                                     group: [u'VUBioPsy']
                                     guest: 0
                                        id: 137
                              login_method: Local
                                  nickname: rinipool
                                      note: 1
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: True
                      precached_useapprove: False
                      precached_usebaskets: True
                       precached_usegroups: True
                        precached_useloans: True
                     precached_usemessages: True
             precached_usepaperattribution: True
                   precached_usepaperclaim: True
                        precached_usestats: False
                   precached_usesuperadmin: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: https://b2share.eudat.eu/yourgroups/index
                               remote_host:
                                 remote_ip: 145.108.164.6
                                   session: None
                                  settings: {'login_method': 'Local', 'dashboard_settings': {'orderRight': u'WebTagSettings', 'orderLeft': [u'WebAlertSettings', u'WebMessageSettings'], 'orderMiddle': [u'WebAccountSettings', u'WebSearchSettings', u'WebBasketSettings']}}
                                       uid: 137
                                       uri: </yourgroups/members/1>

*\* Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/**init**.py", line 60, in **call**
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/**init**.py", line 258, in error_router
    return original_handler(e)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/groups/views.py", line 131, in members
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable

*\* Stack frame details
## Frame members in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/groups/views.py at line 131

```
   128 @blueprint.route('/members/<int:id_usergroup>', methods=['GET', 'POST'])
   129 def members(id_usergroup):
   130     """List user group members."""
```

---->  131     raise NotImplemented()
       132
       133
##        134 @blueprint.route("/search", methods=['GET', 'POST'])

```
            id_usergroup =  '1'
```
## Frame dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1461

```
  1458            and req.method == 'OPTIONS':
  1459             return self.make_default_options_response()
  1460         # otherwise dispatch to the handler for that endpoint
```

----> 1461         return self.view_functions[rule.endpoint](**req.view_args)
      1462
      1463     def full_dispatch_request(self):
##       1464         """Dispatches the request and on top of that performs request

```
                    self =  "<Flask 'invenio.base'>"
                     req =  "<LegacyRequest 'https://b2share.eudat.eu/yourgroups/members/1' [GET]>"
                    rule =  "<Rule '/yourgroups/members/<id_usergroup>' (HEAD, POST, OPTIONS, GET) -> webgroup.members>"
```
## Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477

```
  1474             if rv is None:
  1475                 rv = self.dispatch_request()
  1476         except Exception as e:
```

----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
##       1480         request_finished.send(self, response=response)

```
                      rv =  'None'
                       e =  'TypeError("\'NotImplementedType\' object is not callable",)'
                    self =  "<Flask 'invenio.base'>"
```
## Frame handle_user_exception in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1381

```
  1378             if isinstance(e, typecheck):
  1379                 return handler(e)
  1380
```

----> 1381         reraise(exc_type, exc_value, tb)
      1382
      1383     def handle_exception(self, e):
##       1384         """Default exception handling that kicks in when an exception

```
                       e =  'TypeError("\'NotImplementedType\' object is not callable",)'
                handlers =  'None'
                    self =  "<Flask 'invenio.base'>"
               exc_value =  'TypeError("\'NotImplementedType\' object is not callable",)'
      blueprint_handlers =  '()'
            app_handlers =  '()'
                      tb =  '<traceback object at 0x7f29fa725dd0>'
                exc_type =  "<type 'exceptions.TypeError'>"
```
## Frame handle_user_exception in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py at line 125

```
   122         Hook a before handle to it.
   123         """
   124         before_handle_user_exception.send(e)
```

---->  125         return super(Flask, self).handle_user_exception(e)
       126
       127
##        128 def lazy_import(name):

```
                    self =  "<Flask 'invenio.base'>"
                       e =  'TypeError("\'NotImplementedType\' object is not callable",)'
```
## Frame error_router in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/**init**.py at line 258

```
   255         """
   256         if self._has_fr_route():
   257             return self.handle_error(e)
```

---->  258         return original_handler(e)
       259
       260     def handle_error(self, e):
##        261         """Error handler for the API transforms a raised exception into a Flask

```
        original_handler =  "<bound method Flask.handle_user_exception of <Flask 'invenio.base'>>"
                    self =  '<flask_restful.Api object at 0x7f2a1e7138d0>'
                       e =  'TypeError("\'NotImplementedType\' object is not callable",)'
```
## Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477

```
  1474             if rv is None:
  1475                 rv = self.dispatch_request()
  1476         except Exception as e:
```

----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
##       1480         request_finished.send(self, response=response)

```
                      rv =  'None'
                       e =  'TypeError("\'NotImplementedType\' object is not callable",)'
                    self =  "<Flask 'invenio.base'>"
```
## Frame **call** in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/**init**.py at line 63

```
    60                     response = self.app.full_dispatch_request()
    61                 except Exception as e:
    62                     from invenio.ext.logging import register_exception
```

---->   63                     register_exception(req=request, alert_admin=True)
        64                     response = self.app.handle_exception(e)
        65
##         66                 return response(environ, start_response)

```
          start_response =  '<built-in method start_response of mod_wsgi.Adapter object at 0x7f29fb5b9738>'
                 environ =  "{'wsgi.version': (1, 0), 'mod_wsgi.listener_port': '443', 'HTTP_COOKIE': '__utma=178960688.650288074.1400159653.1409575485.1412233878.4; __utmz=178960688.1412233878.4.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); SESSc97447604b4420b34c9fb22dbb64bf36=5t54bfblqqlhshfe56er9fp9ae55lcm4; __utmb=178960688.29.9.1412236224450; __utmc=178960688; session=f2158303001145e29cdbaed758aa9d5c; sessionstub=HTTPS', 'mod_wsgi.listener_host': '', 'SERVER_SOFTWARE': 'Apache', 'SCRIPT_NAME [...]
                    self =  '<invenio.ext.legacy.LegacyAppMiddleware object at 0x7f2a1e15bdd0>'
      register_exception =  '<function register_exception at 0x7f2a1e5f9488>'
                       e =  'TypeError("\'NotImplementedType\' object is not callable",)'
```

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
