### ISSUE TITLE
persistence error from prod system

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#441]
Hello:

This exception has already been seen 1 times
    last time it was seen: 2014-10-02 10:54:59
    last time it was notified: 2014-10-02 10:54:59
- 2014-10-02 10:54:59 -> FlushError: New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class 'invenio.modules.accounts.models.UserUsergroup'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0> (persistence.py:170:_organize_states_for_save)

*\* User details
                                     agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0
                        dashboard_settings: {'orderRight': u'WebTagSettings', 'orderLeft': [u'WebAlertSettings', u'WebMessageSettings'], 'orderMiddle': [u'WebAccountSettings', u'WebSearchSettings', u'WebBasketSettings']}
                                     email: r.pool@vu.nl
                                     group: [u'VUBioPsy']
                                     guest: 0
                                        id: 137
                              login_method: Local
                                  nickname: rinipool
                                      note: 1
            precached_canseehiddenmarctags: False
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: False
                       precached_usealerts: True
                      precached_useapprove: False
                      precached_usebaskets: True
                       precached_usegroups: True
                        precached_useloans: True
                     precached_usemessages: True
             precached_usepaperattribution: True
                   precached_usepaperclaim: True
                        precached_usestats: False
                   precached_usesuperadmin: False
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: https://b2share.eudat.eu/yourgroups/index
                               remote_host:
                                 remote_ip: 145.108.164.6
                                   session: None
                                  settings: {'login_method': 'Local', 'dashboard_settings': {'orderRight': u'WebTagSettings', 'orderLeft': [u'WebAlertSettings', u'WebMessageSettings'], 'orderMiddle': [u'WebAccountSettings', u'WebSearchSettings', u'WebBasketSettings']}}
                                       uid: 137
                                       uri: </yourgroups/join>

*\* Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/**init**.py", line 60, in **call**
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/**init**.py", line 258, in error_router
    return original_handler(e)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py", line 658, in decorated_view
    return func(_args, *_kwargs)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py", line 203, in decorator
    return f(_args, *_argd)
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/modules/groups/views.py", line 115, in join
    db.session.merge(group)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
    return getattr(self.registry(), name)(_args, *_kwargs)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1510, in merge
    self._autoflush()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1139, in _autoflush
    self.flush()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1818, in flush
    self._flush(objects)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1936, in _flush
    transaction.rollback(_capture_exception=True)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 58, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1900, in _flush
    flush_context.execute()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 525, in execute
    uow
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 45, in save_obj
    uowtransaction)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 170, in _organize_states_for_save
    state_str(existing)))
FlushError: New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class 'invenio.modules.accounts.models.UserUsergroup'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>

*\* Stack frame details
## Frame _organize_states_for_save in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py at line 170

```
   167                     "New instance %s with identity key %s conflicts "
   168                     "with persistent instance %s" %
   169                     (state_str(state), instance_key,
```

---->  170                      state_str(existing)))
       171
       172             base_mapper._log_debug(
##        173                 "detected row switch for identity %s.  "

```
                  mapper =  '<Mapper at 0x7f2a1e502510; UserUsergroup>'
        states_to_update =  '[]'
            has_identity =  'False'
                   dict_ =  "{'user_status': 'P', '_sa_instance_state': <sqlalchemy.orm.state.InstanceState object at 0x7f29fb708210>, 'id_user': 137L, 'id_usergroup': 1L, 'usergroup': <invenio.modules.accounts.models.Usergroup object at 0x7f29fb708610>}"
                   state =  '<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708210>'
             base_mapper =  '<Mapper at 0x7f2a1e502510; UserUsergroup>'
                existing =  '<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708c90>'
                  states =  '<generator object states_for_mapper_hierarchy at 0x7f29fb46aa00>'
                instance =  '<invenio.modules.accounts.models.UserUsergroup object at 0x7f29fb7085d0>'
              connection =  '<sqlalchemy.engine.base.Connection object at 0x7f29fb7088d0>'
            instance_key =  "(<class 'invenio.modules.accounts.models.UserUsergroup'>, (137L, 1L))"
          uowtransaction =  '<sqlalchemy.orm.unitofwork.UOWTransaction object at 0x7f29fb708790>'
        states_to_insert =  '[]'
              row_switch =  'None'
```
## Frame save_obj in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py at line 45

```
    42     states_to_insert, states_to_update = _organize_states_for_save(
    43                                                 base_mapper,
    44                                                 states,
```

---->   45                                                 uowtransaction)
        46
        47     cached_connections = _cached_connection_dict(base_mapper)
##         48

```
                  states =  '<generator object states_for_mapper_hierarchy at 0x7f29fb46aa00>'
                  single =  'False'
             base_mapper =  '<Mapper at 0x7f2a1e502510; UserUsergroup>'
          uowtransaction =  '<sqlalchemy.orm.unitofwork.UOWTransaction object at 0x7f29fb708790>'
```
## Frame execute in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py at line 525

```
   522     def execute(self, uow):
   523         persistence.save_obj(self.mapper,
   524             uow.states_for_mapper_hierarchy(self.mapper, False, False),
```

---->  525             uow
       526         )
       527
##        528     def per_state_flush_actions(self, uow):

```
                    self =  'SaveUpdateAll(Mapper|UserUsergroup|user_usergroup)'
                     uow =  '<sqlalchemy.orm.unitofwork.UOWTransaction object at 0x7f29fb708790>'
```
## Frame execute in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py at line 372

```
   369             for rec in topological.sort(
   370                                     self.dependencies,
   371                                     postsort_actions):
```

---->  372                 rec.execute(self)
       373
       374     def finalize_flush_changes(self):
##        375         """mark processed objects as clean / deleted after a successful

```
                     rec =  'SaveUpdateAll(Mapper|UserUsergroup|user_usergroup)'
                    self =  '<sqlalchemy.orm.unitofwork.UOWTransaction object at 0x7f29fb708790>'
        postsort_actions =  'set([DeleteAll(Mapper|UserUsergroup|user_usergroup), ProcessAll(ManyToOneDP(UserUsergroup.usergroup), delete=True), DeleteAll(Mapper|Usergroup|usergroup), ProcessAll(OneToManyDP(Usergroup.users), delete=True), ProcessAll(OneToManyDP(Usergroup.users), delete=False), SaveUpdateAll(Mapper|UserUsergroup|user_usergroup), SaveUpdateAll(Mapper|Usergroup|usergroup), ProcessAll(ManyToOneDP(UserUsergroup.usergroup), delete=False)])'
```
## Frame _flush in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py at line 1936

```
  1933
  1934         except:
  1935             with util.safe_reraise():
```

----> 1936                 transaction.rollback(_capture_exception=True)
      1937
      1938     def is_modified(self, instance, include_collections=True,
##       1939                             passive=True):

```
               is_orphan =  'False'
             transaction =  '<sqlalchemy.orm.session.SessionTransaction object at 0x7f29fb708910>'
                 deleted =  'set([])'
                    self =  '<flask_sqlalchemy.SignallingSession object at 0x7f29fb47b210>'
           flush_context =  '<sqlalchemy.orm.unitofwork.UOWTransaction object at 0x7f29fb708790>'
                   state =  '<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708c50>'
                 objects =  'None'
               processed =  'set([<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708210>, <sqlalchemy.orm.state.InstanceState object at 0x7f29fb708c50>])'
                  objset =  'None'
                     new =  'set([<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708210>])'
                    proc =  'set([])'
                   dirty =  'set([<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708c50>])'
```
## Frame **exit** in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py at line 58

```
    55         if type_ is None:
    56             exc_type, exc_value, exc_tb = self._exc_info
    57             self._exc_info = None   # remove potential circular references
```

---->   58             compat.reraise(exc_type, exc_value, exc_tb)
        59         else:
        60             self._exc_info = None   # remove potential circular references
##         61             compat.reraise(type_, value, traceback)

```
                    self =  '<sqlalchemy.util.langhelpers.safe_reraise object at 0x7f29fb7084d0>'
               traceback =  'None'
               exc_value =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
                   value =  'None'
                  exc_tb =  '<traceback object at 0x7f29fb684cf8>'
                   type_ =  'None'
                exc_type =  "<class 'sqlalchemy.orm.exc.FlushError'>"
```
## Frame _flush in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py at line 1936

```
  1933
  1934         except:
  1935             with util.safe_reraise():
```

----> 1936                 transaction.rollback(_capture_exception=True)
      1937
      1938     def is_modified(self, instance, include_collections=True,
##       1939                             passive=True):

```
               is_orphan =  'False'
             transaction =  '<sqlalchemy.orm.session.SessionTransaction object at 0x7f29fb708910>'
                 deleted =  'set([])'
                    self =  '<flask_sqlalchemy.SignallingSession object at 0x7f29fb47b210>'
           flush_context =  '<sqlalchemy.orm.unitofwork.UOWTransaction object at 0x7f29fb708790>'
                   state =  '<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708c50>'
                 objects =  'None'
               processed =  'set([<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708210>, <sqlalchemy.orm.state.InstanceState object at 0x7f29fb708c50>])'
                  objset =  'None'
                     new =  'set([<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708210>])'
                    proc =  'set([])'
                   dirty =  'set([<sqlalchemy.orm.state.InstanceState object at 0x7f29fb708c50>])'
```
## Frame flush in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py at line 1820

```
  1817             self._flushing = True
  1818             self._flush(objects)
  1819         finally:
```

----> 1820             self._flushing = False
      1821
      1822     def _flush_warning(self, method):
##       1823         util.warn(

```
                    self =  '<flask_sqlalchemy.SignallingSession object at 0x7f29fb47b210>'
                 objects =  'None'
```
## Frame _autoflush in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py at line 1139

```
  1136
  1137     def _autoflush(self):
  1138         if self.autoflush and not self._flushing:
```

----> 1139             self.flush()
      1140
      1141     def refresh(self, instance, attribute_names=None, lockmode=None):
##       1142         """Expire and refresh the attributes on the given instance.

```
                    self =  '<flask_sqlalchemy.SignallingSession object at 0x7f29fb47b210>'
```
## Frame merge in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/session.py at line 1510

```
  1507
  1508         if load:
  1509             # flush current contents if we expect to load data
```

----> 1510             self._autoflush()
      1511
      1512         object_mapper(instance)  # verify mapped
##       1513         autoflush = self.autoflush

```
                    load =  'True'
                instance =  '<invenio.modules.accounts.models.Usergroup object at 0x7f29fb708610>'
                    self =  '<flask_sqlalchemy.SignallingSession object at 0x7f29fb47b210>'
              _recursive =  '{}'
```
## Frame do in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py at line 149

```
   146
   147 def instrument(name):
   148     def do(self, *args, **kwargs):
```

---->  149         return getattr(self.registry(), name)(_args, *_kwargs)
       150     return do
       151
##        152 for meth in Session.public_methods:

```
                    self =  '<sqlalchemy.orm.scoping.scoped_session object at 0x7f2a1dca6290>'
                    args =  '(<invenio.modules.accounts.models.Usergroup object at 0x7f29fb708610>,)'
                    name =  "'merge'"
                  kwargs =  '{}'
```
## Frame join in /var/www/.virtualenvs/b2share/src/b2share/invenio/modules/groups/views.py at line 115

```
   112     if group is None:
   113         return abort(400)
   114     group.join()
```

---->  115     db.session.merge(group)
       116     db.session.commit()
       117     current_user.reload()
##        118     flash(_('You join a group %(name)s.', name=group.name), 'success')

```
                  status =  'None'
            id_usergroup =  '1'
                   group =  '<invenio.modules.accounts.models.Usergroup object at 0x7f29fb708610>'
```
## Frame decorator in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/decorators.py at line 203

```
   200             from invenio.utils.washers import wash_urlargd
   201             argd = wash_urlargd(request.values, config)
   202             argd.update(kwargs)
```

---->  203             return f(_args, *_argd)
       204         return decorator
##        205     return _decorated

```
                       f =  '<function join at 0x7f2a1fac6578>'
                    argd =  "{'id_usergroup': 1}"
                    args =  '()'
                  kwargs =  '{}'
            wash_urlargd =  '<function wash_urlargd at 0x7f29fa1e4c80>'
                  config =  "{'id_usergroup': (<type 'int'>, 0)}"
```
## Frame decorated_view in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_login.py at line 658

```
   655             return func(*args, **kwargs)
   656         elif not current_user.is_authenticated():
   657             return current_app.login_manager.unauthorized()
```

---->  658         return func(_args, *_kwargs)
       659     return decorated_view
       660
##        661

```
                    args =  '()'
                    func =  '<function join at 0x7f2a1fac65f0>'
                  kwargs =  '{}'
```
## Frame dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1461

```
  1458            and req.method == 'OPTIONS':
  1459             return self.make_default_options_response()
  1460         # otherwise dispatch to the handler for that endpoint
```

----> 1461         return self.view_functions[rule.endpoint](**req.view_args)
      1462
      1463     def full_dispatch_request(self):
##       1464         """Dispatches the request and on top of that performs request

```
                    self =  "<Flask 'invenio.base'>"
                     req =  "<LegacyRequest 'https://b2share.eudat.eu/yourgroups/join' [POST]>"
                    rule =  "<Rule '/yourgroups/join' (HEAD, POST, OPTIONS, GET) -> webgroup.join>"
```
## Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477

```
  1474             if rv is None:
  1475                 rv = self.dispatch_request()
  1476         except Exception as e:
```

----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
##       1480         request_finished.send(self, response=response)

```
                      rv =  'None'
                       e =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
                    self =  "<Flask 'invenio.base'>"
```
## Frame handle_user_exception in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1381

```
  1378             if isinstance(e, typecheck):
  1379                 return handler(e)
  1380
```

----> 1381         reraise(exc_type, exc_value, tb)
      1382
      1383     def handle_exception(self, e):
##       1384         """Default exception handling that kicks in when an exception

```
                       e =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
                handlers =  'None'
                    self =  "<Flask 'invenio.base'>"
               exc_value =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
      blueprint_handlers =  '()'
            app_handlers =  '()'
                      tb =  '<traceback object at 0x7f29fb66f248>'
                exc_type =  "<class 'sqlalchemy.orm.exc.FlushError'>"
```
## Frame handle_user_exception in /var/www/.virtualenvs/b2share/src/b2share/invenio/base/wrappers.py at line 125

```
   122         Hook a before handle to it.
   123         """
   124         before_handle_user_exception.send(e)
```

---->  125         return super(Flask, self).handle_user_exception(e)
       126
       127
##        128 def lazy_import(name):

```
                    self =  "<Flask 'invenio.base'>"
                       e =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
```
## Frame error_router in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask_restful/**init**.py at line 258

```
   255         """
   256         if self._has_fr_route():
   257             return self.handle_error(e)
```

---->  258         return original_handler(e)
       259
       260     def handle_error(self, e):
##        261         """Error handler for the API transforms a raised exception into a Flask

```
        original_handler =  "<bound method Flask.handle_user_exception of <Flask 'invenio.base'>>"
                    self =  '<flask_restful.Api object at 0x7f2a1e7138d0>'
                       e =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
```
## Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1477

```
  1474             if rv is None:
  1475                 rv = self.dispatch_request()
  1476         except Exception as e:
```

----> 1477             rv = self.handle_user_exception(e)
      1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
##       1480         request_finished.send(self, response=response)

```
                      rv =  'None'
                       e =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
                    self =  "<Flask 'invenio.base'>"
```
## Frame **call** in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/**init**.py at line 63

```
    60                     response = self.app.full_dispatch_request()
    61                 except Exception as e:
    62                     from invenio.ext.logging import register_exception
```

---->   63                     register_exception(req=request, alert_admin=True)
        64                     response = self.app.handle_exception(e)
        65
##         66                 return response(environ, start_response)

```
          start_response =  '<built-in method start_response of mod_wsgi.Adapter object at 0x7f29fa166a08>'
                 environ =  "{'wsgi.version': (1, 0), 'mod_wsgi.listener_port': '443', 'HTTP_COOKIE': '__utma=178960688.650288074.1400159653.1409575485.1412233878.4; __utmz=178960688.1412233878.4.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); SESSc97447604b4420b34c9fb22dbb64bf36=5t54bfblqqlhshfe56er9fp9ae55lcm4; __utmb=178960688.29.9.1412236224450; __utmc=178960688; session=f2158303001145e29cdbaed758aa9d5c; sessionstub=HTTPS', 'mod_wsgi.listener_host': '', 'SERVER_SOFTWARE': 'Apache', 'SCRIPT_NAME [...]
                    self =  '<invenio.ext.legacy.LegacyAppMiddleware object at 0x7f2a1e15bdd0>'
      register_exception =  '<function register_exception at 0x7f2a1e5f9488>'
                       e =  'FlushError("New instance <UserUsergroup at 0x7f29fb71cf10> with identity key (<class \'invenio.modules.accounts.models.UserUsergroup\'>, (137L, 1L)) conflicts with persistent instance <UserUsergroup at 0x7f29fb7085d0>",)'
```

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
