### ISSUE TITLE
Download button to the right of search result item does not initiate download.

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#455]
Clicking the download button doesn't help you to download the item:
![screenshot from 2014-10-16 16 46 07](https://cloud.githubusercontent.com/assets/6217533/4664394/affaa18a-5543-11e4-910a-278086faecc0.png)

**Comment by cjhak** [comment]
Still an issue in B2SHARE 1.4.

**Comment by dblommesteijn** [comment]
@cjhak I think it's good to move non critical issues to b2share 2.0!

**Comment by cjhak** [comment]
@dblommesteijn I agree, in particular for UI-bugs (while e.g. Invenio-related bugs might better be fixed as we go along).

**Comment by tiborsimko** [comment]
FWIW the drop-down menu works well for some records such:

- https://b2share.eudat.eu/search?p=recid:10

Might be worth to check templates. CC @nharraud

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
