### ISSUE TITLE
Fix language code values in production db

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2SHARE/b2share#457]
Fix imaginative values set for Linguistics ```language_code``` metadata field in production database, before controlled vocabulary was enabled in #110.

**Comment by noumar** [comment]
@llehtine I'm donating this to you. It's easier that way.

**Comment by noumar** [comment]
I sent @llehtine a script to try and fix the cached values.

**Comment by cjhak** [comment]
Moving to B2SHARE 2.0 to be followed up there.

**Comment by llehtine** [comment]
The script was run in production I think in spring. The issue was just forgot to be closed. Closing it now.
