### ISSUE TITLE
AAI: Unity authentication for B2SHARE

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#474]
Proposed tasks for solving this issue:
- [x] Use Zenodo code to use github as IdP, as baseline for testing
- [x] Change from github to Unity

**Comment by cjhak** [comment]
@dblommesteijn Assigning this issue too to you as a part of the AAI investigations.

**Comment by emanueldima** [comment]
After merging with invenio 2.0, the next branch, GitHub login is trivial to configure and use. See the last commit in this branch: https://github.com/emanueldima/b2share/tree/master%23merge-invenio-next---github-oauth-config-example (but, of course, a different installation would need different GitHub settings). 

Good and up-to-date documentation on the configuration is available here: http://invenio.readthedocs.org/en/latest/modules/oauthclient.html

**Comment by emanueldima** [comment]
Should be solved by #600

**Comment by lnielsen** [comment]
> Good and up-to-date documentation on the configuration is available here: http://invenio.readthedocs.org/en/latest/modules/oauthclient.html

@emanueldima Let me know if there's something that can be improved in this part of the documentation :-)

**Comment by emanueldima** [comment]
Fixed by switching to invenio2 and https://github.com/EUDAT-B2SHARE/b2share/pull/621
