### ISSUE TITLE
Issue with deploying of B2SHARE without the vagrant install

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#475]
I tried to install and deploy B2SHARE (without Vagrant) on a centos6.5 machine without any success.
I followed the following steps:

### Installing B2Share in a VM (without vagrant)

- System: CentOS 6.5 64bit
- Login as root
- install wget, vim and git
	yum install wget vim git
- create user b2admin
	useradd b2admin
- add b2admin to sudoers
	vim /etc/sudoers
   add
	b2admin ALL=(ALL)       ALL
- add ports to iptables:
	vim /etc/sysconfig/iptables    insert 	-A INPUT -p tcp -m state --state NEW -m tcp --dport 4000 -j ACCEPT  	-A INPUT -p tcp -m state --state NEW -m tcp --dport 4443 -j ACCEPT
  before line 
	-A INPUT -j REJECT --reject-with icmp-host-prohibited
- Clone repository as b2admin in /home/b2admin  
	git clone -b master https://github.com/EUDAT-B2SHARE/b2share.git

- In b2share/install/provision_system.sh and b2share/install/install_b2share.sh change
	USER=vagrant
  to
	USER=b2admin

- Become root
	su

- Execute in b2share/install/
	./provision_system.sh

- Change back to b2admin
- Go to /home/b2admin
- Execute
	./b2share/install/install_b2share.sh

- Execute either
	workon b2share
   or
	source .virtualenvs/b2share/bin/activate

- screen -S b2share
- cd /home/b2admin/.virtualenvs/b2share/src/b2share/install/
- ./ start_b2share.sh results in

(b2share)[b2admin@cloudvm install]$ ./start_b2share.sh 

### Error messages
At first the WORKON_HOME was empty for root. So I fixed this. 
Then the following occurred:

[sudo] password for b2admin:
./start_b2share.sh: line 16: 27114 Illegal instruction     $WORKON_HOME/b2share/bin/bibsched restart
nohup: appending output to `nohup.out'
./start_b2share.sh: line 23: 27122 Illegal instruction     nohup celeryd -E -A invenio.celery.celery --workdir=$VIRTUAL_ENV
./start_b2share.sh: line 26: 27128 Illegal instruction     $WORKON_HOME/b2share/bin/inveniomanage collect
./start_b2share.sh: line 29: 27134 Illegal instruction     $WORKON_HOME/b2share/bin/inveniomanage runserver -d -r

## Executing bibsched in python 
Python 2.7.6 (default, Nov  3 2014, 15:54:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> __requires__ = 'Invenio==1.9999'
>>> import sys
>>> from pkg_resources import load_entry_point
>>> load_entry_point('Invenio==1.9999', 'console_scripts', 'bibsched')()
Illegal instruction

Do you have any suggestion what I did wrong or how to fix this?

Many thanks for your help in advance.

**Comment by emanueldima** [comment]
This issue is outdated and refers to an old b2share version, so I'm closing it.
