### ISSUE TITLE
Automatic tests for the REST API

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#480]

**Comment by dblommesteijn** [comment]
Current RestAPI test-coverage:
![image](https://cloud.githubusercontent.com/assets/395001/6146213/92c514fc-b1ea-11e4-9884-ce2f065408c2.png)

**Comment by dblommesteijn** [comment]
So someone should fix: #563, #559

**Comment by emanueldima** [comment]
Blocked?

**Comment by dblommesteijn** [comment]
Haven't tracked #563 and #559, they are solved so this is no longer blocked.

**Comment by emanueldima** [comment]
Close?

**Comment by nharraud** [comment]
I would say so, current REST API is tested and we are creating tests when adding new endpoints :)

**Comment by cjhak** [comment]
Good point. The new REST API is actually an excellent point for finally start applying the test driven approach we have had in mind for so long.
