### ISSUE TITLE
Bibreformat errors when uploading duplicate files

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#490]
I've made two deposits (in the dev environment) with twice the same file. Bibreformat (in bibsched) errors:
![screen shot 2014-12-05 at 17 52 41](https://cloud.githubusercontent.com/assets/395001/5319234/b1ce3950-7ca7-11e4-866f-bcd6b2bdad2b.png)

Resulting in no more records added to the deposit list (homepage):
![screen shot 2014-12-05 at 17 54 31](https://cloud.githubusercontent.com/assets/395001/5319254/c8e5c8b0-7ca7-11e4-95b7-7c9b9d5e33e4.png)

PS. I've reinstalled B2SHARE to make sure I didn't introduce the error on my local machine.

**Comment by cjhak** [comment]
@dblommesteijn Is this still an issue?

**Comment by dblommesteijn** [comment]
Yes, but cannot reproduce. We can close it for now.
