### ISSUE TITLE
User is not informed when another user attempts to download protected data

### ISSUE THREAD

**Issue by huwmorris** [EUDAT-B2SHARE/b2share#507]
User 1 uploads data with "Open Access" set to off. User 2 attempts to download this data. User 2 is correctly sent to a page where he can send a message to User 1 to request access to the data. User 1 never receives that message, either through email or internal messages.

**Comment by emanueldima** [comment]
We must check this issue in v2

**Comment by emanueldima** [comment]
this was a v1 issue, not valid for v2
