### ISSUE TITLE
Files with non-ascii letters in file name can not be downloaded

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#523]
Examples:
https://test-eudatis.csc.fi/record/93
https://test-eudatis.csc.fi/record/218

Similar to old issue #169, for which the fix does not seem to have made it to the current version of B2SHARE. However, now we don't get "Internal server error" but "Requested file does not seem to exist".

**Comment by emanueldima** [comment]
Works on the new b2share+invenio2
