### ISSUE TITLE
ListMetadataFormats: metadata prefixes point to wrong schema 

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#536]
marcxml prefix points to oai_dc and vice versa on page https://b2share.eudat.eu/oai2d?verb=ListMetadataFormats (see also picture below)
![screen shot 2015-01-14 at 12 00 32 pm](https://cloud.githubusercontent.com/assets/8696302/5737759/1123e484-9be5-11e4-89e4-49def861c56c.png)

**Comment by noumar** [comment]
I will cherry-pick the commit.
