### ISSUE TITLE
Add new community/domain extension: RDA

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#540]

**Comment by cjhak** [comment]
Metadataset very similar to what we already have as "Generic". Dublin Core Metadata Element Set Version 1.1, plus a field for version and the other standard fields we use. The following list should be covered:

version
contributor (multiple)
coverage
creator (multiple)
date
description
format
identifier
language
publisher
relation
rights
source
subject
title
type

**Comment by cjhak** [comment]
Icon:
https://b2drop.eudat.eu/public.php?service=files&t=4b60a0c92dd263ec185ab4f81fb40d1b

**Comment by noumar** [comment]
RDA | Schema | EUDAT
--- | --- | ---
title | Generic | title
description | Generic | description
creator (multiple) | Generic | creator
rights | Generic | open_access + licence
subject | Generic | keywords
contributor (multiple) | Generic | contributors
type | Generic | resource Type
identifier | Generic | alternate_identifier
version | Generic | version
 | | 
publisher | Generic, hidden, static | publisher
language | Generic, hidden, static | language
 | Generic, hidden, static | publication_date
 | Generic, hidden, static | contact_email
 | | 
date | RDA | 
coverage | RDA | 
format | RDA | 
relation | RDA | 
source | RDA |

**Comment by dblommesteijn** [comment]
@noumar did you know domains are configured in the [`.travis.yml`](https://github.com/EUDAT-B2SHARE/b2share/blob/master/.travis.yml) file as well? There's currently no impact, just so you know.

**Comment by noumar** [comment]
No, I didn't know. But I can't find the line in `.travis.yml` either. Can you give the line number?

**Comment by dblommesteijn** [comment]
It's actually still in my pull-request: https://github.com/EUDAT-B2SHARE/b2share/pull/489/files#diff-354f30a63fb0907d4ad57269548329e3R65
