### ISSUE TITLE
"Discipline" field in the generic schema

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#541]
The following request is from the B2FIND team:

"Within b2find we are using the facet discipline. Only a closed list of
entries are possible here, as defined in
http://en.wikipedia.org/wiki/Outline_of_academic_disciplines
Is it possible to have such a field (with the same list) within the generic
metadata scheme of b2find? (it should be possible to select 0, 1 or more out of
those in the list).
A subset of those disciplines is also available in git within
https://github.com/B2FIND/md-mapping/blob/master/mapfiles/b2find_disciplines.tab"

**Comment by noumar** [comment]
@hwidmann this should be possible to do. I will try to add it.

**Comment by noumar** [comment]
@cjhak should `discipline` be a basic or extra fields, i.e. directly visible or after clicking `Add more details?`?

**Comment by cjhak** [comment]
@noumar basic / directly visible, unless there is any particular problem with that.
