### ISSUE TITLE
RestAPI URI naming convention

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#545]
According to [the wiki](https://github.com/EUDAT-B2SHARE/b2share/wiki/REST-API) we use the following URI's:
* `/api/record(s)/`
* `/api/deposition(s)/`

Is there a reason for mixing two names for basically the same objects?
@emanueldima @SarahBA I'd rather use one name instead of two.

**Comment by emanueldima** [comment]
Depositions are uncommitted records. They have no metadata, just some files. It's more of a practical distinction, easier to make the depositing this way.

**Comment by dblommesteijn** [comment]
Ok, so uncommitted is a state to records?

**Comment by emanueldima** [comment]
More than that. From a single deposition many records can be created. A deposition ID is a random uuid, but a recordID points to something in the database. If you get a recordID you know that the object is there and accessible (at least the metadata). They are different types of objects.

**Comment by emanueldima** [comment]
We've decided to merge depositions and records in b2share2, and introduce a record_status field [draft, submitted for review, released, deleted]
