### ISSUE TITLE
RestAPI create deposition without committing

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#548]
What happens to a record after it's created via: `POST /api/depositions/?access_token=xyz`, and is never committed? @emanueldima are these cleaned up?

Moreover, do we need a `DELETE` action?

**Comment by emanueldima** [comment]
A deposition is just a temporary folder in the upload directory, is subject to the same gc procedure as the one implemented for the user interface in this pr: https://github.com/EUDAT-B2SHARE/b2share/pull/251
