### ISSUE TITLE
RestAPI depositing multiple files at once

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#549]
Uploading multiple files in a single post will not work.

~~Is uploading multiple files at once tested? I could only manage to upload single files via:~~
~~`POST /api/deposition/123/files?access_token=xyz`.~~

~~@emanueldima have you tried it?~~

**Comment by emanueldima** [comment]
I didn't try, indeed, it's very possible that it won't work. The user can do multiple posts, however.

**Comment by dblommesteijn** [comment]
Good to know! I'll make a note of it. For future use we should have a multi-file upload or even streaming upload I think: http://docs.python-requests.org/en/latest/user/advanced/#streaming-uploads

**Comment by emanueldima** [comment]
Pointer: http://stackoverflow.com/questions/11817182/uploading-multiple-files-with-flask

**Comment by hevp** [comment]
This is no longer a requirement. To upload multiple files, use multiple requests. Streamed uploading is supported through request headers and tools used.
