### ISSUE TITLE
Creating new deposit will give error-message to log-file

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#553]
Hello:

This exception has already been seen 1 times
    last time it was seen: 2015-02-02 14:57:33
    last time it was notified: 2015-02-02 14:57:33

* 2015-02-02 14:57:33 -> ValueError: View function did not return a response (app.py:1566:make_response)

** User details
                                     agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0
                        dashboard_settings: {'orderMiddle': [u'WebSearchSettings', u'WebBasketSettings', u'WebGroupSettings'], 'orderLeft': [u'WebAlertSettings', u'WebMessageSettings', u'WebAccountSettings'], 'orderRight': u'WebTagSettings'}
                                     email: eudat-support@csc.fi
                                     group: []
                                     guest: 0
                                        id: 1
                              login_method: Local
                                  nickname: admin
                                      note: 1
            precached_canseehiddenmarctags: True
precached_permitted_restricted_collections: []
                    precached_sendcomments: False
                        precached_useadmin: True
                       precached_usealerts: True
                      precached_useapprove: True
                      precached_usebaskets: True
                       precached_usegroups: True
                        precached_useloans: True
                     precached_usemessages: True
             precached_usepaperattribution: True
                   precached_usepaperclaim: True
                        precached_usestats: True
                   precached_usesuperadmin: True
                   precached_viewclaimlink: False
                 precached_viewsubmissions: False
                                   referer: <https://b2share.eudat.eu/b2deposit>
                               remote_host:
                                 remote_ip: 193.166.1.75
                                   session: None
                                  settings: {'login_method': 'Local', 'dashboard_settings': {'orderMiddle': [u'WebSearchSettings', u'WebBasketSettings', u'WebGroupSettings'], 'orderLeft': [u'WebAlertSettings', u'WebMessageSettings', u'WebAccountSettings'], 'orderRight': u'WebTagSettings'}}
                                       uid: 1
                                       uri: </b2deposit/upload/099fe5d2aadb11e4b826005056943408>

** Traceback details

Traceback (most recent call last):
  File "/var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py", line 60, in __call__
    response = self.app.full_dispatch_request()
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response

** Stack frame details

Frame make_response in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1566
-------------------------------------------------------------------------------
      1563             rv, status, headers = rv + (None,) * (3 - len(rv))
      1564
      1565         if rv is None:
----> 1566             raise ValueError('View function did not return a response')
      1567
      1568         if not isinstance(rv, self.response_class):
      1569             # When we create a response object directly, we let the constructor
-------------------------------------------------------------------------------
                      status =  'None'
                     headers =  'None'
                          rv =  'None'
                        self =  "<Flask 'invenio.base'>"

Frame full_dispatch_request in /var/www/.virtualenvs/b2share/lib/python2.7/site-packages/flask/app.py at line 1478
-------------------------------------------------------------------------------
      1475                 rv = self.dispatch_request()
      1476         except Exception as e:
      1477             rv = self.handle_user_exception(e)
----> 1478         response = self.make_response(rv)
      1479         response = self.process_response(response)
      1480         request_finished.send(self, response=response)
      1481         return response
-------------------------------------------------------------------------------
                          rv =  'None'
                        self =  "<Flask 'invenio.base'>"

Frame __call__ in /var/www/.virtualenvs/b2share/src/b2share/invenio/ext/legacy/__init__.py at line 63
-------------------------------------------------------------------------------
        60                     response = self.app.full_dispatch_request()
        61                 except Exception as e:
        62                     from invenio.ext.logging import register_exception
---->   63                     register_exception(req=request, alert_admin=True)
        64                     response = self.app.handle_exception(e)
        65
        66                 return response(environ, start_response)
-------------------------------------------------------------------------------
              start_response =  '<built-in method start_response of mod_wsgi.Adapter object at 0x7f56a99cf288>'
                     environ =  "{'wsgi.version': (1, 0), 'mod_wsgi.listener_port': '443', 'HTTP_REFERER': 'https://b2share.eudat.eu/b2deposit', 'mod_wsgi.listener_host': '', 'SERVER_SOFTWARE': 'Apache', 'SCRIPT_NAME': '', 'mod_wsgi.enable_sendfile': '0', 'mod_wsgi.handler_script': '', 'SERVER_SIGNATURE': '', 'REQUEST_METHOD': 'POST', 'PATH_INFO': '/b2deposit/upload/099fe5d2aadb11e4b826005056943408', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'SSL_TLS_SNI': 'b2share.eudat.eu', 'CONTENT_LENGTH': '565', 'HTTP_USER_AGENT' [...]
                        self =  '<invenio.ext.legacy.LegacyAppMiddleware object at 0x7f56a3ba9dd0>'
          register_exception =  '<function register_exception at 0x7f56a4041f50>'
                           e =  "ValueError('View function did not return a response',)"

**Comment by emanueldima** [comment]
This bug has already been solved by pr https://github.com/EUDAT-B2SHARE/b2share/pull/550.

**Comment by llehtine** [comment]
Oki, that was then missing from master
