### ISSUE TITLE
OAI identifiers are not custom/unique

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2SHARE/b2share#556]
The ```oai-identifiers``` generated are still basic Invenio's, e.g. ```oai:atlantis.cern.ch:123```. Our own unique identifiers should be used.

**Comment by cjhak** [comment]
Still an issue, re-opening.

**Comment by cjhak** [comment]
@llehtine Perhaps still an issue with config settings mentioned in  #585?

**Comment by llehtine** [comment]
i've changed the config-values, but they are only applicable to new entries. should i go and try to change all the old entries manually?

**Comment by llehtine** [comment]
this entry for example has the correct one: https://b2share.eudat.eu/oai2d/?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:b2share.eudat.eu:197

**Comment by cjhak** [comment]
@llehtine Thanks. Yes, we should update old values soon. Let's discuss in the developer's meeting today.

**Comment by noumar** [comment]
I recall these changing for me when the config variable was changed. @llehtine have you run `oairepositoryupdater` after the change? You should! See https://github.com/EUDAT-B2SHARE/b2share/blob/master/invenio/legacy/oairepository/updater.py#L20-L26.

**Comment by llehtine** [comment]
Hi oairepositoryupdater is ran automatically from bibsched, so it has been ran after the update

**Comment by cjhak** [comment]
Will hopefully be fixed by #628. Keeping it open for now and assigning to myself to follow up.

**Comment by cjhak** [comment]
Verified that this works for new deposits on production site. Clean up of old data still needed and will be taken care of in #628. Closing this issue again.
