### ISSUE TITLE
RestAPI naming convention JSON payload

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#558]
The RestAPI's naming convention for `GET /record/:id` [response-fields](https://github.com/EUDAT-B2SHARE/b2share/wiki/REST-API#response-fields) returns `recordID` (lower camelcase); whereas the other fields `open_access`, and `contact_email` use underscores to separate names. It seems wrong, why is this? Should we change it?

**Comment by emanueldima** [comment]
The recordID is added manually and can be easily changed. The other field names are encoded in the database (marc fields 690__a) and more difficult to rename or map.

**Comment by dblommesteijn** [comment]
I'm in favour of one single format, instead of two.
