### ISSUE TITLE
RestAPI record incorrect url prefix in JSON

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#563]
RestAPI call `GET /api/records/:id` returns a JSON with a nested `url` index in `files`, below. URL is prefixed with `http://0.0.0.0:4443/`, which is unusable from outside of the server.

```json
[{"files": [{"url": "http://0.0.0.0:4443/record/1/files/testfile1.ksh?version=1", "name": "testfile1.ksh", "size": 11}], "domain": "generic", "description": "Test file 1 via RestAPI description.", "contributors": [], "creator": [], "recordID": 1, "contact_email": "", "licence": "", "keywords": [], "publication_date": "", "open_access": "open", "title": "Test File 1 via RestAPI", "version": "", "alternate_identifier": "", "resource_type": []}]
```

**Comment by dblommesteijn** [comment]
I know we set `CFG_SITE_URL` in `b2share/install/install_b2share.sh` but I when hosting `http://localhost:4000` in the VM I cannot get a connection to the outside.

**Comment by emanueldima** [comment]
The installation setting used to create files urls is CFG_SITE_SECURE_URL. I think this is the problem, please check your installation.

**Comment by dblommesteijn** [comment]
`CFG_SITE_URL` and `CFG_SITE_SECURE_URL` are both set according to the `install_b2share.sh` script but this gives a problem because Invenio uses it as it's listen port, and if set to `127.0.0.1` or `localhost` foreign communication (like ssh tunnels) do not work. So I propose to use an alternate config setting.

**Comment by emanueldima** [comment]
Ok, I will add another optional parameter, let's call it CFG_FILE_SERVER_URL_PREFIX, is this ok?

**Comment by dblommesteijn** [comment]
@emanueldima that will do the trick!
