### ISSUE TITLE
Check against duplication of domain field names when invenio starts

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#566]
Adding new domains means adding new fields, and the more domains we add the more probable a clash becomes.

**Comment by noumar** [comment]
The problem I'm having is with ```generic``` and ```domain``` clashing, not between domains.

If you create a field in a domain that already exists within generic, e.g ```language```, you get a cryptic error: ```TypeError: Do not know how to convert multiple-column properties currently```.
This is completely useless and not helping to find the name of the field.

To my understanding the metadata fields are just key-value pairs stored separately for each record so they should not clash as one record can't belong to several domains.

**Comment by noumar** [comment]
@emanueldima have you had the problem that field names in two domains clash?

**Comment by emanueldima** [comment]
@noumar not yet; can you post the domain/field names that you are trying to add?

**Comment by noumar** [comment]
See #540 where RDA wants Dublin Core fields for their community. In practice this means 11 are already provided by ```Generic``` but 5 need to be ```RDA``` custom, unless we extend ```Generic```. This takes time to match up manually, but the comparing could well be done in ```model.py```. Currently ```model.py``` just adds ```Generic``` + ```Community``` fields together and "duplicate fields" somehow end up on top of each other and that causes the weird error.

**Comment by noumar** [comment]
@emanueldima I have added some checks to ```model.py``` that checks field names between Generic and Domain, and duplicates within Domain. I can push the changes today, but to this issue or a new one?

**Comment by emanueldima** [comment]
This one, but please don't close the issue as I might have some code for it later

**Comment by noumar** [comment]
@emanueldima please have a look at my suggestions when you can.
