### ISSUE TITLE
Feature request: Geospatial information in Generic schema

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2SHARE/b2share#584]
B2FIND requested that geospatial information would be available in the `Generic` schema/domain. Currently it's available in `NRM`. This could easily be moved under `Add more details?`.

@cjhak what do you think?

**Comment by emanueldima** [comment]
Not all datasets need a location. The basic set of fields is modeled after Dublin Core. If we add such a common field we won't be able to distinguish between records for which geophysical information has no applicability and records which should have but simply don't specify such a field.

**Comment by cjhak** [comment]
It would also be good to keep it visible for NRM. It will be important data for NRM and should be entered by citizen scientists, so we must make it as user-friendly as possible.

**Comment by noumar** [comment]
@emanueldima I agree, but Dublin Core has a `coverage` field that can represent this. See http://dublincore.org/documents/dces/. Yet we don't have/use it. This could be used.
@cjhak we can still leave separate fields for `NRM`. If this isn't confusing.

**Comment by cjhak** [comment]
@noumar Yes, using the DC `coverage` field and leaving the NRM fields as they are sounds like a better solution if that is sufficient for B2FIND.

**Comment by emanueldima** [comment]
What marc field will be used?
Will the nrm deposits be able to specify both the common field and the domain-specific field?

**Comment by noumar** [comment]
> What marc field will be used?

NRM uses MARC `690` for `longitude` and `latitude`. This could be changed to `342` and `00$c$d`.
Seems that `522` describes `Geographic Coverage` and `045` `Time Period`, but I haven't found a more generic field like DC's `coverage`. Claudia, who's a librarian, also mentioned `043`, `662` and `751` but they are all only geographic.

> Will the nrm deposits be able to specify both the common field and the domain-specific field?

It would depend on if we want a generic coverage field(s) or only specific geospatial in Generic schema? We can have several `342` fields and those filled from both Generic and Domain, but that's confusing. But NRM's geospatial fields are content-wise more correct in `342` than `690`.

**Comment by noumar** [comment]
I was thinking about this yesterday. A more generic alternative would be to provide user-selectable metadata fields in Generic, i.e. drop-down + textbox. Drop-down would have content only linkable to MARC fields and then textbox for value.

**Comment by cjhak** [comment]
@noumar Any plans for this issue?

**Comment by noumar** [comment]
I haven't had time to put more thought into it. I won't have time to do anything either, but what I think is:

1. NRM's `latitude` and `longitude` should be moved from MARC `690` to `342`.
1. We should provide customizable metadata for users also, and not only communities.
