### ISSUE TITLE
'Resource type' saved in wrong MARC field

### ISSUE THREAD

**Issue by noumar** [EUDAT-B2SHARE/b2share#586]
`Resource type` is being saved to `980` which is also used for `Domain name`. MARC specs states that `Media type`, which corresponds value-wise, is to be stored in `337`.

Should be done:
- [x] Fix `b2share_marc_handler.py`.
- [x] Add `Resource type` to `bfe_metadata.py`.
- [x] Link `337`, i.e. `Resource type`, to `dc:type` in both `DC.xsl` and `OAI_DC.xsl`.
- [x] Fix REST API.
- [x] Clean up REST API if-else block.
- [x] Migration script `980to337.py`.
 - [x] Fix existing values in DB (`resource_type` and `ling_resource_type`).
 - [ ] Get WUI to show updated values.

**Comment by cjhak** [comment]
@noumar Would this tidy up how we use `980` so it is exclusively used for `Domain name`? (For future deposits, I mean, not what we already have in the db of course).

**Comment by noumar** [comment]
@cjhak yes, it would. I will try and look at the DB content if I can make a generic script that would fix the export and OAI values, at least. But the WUI is still cached somehow.

**Comment by noumar** [comment]
@SarahBA can you take care of the REST API cleaning? It shouldn't be much work.

**Comment by noumar** [comment]
@cjhak for my part this is done. The last points are for @SarahBA (REST) and @llehtine (DB) to do.

**Comment by cjhak** [comment]
@llehtine Is there still DB updates to be done for this issue?

**Comment by llehtine** [comment]
Those were done previously, so this should be OK now
