### ISSUE TITLE
Checksums in B2SHARE

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#595]
The checksums published in the B2SHARE metadata box are NOT the checksums of the data (files +metadata) as expected and as would be handy to check wther the download of data succeeded. 
If one uploads the same file and metadata, two different checksums are published, see also issue #594

**Comment by dblommesteijn** [comment]
@chStaiger which format do you expect the metadata to be in for this checksum?

**Comment by chStaiger** [comment]
Sorry for being sloppy in my description.
I meant that when I upload twice the identical file with exactly the same metadata, I receive two different checksums from B2SHARE.
See also entries
https://b2share.eudat.eu/record/76
https://b2share.eudat.eu/record/75

**Comment by chStaiger** [comment]
So the question is, what is the checksum calculated on?
As a user who wants to download a data file I would prefer the checksum to be calculated on the uploaded file.

**Comment by emanueldima** [comment]
The checksums currently include the file metadata, which contain the full path to the deposited file. But the full path is different from one deposit to another (as it includes the randomly generated depositId). This is what creates the difference in checksums. 

It's not clear to me whether the checksums should include the depositing metadata (title, description and all the other fields). @chStaiger, @cjhak, @dblommesteijn what do you think?

**Comment by chStaiger** [comment]
As a user who downloads data I would like to have the checksum to correspond to the data to see whether the download worked properly. So there are several scenarios:

1) B2SHARE only facilitates to download single data files, then I would expect a list of checksums, each for each data file. If a record holds several data files this might become confusing in the current web-interface (e.g. see https://b2share.eudat.eu/record/169)
2) If a record consists of several data files and a user would like to download the whole data collection, B2SHARE could tar the data beforehand. The metadata record should then contain the checksum of the tar.
3) B2SHARE could also offer to download a data package, i.e. all data + the metadata (e.g. in OAI-PMH, XML, ...) then the checksum should correspond to the whole package.

**Comment by emanueldima** [comment]
The checksum of the entire record, which will also get into the PID, will be the checksum of the files, sorted lexicographically by name, and concatenated. The user will be able to verify this by downloading all the files in an empty folder and then running, in that folder, this bash command:

````
ls -1 | sort | xargs cat | md5
````

@chStaiger @cjhak I don't know what to do with the old records: should we update their checksum or not? I would say that we should, but some people might think the files are corrupted because their checksum has changed since uploading.

**Comment by emanueldima** [comment]
Solved: now only checksumming the deposited files. Use the above shell command to test the deposits.

**Comment by dblommesteijn** [comment]
Perhaps we should add the command to the site as well?

**Comment by chStaiger** [comment]
If a collection consists of many files, which is also supported by B2SHARE, and the user just wants to download a couple of them. How can he verify that the downloaded data is not corrupted?

**Comment by emanueldima** [comment]
I'm afraid this is not possible right now. The consensus seems to be that we should have a PID entry and a checksum for each file, and another PID and checksums for the collection of the files. Right now we only have the PID and the checksum for the collection. 

Issue https://github.com/EUDAT-B2SHARE/b2share/issues/593 partially discusses this point, but also about another problem with the current PID.

**Comment by dblommesteijn** [comment]
I think @chStaiger still has a valid point, and we need checksums per file in the future. 

Shall we mark this issue with a different label en reopen it?

**Comment by cjhak** [comment]
We will soon start investigating changes in the data model, including support for file level metadata and checksums. I will create new issues for that. AFAIK, checksums now works as sensibly as can be for our current data model ( @chStaiger: when using GNU sort for file sorting ;) ) so we can consider this solved for our current version(s) of B2SHARE. More to come for future versions.

**Comment by dblommesteijn** [comment]
@chStaiger so I guess you should make a new issue for checksums for individual files.

**Comment by chStaiger** [comment]
Continued in https://github.com/EUDAT-B2SHARE/b2share/issues/711
