### ISSUE TITLE
Test server 500 Internal server error

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#602]
Server: https://test-eudatis.csc.fi appears to be down.

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, lassi.lehtinen@csc.fi and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.
```

**Comment by llehtine** [comment]
the automatic updating script ran after merge, so it pulled the new master upgrades from git. some new modules missing from the server, installing those

**Comment by dblommesteijn** [comment]
So pull-request #600 caused it to crash?

**Comment by llehtine** [comment]
yes, requirejs-package seems to be missing: [Tue Apr 07 15:28:42 2015] [error] [client 193.166.1.75] ImportError: No module named requirejs

**Comment by emanueldima** [comment]
@llehtine You will have more problems, the new setup is a bit different than the previous one. You should also follow these steps:

1. Generate a new bower file: `inveniomanage bower -i bower-base.json > bower.json`
2. Run bower
3. Generate bundles: `inveniomanage assets build`
4. add more configs:
```
`inveniomanage config set REQUIREJS_BIN `find $PWD/node_modules -iname r.js | head -1`
inveniomanage config set UGLIFYJS_BIN `find $PWD/node_modules -iname uglifyjs | head -1`
````

and make sure redis is working...

**Comment by emanueldima** [comment]
But before all these, run `inveniomanage clean` to clear the old cruft

**Comment by llehtine** [comment]
thanks for these tips, i've got the test-enviroment server now running, but there seems still to be issues (unable to open records etc.), looking now on those. I also documented the steps, so the prod server update should be easier.

**Comment by llehtine** [comment]
now it's up and running, although "Latest Deposits" shows the four first deposist (from 2014)

**Comment by emanueldima** [comment]
created https://github.com/EUDAT-B2SHARE/b2share/issues/608

**Comment by llehtine** [comment]
closing this, as the site is now up and running, uploading also should work. For issue #608 i've created separate pull request.
