### ISSUE TITLE
Unable to install Invenio2 via Vagrant

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#605]
I get various installation issues when installing the `master#b2share+invenio2` (since #600 in `master`) branch, logs below.

**Install procedure**

1. `clone git repository`
2. `cd b2share/install-invenio2`
3. `./install.sh`

**Errors**

```
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/.virtualenvs/b2share/src/b2share/npm-debug.log
npm ERR! not ok code 0
```
File `/home/vagrant/.virtualenvs/b2share/src/b2share/npm-debug.log` does not exist.

A bit further in the process I get the errors below.

```
### Make bower config
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/b2share/bin/inveniomanage", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3057, in <module>
    working_set = WorkingSet._build_master()
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 641, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/vagrant/.virtualenvs/b2share/lib/python2.7/site-packages/pkg_resources/__init__.py", line 827, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wtforms-alchemy>=0.12.6' distribution was not found and is required by invenio
```

Even more (cascading) errors:

```
### Run bower install
bower                       EMALFORMED Failed to read /home/vagrant/.virtualenvs/b2share/src/b2share/bower.json

Additional error details:
Unexpected end of input
```

**Comment by emanueldima** [comment]
I think I found the cause of our vagrant issues. In our provisioning scripts I had added a long time ago a line to update the centos system:

````
echo; echo "### System update"
yum -y update
````

but the update changes the kernel, and the new kernel is not compatible with the vboxguestadditions already installed in the VM. Commenting out the system update seems to solve these problems.

**Comment by dblommesteijn** [comment]
@emanueldima which pull-request was that?

**Comment by emanueldima** [comment]
@dblommesteijn https://github.com/EUDAT-B2SHARE/b2share/pull/606/files fixes the install-invenio2 scripts; the old scripts are untouched, should be aso modified if we continue to use them

**Comment by dblommesteijn** [comment]
@emanueldima so the issue described in #560 have nothing todo with it? I thought they were, too bad.

**Comment by emanueldima** [comment]
@dblommesteijn I am not sure yet, we'll know better in a few days

**Comment by dblommesteijn** [comment]
I keep getting the same errors by running `./install.sh` from `install-inenio2` as before.

**Comment by emanueldima** [comment]
With the #606 patch? I tried it from scratch, it worked here

**Comment by dblommesteijn** [comment]
Tried your branch, I get sort of the same errors. `/home/vagrant/.virtualenvs/b2share/src/b2share/bower.json` appears to be empty.

**Comment by emanueldima** [comment]
I don't understand. Here's what I just did: 
````
git clone -b master#fix-vagrant https://github.com/emanueldima/b2share b2share2
cd b2share2
cd install-invenio2
./install.sh
vagrant ssh
````
In VM:
````
workon b2share
/vagrant/start_b2share.sh
````
and then b2share is available at http://localhost:4000/

**Comment by dblommesteijn** [comment]
I've almost finished the installation, and it seems to work... Perhaps I didn't cleanup my `.pyc` files correctly.

**Comment by dblommesteijn** [comment]
On the first start of `./vagrant/start_b2share.sh` I got a strange error, and the assets didn't load correctly. After `ctrl-c` and rerun of the command the service worked without a hitch.

**Comment by emanueldima** [comment]
I also get those, it's just Invenio restarting itself when loading a new module for the first time. I presume it's normal, but don't know for sure. I can't track it to an exception, though.

**Comment by dblommesteijn** [comment]
Good to know, think we can close this one.
