### ISSUE TITLE
Test server getting stuck at 302-loop

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#620]
When trying to access https://test-eudatis.csc.fi/b2deposit/ while not logged in, the server will get stuck in 302-loop and showing error message for that (The page isn't redirecting properly) instead of proper "Please sign in to continue."-message

**Comment by emanueldima** [comment]
I don't get this on developer VMs, it might be cause by some leftover file from the old b2share version on the test site. Maybe a `inveniomanage clean` may help, or list all the files and look for a difference between the sites.

**Comment by llehtine** [comment]
I've tried the inveniomanage clean for this, but it didn't seem to help. I'll try next to look to see the differences if there is something

**Comment by jirikuncar** [comment]
If `inveniomanage clean` does not help, you can try pure Unix solution: `find . -iname \*.pyc -delete`. Does at least `inveniomanage shell` work? Last option to get some more debug messages is to use `ipython`:
```python
from invenio.base.factory import create_app
app = create_app()
```

**Comment by emanueldima** [comment]
Might be an Apache configuration problem, see below:

````
$ curl -k -v https://test-eudatis.csc.fi:443/b2deposit/
* Hostname was NOT found in DNS cache
*   Trying 86.50.166.38...
* Connected to test-eudatis.csc.fi (86.50.166.38) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: eudatis.csc.fi
> GET /b2deposit/ HTTP/1.1
> User-Agent: curl/7.37.1
> Host: test-eudatis.csc.fi
> Accept: */*
>
< HTTP/1.1 302 FOUND
< Date: Wed, 29 Jul 2015 09:53:32 GMT
* Server Apache is not blacklisted
< Server: Apache
< Strict-Transport-Security: max-age=31536000
< X-Frame-Options: DENY
< Content-Length: 291
< Location: https://test-eudatis.csc.fi:443/b2deposit/
< Connection: close
< Content-Type: text/html; charset=utf-8
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
* Closing connection 0
<p>You should be redirected automatically to target URL: <a href="https://test-eudatis.csc.fi:443/b2deposit/">https://test-eudatis.csc.fi:443/b2deposit/</a>.  If not click the link.---
````

**Comment by cjhak** [comment]
Moving the issue to B2SHARE 2.0. Let's follow this up when we have B2SHARE 2.0 running on the test server.

**Comment by llehtine** [comment]
Seems that this was caused by specifying also ports in CFG_SITE_URL and CFG_SITE_SECURE_URL (like CFG_SITE_URL=u'http://test-eudatis.csc.fi:80' insted of CFG_SITE_URL=u'http://test-eudatis.csc.fi'. Changed the parameter now and closing issue.
