### ISSUE TITLE
Update graphics design for EUDAT2020

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#624]

**Comment by dblommesteijn** [comment]
@cjhak Why have we chosen the new UI to be a bugfix?

**Comment by cjhak** [comment]
@dblommesteijn The new UI is not a bug fix, why do you think that? This ticket was for updating the graphics design of the current UI. We deployed it together with bug fix release 1.4.1 only for the sake of coordinating with the graphics updates of the other web-based services.

**Comment by dblommesteijn** [comment]
@cjhak Because it's merged into the bugfix branch and not into master.

**Comment by cjhak** [comment]
@dblommesteijn This was discussed and decided in the developer's meeting 4 May. We had many urgent bug fixes and our features development was, and still is, severely behind schedule. We are in a situation where we need to focus on swift progress. "Responding to change over following a plan" (agile manifesto).
