### ISSUE TITLE
custom nginx config files generation

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#629]
For production site we are using this to force the https on paths:
        RewriteCond %{HTTPS} off
        RewriteCond %{REQUEST_URI} !/oai2d.*
        RewriteCond %{REQUEST_URI} !/css/oai2*
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

This ticket is for creating script which allows for creating apache configuration files which allow forcing ssl, but enabling http for oai2d

**Comment by emanueldima** [comment]
This issue is solved
