### ISSUE TITLE
Search bar text field too narrow again!

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#634]
Looks like our old friend #415, the shrunken search bar text field, is back again, but this time the problem is occuring in (at least) both Firefox and Chrome. Also, strangely enough it only occurs on the production site (running 1.4) - not on test-eudatis (master branch), not on trng (which should be identical to production and run 1.4).

@emanueldima I assign the issue to you as you solved it last time and may be able to fix it quickly - let me know if you don't have time to do it in this sprint (code freeze on Monday). The design update may also have some effects on the issue.

@llehtine Any idea why this is only happening on production but not on trng, as they are supposed to run the same code?

For description, see screenshots etc in #415 or simply take a look at the search bar at https://b2share.eudat.eu.

**Comment by emanueldima** [comment]
@llehtine The b2s-common.css file that the production uses doesn't seem to be the latest version, please update from git and regenerate all the assets

**Comment by llehtine** [comment]
should be now updated

**Comment by llehtine** [comment]
note: trng-eudatis is not running 1.4 yet, i haven't had time to update it yet; i'm trying to accomplish that also this week

**Comment by cjhak** [comment]
Yes, confirming that this is now OK on prod. I will close the issue.

@llehtine No hurry with trng, it can wait till after the 1.4.1 release if you have more urgent things to attend to.
