### ISSUE TITLE
uploading sometimes not working for production / test site

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#635]
Hi,

Seems like the uploading to production / test-site works bit randomly. Sometimes you can't upload anything, sometimes it work. I've tracked this to b2s_deposit.js, as it sometimes gives this error:

TypeError: _.keys is not a function

But it will not fail everytime, so that's why uploading sometimes works.

**Comment by emanueldima** [comment]
Looks like a problem related to lodash, will investigate
