### ISSUE TITLE
Merge 1.4 fixes to master

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#644]

**Comment by dblommesteijn** [comment]
I'm not sure why we're merging 1.4 when we have not set a date for 1.5 branch.

**Comment by emanueldima** [comment]
I need to have the new UI on master

**Comment by nharraud** [comment]
I also think that it is a good practice. The more often we do it, the less surprises we will have. Normally a maintenance branch should only add bugfixes and should not break anything, but it can always happen. If we wait too long it will be harder to find the cause.

**Comment by dblommesteijn** [comment]
@nharraud We have a workflow in place, which was not followed this time, and I'm NOT happy about this to put it mildly. You can find our workflow here: https://github.com/EUDAT-B2SHARE/b2share/wiki/Contributing

**Comment by emanueldima** [comment]
Well, let's talk about the procedures at the next meeting. Now the deed is done and the merge must happen. There won't be any other developments on 1.4, so it's the best time to do it.
