### ISSUE TITLE
Merge invenio 2.0.x (latest maintenance) branch in B2SHARE

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#646]
There have been some bug fixes in Invenio since the last merge. We need to merge the last maintenance release in order to fix all those bugs.

Found Bugs which are fixed in Invenio:
* inveniosoftware/invenio#2921 ("assets: error on bundle rebuild").
  The patch fixing it is inveniosoftware/invenio@a6945a8d57a000dacdc4f725ee6775196a0b7936.

**Comment by emanueldima** [comment]
We probably want to merge invenio to master, not branch 1.4

**Comment by cjhak** [comment]
I agree, let's merge to master this time. We will not make any 1.4.3 release so we should focus entirely on release 1.5 now.

**Comment by nharraud** [comment]
Ok, if the merge is postponed after 1.5 release, which can happen, I suggest that we merge it in the 1.5 maintenance branche. Invenio 2.0 branch contains only bugfixes.

**Comment by cjhak** [comment]
@nharraud Are there any bug-fixes in Invenio 2.0.3/2.0.4 that you can see that we have any urgent need of? Otherwise we can postpone this issue to milestone 1.5.1 (i.e. merge to the 1.5 maintenance branch, as you suggest).

**Comment by nharraud** [comment]
I only saw the one I listed above for the moment but I didn't test B2share extensively yet. I would prefer to add some more tests to B2share before doing the merge. I don't know how long it will take.

**Comment by cjhak** [comment]
@nharraud Ok, I can't see any fixes we need urgently and we have already postponed 1.5 twice, so probably better to play safe now. I move it to milestone 1.5.1 so you can make the merge to the 1.5 maintenance branch after the next release. Guess you can go for Invenio 2.0.4, as it was released a couple of days ago.

**Comment by cjhak** [comment]
@nharraud Do you think this can be done before end of June? If so, it may be better to move this issue back to milestone 1.5 again (and merge with master), as 1.5 and 1.5.1 are postponed again.

**Comment by nharraud** [comment]
There seem to be few conflicts so it might be done but I'm not sure about it. I would rather move it back to 1.5 once I'm working on it. Right now I'm still adding tests for the b2share REST API.

**Comment by cjhak** [comment]
@nharraud Ok, then I leave it to your judgement to move it if and when you find it appropriate.

**Comment by nharraud** [comment]
Merged
