### ISSUE TITLE
"Community" link on home page is not working

### ISSUE THREAD

**Issue by SarahBA** [EUDAT-B2SHARE/b2share#650]

**Comment by cjhak** [comment]
Let's solve this by simply removing the link. The link is merely a reflection of the design of the EUDAT home page, but has no function in B2SHARE.

**Comment by dblommesteijn** [comment]
The link is working but not pointed to anything:
![screen shot 2015-08-06 at 16 32 36](https://cloud.githubusercontent.com/assets/395001/9114279/42e37cb8-3c59-11e5-81e0-787a953ebc20.png)

**Comment by emanueldima** [comment]
It has been decided that the link will be removed.
