### ISSUE TITLE
search: global search not working because of missing Bibindex

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#652]
On 1.4 dev environment, when you index a record it can be searched only if you specify the searched field.

Example:
  1. submit a document with title 'MyTitle'
  2. wait for bibindex to index it
  3. search 'title:MyTitle'
    * -> document found
  4. search 'MyTitle'
    * -> no result

This happens because of a missing Bibindex scheduling needed since inveniosoftware/invenio@f0a0b02c3b14ac40e3dbddca387eb7e54459ace5 and documented here inveniosoftware/invenio@51641d243139c4df27c0093cdfedd1c0d305df91

The `global` index, which is used when searching all the fields at the same time is a virtual index on top of many other indexes. Virtual indexes need a special Bibindex scheduling as described here b2share/invenio/legacy/webhelp/doc/admin/howto/howto-run.webdoc.

**Comment by emanueldima** [comment]
Could it be connected to https://github.com/EUDAT-B2SHARE/b2share/issues/638?

**Comment by nharraud** [comment]
I don't think so. This issue has nothing to do with character encoding.

**Comment by emanueldima** [comment]
Character encoding? https://github.com/EUDAT-B2SHARE/b2share/issues/638 is about bibindex crashing

**Comment by nharraud** [comment]
Maybe I am wrong, don't know much about Invenio yet, but when I see `Incorrect string value: '\xE2, Giu...' for column 'term' at row 1` it seems to me that bibindex is crashing because of an encoding issue.

For the current issue, the problem is that bibindex is never started for global index. Fields are correctly indexed in each separate index, this is why we can search documents by specifying `title: ...`. However we can't search without specifying the field because global index is not updated. This needs another bibindex running.
