### ISSUE TITLE
b2deposit: save the bibsched task ids

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#661]
The REST API does not save the task ids after calling `task_low_level_submission` (see b2deposit/restful.py). This prevent us from:
- monitoring the tasks.
- making clean unit tests where we run only needed tasks.

**Comment by emanueldima** [comment]
Irellevant for b2share2? we'll not use bibupload, right?

**Comment by nharraud** [comment]
@emanueldima Yes, there won't be any bibupload in Invenio 3.0
