### ISSUE TITLE
Deny uploading empty files via REST API

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#667]
This is a temporary measure because https://github.com/EUDAT-B2SHARE/b2share/issues/575 is delayed.

**Comment by dblommesteijn** [comment]
@emanueldima Is this already fixed in a pull-request?

**Comment by emanueldima** [comment]
No, not yet. You can have it, if that's what you mean :grinning:

**Comment by dblommesteijn** [comment]
No I don't want it actually ;)
