### ISSUE TITLE
Moving _collection.sql file to uploader module

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#668]
In the installation script of b2share there is a sql file `install/_collections.sql`, which adds values to tables. I've discovered `inveniomanage upgrader`, and it handles some sort of db migrations. We should move this file to a module inside the invenio stack: `invenio/modules/upgrader/upgrades/`.

**UPDATE:** It's actually seeding the database with information.

**Comment by nharraud** [comment]
@dblommesteijn I think this is its documentation http://invenio.readthedocs.org/en/latest/modules/upgrader.html

**Comment by emanueldima** [comment]
We plan to separate b2share from invenio. Is it possible to make an invenio upgrader in our own overlay?

**Comment by nharraud** [comment]
Yes, it is already used by other overlays. You can specify global upgrades and per module upgrades.

**Comment by dblommesteijn** [comment]
More documentation here: https://invenio.readthedocs.org/en/latest/upgrading.html#recommendations-for-writing-upgrades

**Comment by emanueldima** [comment]
Does not apply anymore. Communities have their own API.
