### ISSUE TITLE
b2deposit: improve REST API

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#675]
While testing the B2Deposit REST API I found some strange things:
- [x] GET `/records/<ID>` returns a json with `Deposit` as the root key, why? **=> solved by PR: #672.**
- [x] the `open_access` field has some discrepancies:
  - When it is not provided to `DepositionCommit`, the error message is `open_access boolean field required`. However it accepts both a boolean and `restricted` which is a string.
  - In the model, this field has a boolean type.
  - When returned by GET `/records/<ID>` the field contains the string `open`
  - The documentation at https://github.com/EUDAT-B2SHARE/b2share/wiki/REST-API says the field is a boolean
- [ ] improve the record listing API #681 #757 
- [ ] GET `/api/depositions/<deposit_id>` does not do anything useful.  **=> As this is not yet documented, I suggest we remove it and specify exactly what we want it to do before adding something similar**
  - it does not check if the deposition exist but returns a message saying that it does, and even worse, that it is valid.
  - `locations` is an array of links for different actions. As these links are here to give more information, grouping them all together like that is not useful.

I just stumbled on these and will add more as I test the whole API.

**Comment by emanueldima** [comment]
The first issue is solved in this PR: https://github.com/EUDAT-B2SHARE/b2share/pull/672. 
I agree we should change the behaviour of `open_access`.

**Comment by nharraud** [comment]
Ok, Then we can use this issue thread to discuss how we will implement it.
Do we plan to have more values than `open` and `restricted`? If not, I suggest that we use only boolean values as this is currently documented.

**Comment by emanueldima** [comment]
Boolean values should be used, yes. We must also think about the embargo feature, which will create some additional complications.

**Comment by nharraud** [comment]
Closing this issue in favor of #765 as we are completely redesigning the REST API.
