### ISSUE TITLE
b2deposit: change pagination of record listing in REST API

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#681]
There are currently two REST calls listing records: `/api/records/<domain_name>` and `/api/records/`.
They handle pagination with two parameters:
- `page_size`: the number of results per page.
- `page_offset`: the number of pages to skip.

The result contains only the list of records.

This API has multiple limitations:
- The client cannot know if he has reached the end of matching records.
- The clients cannot ask for a given number of documents from a given position.
- The two previous points imply that one cannot ask for the last records for example. Although retrieving last records should be done with sorting, which we don't provide.
- `page_offset` is not a common pagination way. SQL uses `offset` and Elasticsearch uses `from` which is the precise number of records to skip, not the number of pages.

As the page size is given by the client, it can easily compute the number of records to skip. This computation should not be done on the server side as it is less flexible.

Invenio has already been working on it, we could follow their record API so that we can use it once it is released.
- inveniosoftware/invenio#2478
- inveniosoftware/invenio#1724

**Comment by emanueldima** [comment]
We now use the Invenio module for searching in records.
