### ISSUE TITLE
b2deposit: inconsistent letter case in domain names

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#691]
Some domain names have a display_name and some have not.
Some domain names are in upper case and other are not.

example:
- `generic` domain is in lower case and has a display name "Generic"
- `Ecology` begins with an upper case and has no display name
- `BBMRI` is fully in upper case
- `drihm` is fully in lower case

This is a minor problem but we might want to fix that when we move domains definition from file to tables.

**Comment by emanueldima** [comment]
solved in v2
