### ISSUE TITLE
Change "Linked accounts page"

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#692]
`Linked accounts` page in user settings still has an active link to Unity:
https://b2share.eudat.eu/account/settings/linkedaccounts/

Pull-request #632 #631 did not hide this.

**Comment by cjhak** [comment]
The URLs for the B2ACCESS instances are also likely to change soon (B2ACCESS will get in production in the next few weeks). I will follow this up.

**Comment by cjhak** [comment]
"Linked accounts" page should work consistently with #696 (title of this issue changed accordingly).
