### ISSUE TITLE
Easy Invenio deployment

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#697]
In the past, we have discussed with Invenio team (Tim and Tibor) to have e.g. an installer or something similar (container?) for easy deployment of Invenio when a B2SHARE instance is set up.

@nharraud: assigning this to you for investigation of current Invenio plans and coordination with B2SHARE 2.0 development.

**Comment by cjhak** [comment]
Conclusion from July 2015 Hackaton: containers (probably Docker) will be the solution to go for.

**Comment by cjhak** [comment]
(This issue is for production instances, not dev-env).

**Comment by dblommesteijn** [comment]
Sorry, didn't read it properly

**Comment by emanueldima** [comment]
We'll use Docker
