### ISSUE TITLE
Initialize the database via fixtures

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#701]
It is possible to insert initial values into the database by using a file named “fixtures.py” in a module. Examples:
`./invenio/modules/indexer/fixtures.py`
`./invenio/modules/ranker/fixtures.py`
`./invenio/modules/search/fixtures.py`
`./invenio/modules/submit/fixtures.py`
`./invenio/modules/sword/fixtures.py`

They are loaded by this code:
`./invenio/ext/fixtures/__init__.py`

It’s also possible to use mixers instead but there is no example in invenio. The code handling mixers is here: `./invenio/ext/mixer/__init__.py`

(from @nharraud)

**Comment by tiborsimko** [comment]
BTW if you want to see a mixer example, here is CDSLABS's configuration:

- https://github.com/CERNDocumentServer/cds/tree/cdslabs/cds/base/mixer

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
