### ISSUE TITLE
Metadata template various issues with stylesheets

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#702]
The RDA metadata template has a date-picker but the stylesheets look wrong.

![screen shot 2015-06-26 at 16 02 55](https://cloud.githubusercontent.com/assets/395001/8378937/f5008cb8-1c1c-11e5-9461-a9275e28e373.png)

**Comment by dblommesteijn** [comment]
More UI related issues with 'Linguistics' metadata template, below. The `resource type` selector doesn't fit.

![screen shot 2015-07-06 at 12 00 00](https://cloud.githubusercontent.com/assets/395001/8519965/a2ad51a0-23d6-11e5-97b2-44b5883447fd.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
