### ISSUE TITLE
Metadata validation feedback UI wrong place

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#703]
When submitting an incorrect metadata template with your deposit on b2share, the UI presents feedback per field (in the case below Title, Description), but this feedback (This field is required) is appended at the top of the form. When you have a long list of feedback + input-fields this list is very extensive.

![screen shot 2015-06-29 at 14 44 02](https://cloud.githubusercontent.com/assets/395001/8408099/855e70a2-1e6d-11e5-98cc-ffba1c366c41.png)

The same goes for specific metadata templates (Linguistics for example):

![screen shot 2015-06-29 at 14 47 39](https://cloud.githubusercontent.com/assets/395001/8408146/cfd4cb72-1e6d-11e5-8e9b-ecf9ccaaa9bc.png)

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
