### ISSUE TITLE
Inexhaustive list of metadata disciplines

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#704]
The `Discipline` field of the `Generic` template has an very long list of disciplines to select.
I would suggest to limit the list, or make it searchable by some input field: `data-live-search="true"` according to http://silviomoreto.github.io/bootstrap-select/

![screen shot 2015-06-29 at 16 22 52](https://cloud.githubusercontent.com/assets/395001/8409963/9fa31cb6-1e7b-11e5-8bef-db18f386023c.png)

**Comment by llehtine** [comment]
This also came up today when meeting with Aalto. The disciplines list is quite long, so would it be possible to limit it also by the domain?

**Comment by emanueldima** [comment]
The v2 ui will look different, we have a task for it: https://github.com/EUDAT-B2SHARE/b2share/issues/843

**Comment by emanueldima** [comment]
see also https://github.com/EUDAT-B2SHARE/b2share/issues/872

**Comment by janiheikkinen** [comment]
A discipline search function was also requested by EISCAT.

**Comment by emanueldima** [comment]
solved in v2, before rc11
