### ISSUE TITLE
Restricted processed records

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#705]
~~New deposit creates only an restricted records via web-UI. Deposit [239](https://b2share.eudat.eu/record/239) was created with open access enabled, but turns out to be restricted.~~ 

**UPDATE:** On my development machine, `master` branch checkout I've got an issue with `open-access`. It appears no matter the setting, all deposits are created with restricted access.

**UPDATE2:** On the latest bugfix release `v1.4.2` this bug is not present.

**Logged in as owner of deposit:**
![screen shot 2015-06-29 at 17 58 14](https://cloud.githubusercontent.com/assets/395001/8412182/66631296-1e88-11e5-85d6-b880bb0a8199.png)

**Not logged in:**
![screen shot 2015-06-30 at 14 55 30](https://cloud.githubusercontent.com/assets/395001/8431186/0c05688e-1f38-11e5-92bd-cd12722dad58.png)

**Comment by emanueldima** [comment]
The "Restricted Processed record" flash message is added by Invenio and is indeed misleading. The actual access level is public: I can see the file and its content.

**Comment by dblommesteijn** [comment]
@emanueldima you are correct, however I have this issue on my development machine, and thought I had reproduced it on the live system.

**Comment by dblommesteijn** [comment]
I've tested with `v1.4.2`, on this tag the bug is not present.

**Comment by emanueldima** [comment]
Did you create the record via the web UI or the rest api?

**Comment by dblommesteijn** [comment]
Web UI

**Comment by dblommesteijn** [comment]
I've just tested the RestAPI, with `open_acces: "true"`, and it saves the record correctly. It seems the issue is with the web-UI only.

**Comment by emanueldima** [comment]
I cannot reproduce the issue. I made a new VM, created a user and then created a record in the generic domain. I have not changed the access level from the default 'open' state. When I login as another user, or when I am not logged in, the record is still accessible. 

@dblommesteijn Have you changed the domain, or did anything different?

**Comment by dblommesteijn** [comment]
I'm working on a new metadata template for a SURFsara case. 

When I checkout one of the bugfix branches it works, but working on master (NOTE with my local changes reverted), it does not.

**Comment by emanueldima** [comment]
I have just created a record on the test server, and I see the same behavior that you reported. When a record is first created Invenio puts it into a "Restricted" state, no matter the access level specified by the user. After a while the record is processed somehow (by some bib* processes, I imagine), the "Restricted" state goes away, and the record becomes publicly accessible. On my VM the record spends very little time in the "Restricted" state, but on the test server it takes a longer while.

I don't see how I can fix it, it looks like this is how Invenio works.

**Comment by dblommesteijn** [comment]
Aha, than I suppose there is an issue with my local bib process?

**Comment by emanueldima** [comment]
We can postpone this issue since it's lost its 'Important' status.

**Comment by emanueldima** [comment]
Not relevant in B2SHARE2
