### ISSUE TITLE
File checksums

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2SHARE/b2share#711]
When downloading single files in a record/data collection it is necessary to have a checksum of this file as metadata entry to compare with the downloaded file(s).
Currently, checksums are given on collection level, so it is not possible to verify the integrity of single files.

**Comment by cjhak** [comment]
Currently "Date" and "Size" are file level metadata. This seems to be the Invenio data model.
To investigate: can the Invenio data model support "Checksum" as a file level metadata attribute as well?

**Comment by nharraud** [comment]
Yes, I think that it can be done. Zenodo offers it in its API. https://zenodo.org/dev#restapi-rep-files

**Comment by tiborsimko** [comment]
Yes, checksums are supported in Invenio, and can be "randomly verified" on the server side before serving the files.

**Comment by emanueldima** [comment]
ready in v2: https://github.com/EUDAT-B2SHARE/b2share/pull/933
