### ISSUE TITLE
Metadata generic fields 'more detail' not shown

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#713]
Some fields of the generic `more detail` fields are not shown on the deposit page. At least `language` is not shown on the deposit page (I suspect there are more).

![screen shot 2015-07-06 at 12 05 48](https://cloud.githubusercontent.com/assets/395001/8520098/c3abd452-23d7-11e5-9386-fa6b3a6c72ec.png)

**Comment by dblommesteijn** [comment]
Thus far I can only confirm `language` is missing. The following should be added to `invenio/modules/formatter/format_elements/bfe_metadata.py`:

```python
language = bfo.field('546__a')
if language:
    ret += html.format('Language', language)
```

@nharraud is there a way to template this in the B2share module instead of the invenio core?

**Comment by nharraud** [comment]
This file (`invenio/modules/formatter/format_elements/bfe_metadata.py`) does not exist in Invenio. It has been created for B2Share in Sept 2014. Thus I would say that it can be safely modified.

However, it is indeed possible to create custom formatter and add them in an Invenio overlay (thus without modifying Invenio core). They can even override existing Invenio ones. This is be part of the work which has to be done to separate Invenio from B2Share.

**Comment by nharraud** [comment]
Also the bfe files will apparently get deprecated in future versions of Invenio.

**Comment by dblommesteijn** [comment]
@nharraud good to know, thanks

**Comment by emanueldima** [comment]
solved in beta1
