### ISSUE TITLE
OAI-PMH: "Resource Identifier" should be the PID

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#719]
See https://b2share.eudat.eu/oai2d?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:b2share.eudat.eu:195

The `Resource Identifier` field is currently set to `http://b2share.eudat.eu/record/195`
Should it be changed to a PID?

**Comment by cjhak** [comment]
Yes, `Resource Identifier` shall be changed to contain PID, probably in the form of a resolvable URL, e.g. http://hdl.handle.net/11304/60449ad8-e99a-11e4-ac7e-860aa0063d1f. I've asked for feed-back from the requester to confirm that this is the preferred format.

(Changeing issue title accordingly and removing "Question" label).

**Comment by nharraud** [comment]
Is it normal that there are two fields `Resource Identifier`. One with an URN matching `OAI Identifier` and the other with an URI? I found the specifications for `OAI Identifier` but not `Resource Identifier` http://www.openarchives.org/OAI/2.0/guidelines-oai-identifier.htm

**Comment by cjhak** [comment]
@nharraud Normal or not, I do not know, but the reason here is that this is the Dublin Core metadata standard supplied via OAI-PMH protocol, and therefore there is one `Resource Identifier`in OAI-PMH format and a second one in Dublin Core format.

**Comment by cjhak** [comment]
@nharraud c.f. e.g. http://dublincore.org/documents/usageguide/elements.shtml, 4.14. Identifier

**Comment by cjhak** [comment]
The requester has confirmed that the preferred solution is that the (DC) `Resource Identifier` field should have the resolvable URL format of the PID, i.e. e.g. http://hdl.handle.net/11304/60449ad8-e99a-11e4-ac7e-860aa0063d1f.

(This issue is now scheduled for milestone 1.6 and up for grabs for anyone who wants to solve it).

**Comment by emanueldima** [comment]
Seems to work: https://test-eudatis.csc.fi/oai2d?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:b2share.eudat.eu:269

Now the DC metadata reports 2 identifiers, the first being the PID
