### ISSUE TITLE
Create draft REST API python file

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#723]
* Python file to be used for developing the new HTTP API
* Includes documentation of the API
* Should reside in "Evolution" branch

**Comment by cjhak** [comment]
The HTTP API should be separated from the current b2deposit module, but we need to discuss the future module-structure further.

**Comment by emanueldima** [comment]
Each module has now a rest file, responsible for the rest api. The actual implementation is underway.
