### ISSUE TITLE
Installation packet like rpm for redhat/centos

### ISSUE THREAD

**Issue by thomasmtl** [EUDAT-B2SHARE/b2share#724]
This installation script in the b2share package for a wsgi apache environment isn't so handy. Specially when we try to have a production environment. In which we need to update and keep the old database, data, templates and settings. We prefer to have the possibility to pack the things and deploy a package on the production, after testing. That we can have a reliable and consistent running service with less downtime as possible. :-)

**Comment by cjhak** [comment]
We will support installation packages in the future (planned for autumn 2015), but it will not be RPM. Instead some container technology (e.g. Docker) is the most likely candidate for production ready installations. This is covered by #526 and #697.
