### ISSUE TITLE
Howto setup admin user

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#732]
How is the admin user enabled (or setup) on a new installation of B2share? According to #664 there is an interface but am not sure how to access it.

**Comment by emanueldima** [comment]
By default, there is an `admin` user with no password.

**Comment by dblommesteijn** [comment]
Probably not how we want this system to work, perhaps we should fix it.

**Comment by nharraud** [comment]
This is now documented [here](https://github.com/EUDAT-Training/B2SHARE-Training/blob/22876ebdc128f5872b46ec4e88919c3044f6d2d7/deploy/09_User_management.md).
