### ISSUE TITLE
test-eudatis shows "Internal Server Error"

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#734]

**Comment by cjhak** [comment]
This issue may be related to the merge of Invenio maintenance branch.

#734 and #735  occured with a couple of weeks between them and the machines run different branches, so the issues are likely to be unrelated to each other.

**Comment by llehtine** [comment]
This was related to the merge of invenio maintenance branch. Script on the server got updates from github, but didn't install the new version of Invenio which then broke the running instance. Installed the new version, and it should be now running OK on test-eudatis.csc.fi
