### ISSUE TITLE
trng-b2share shows "Internal Server Error"

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#735]

**Comment by dblommesteijn** [comment]
So this site: https://test-eudatis.csc.fi is down right?

**Comment by cjhak** [comment]
@dblommesteijn Yes, both https://test-eudatis.csc.fi (#734) and https://trng-b2share.eudat.eu (this issue) shows "Internal server error" in the WUI (someone said the REST API still works on trng-b2share, but I haven't verified that). trng-b2share has been down for some weeks, while test-eudatis seem to have collapsed last week so it is probably unrelated.

**Comment by llehtine** [comment]
There was one partition which seems to ran out of disk. Fixed.
