### ISSUE TITLE
search: repeated title and description in search results

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#738]
This is something that has been bothering me for some time and I didn't found any corresponding ticket.

The title and description are repeated twice for each search result. The record itself seems fine so it is probably a search view issue.

I have seen this on both production and current master branch.

**Search results** (There are two records with the same title and description because I deposited it multiple times)

![screen shot 2015-08-04 at 16 22 05 2](https://cloud.githubusercontent.com/assets/5708796/9062875/33260e8e-3ac5-11e5-8dcb-cc1c9b4861f5.png)

**Actual record**

![screen shot 2015-08-04 at 16 28 18 2](https://cloud.githubusercontent.com/assets/5708796/9062955/b15e73a4-3ac5-11e5-9566-d4dda333437d.png)

**Comment by cjhak** [comment]
We should prioritise this issue too for the 1.6 release, so if anyone has time to work on this, please pick it up (RDA are concerned).

I got some feedback that the problem occurs also on the collection pages (e.g. https://b2share.eudat.eu/collection/rda) but that it is fine when using "the API" (not sure which one of them).

**Comment by emanueldima** [comment]
The formatting error has been fixed (see https://github.com/EUDAT-B2SHARE/b2share/pull/748) but in production and test sites the formatting cache must be cleared and rebuild. I have managed to solve this issue with `inveniomanage formatter expunge`.

@llehtine Please clear the formatting cache on production after switching to B2SHARE v.1.6

**Comment by cjhak** [comment]
@llehtine Please do this on test-eudatis as well

**Comment by llehtine** [comment]
I've ran it now on prod/test
