### ISSUE TITLE
RDA logo on https://b2share.eudat.eu/collection/rda

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#742]
Request from RDA (https://helpdesk.eudat.eu/Ticket/Display.html?id=10397):

"Can the collection landing page (https://b2share.eudat.eu/collection/rda ) be modified in the following ways:
a) On the spot where it now says "RDA:" could we get some branding 
(i.e. our logo and so forth). I.e. It needs to look a bit more RDA official. The /collection/something pages already have a special rendering inserting the title there, so you have an easy hook to add the branding."

Logo: https://b2drop.eudat.eu/public.php?service=files&t=4b60a0c92dd263ec185ab4f81fb40d1b

**Comment by nharraud** [comment]
I can add a directory where every collection can have a logo and display them on collection page by modifying Invenio code. This is clearly a hack and, if accepted, it should not be added in the feature list, documentation or changelog.

We would remove this in 2.0 and add a proper way to create communities with their logos.

I fear that trying to add this cleanly in 1.6 a week before its code freeze would make migration to 2.0 more complicated.

**Comment by cjhak** [comment]
@nharraud, if you think that is the easiest way to get it to work before the 1.6, then please go ahead with it. I agree that we should come up with some other solution for B2SHARE 2.0, but there we will implement it in the new UI anyway. So we will leave your solution in the 1.6.x branch and replace it in evolution/2.x.

@dblommesteijn, please consider how we can solve this (or perhaps make something better) in the new UI.

**Comment by cjhak** [comment]
@nharraud I assign this issue to you for now, although I know you will not be working on Friday. If you don't have time to fix it this week, please assign it back to me. We will need to have the branding visible on the test system so RDA can take a look at it on Monday already.

**Comment by nharraud** [comment]
Ok no problem. I should be able to work on it today or tomorrow.

**Comment by nharraud** [comment]
I have reused the logos already existing in the `main` module. These are the ones displayed during when the user submits a new record and has to choose a `domain`.

I know that we have renamed `domain` as `community` for 2.0 but I have used it here for better consistency in 1.6.

**Comment by nharraud** [comment]
![collection-logo](https://cloud.githubusercontent.com/assets/5708796/9385899/2dc167ae-4759-11e5-8189-d2e59d5e6732.jpg)

It should work with other domains too. I tried with EUON and CLARIN. I had to duplicate CLARIN logo as its collection is named `Linguistics`. We might want to fix this inconsistency in future releases.
