### ISSUE TITLE
Increase logo size on community page

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#753]
Feedback from RDA on #742:

"In short: I think it looks good, but the RDA logo could be a bit bigger."

**Comment by nharraud** [comment]
Do we have the other logos in bigger size too? The ones commited in B2Share have a poor resolution. Having just one collection with a big logo and the others with small ones would not be a good design choice.

**Comment by nharraud** [comment]
SVG logos would be the best. Then we can change their size very easily without losing quality.

**Comment by cjhak** [comment]
Unfortunately, for most of the communities I don't think we have anything better. 

If the effect for other commuities is bad, then I think we can close this issue as "won't fix".

**Comment by nharraud** [comment]
Ok for closing the issue. We will have to discuss the community page customization use cases for 2.0. Right now the communities are hard coded so we can do dirty hacks but we are planning to enable dynamic community creation later on. Each community should be able to upload their own logo and change it later if they want to. They will surely want other customizations like:
- an url to their website
- a short description of the community

I will create another issue for this.
