### ISSUE TITLE
"Rest" API does not indicate the availability of futher records

### ISSUE THREAD

**Issue by httpPrincess** [EUDAT-B2SHARE/b2share#757]
to reproduce:
curl -i https://b2share.eudat.eu/api/records?access_token=secretToken\&page_size=500

The page size is silently replaced with the maximal value (100) and only maximal value of records is returned. This would be perfectly ok if the availability of further records would be indicated somehow. 

check:
https://github.com/EUDAT-B2SHARE/b2share/blob/master/invenio/b2share/modules/b2deposit/restful.py#L261

proposed solution: set of links e.g. _next, _prev, _self could be added to the response. See HAL standard for instance.

**Comment by emanueldima** [comment]
Works on v2, thanks to Invenio 3:

````
"links": {
    "next": "https://b2share.local/api/records/?size=10&sort=mostrecent&page=2&q=",
    "self": "https://b2share.local/api/records/?size=10&sort=mostrecent&page=1&q="
}
````
