### ISSUE TITLE
Add RDA user as RDA administrator

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#758]
@llehtine Please add the user identified by this email: [enquiries at rd-alliance com] to the user group rda_domain_administrators

**Comment by llehtine** [comment]
i don't really understand the group-definition here, but i've added new role rda_domain_administrators. Is there any actions that needed also to be added to that role?

**Comment by emanueldima** [comment]
I'm not sure a role is the same as a group, I think not. You should go, as administrator, to /yourgroups/index and there should be a list of groups ( ..._domain_administrators).

**Comment by emanueldima** [comment]
The groups in the list were created by the `invenio/b2share/upgrades/b2share_2015_06_23_create_domain_admin_groups.py`

**Comment by llehtine** [comment]
Thanks. Got it now.

**Comment by llehtine** [comment]
Was done after the upgrade
