### ISSUE TITLE
[RFC] - new REST API design

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#765]
This issue is here to discuss and summarize the new REST API design. All other related issues should be listed here.
# QUESTIONS
## B2Access status

What will be the B2Access status in a month or so. Can we delegate all the user creation and authentication to it now or do we have to implement it now?
# General design
## Discrepancies with previous API
- We will always use `Community` and `Communities` instead of `Domain` or `Collection`.
## Naming
- all endpoints should use plural
  - example: /api/records
- resources should always be accessible by ID, even if they have a name because this name might change at some time. Access by name can be added too as long as name and IDs can't conflict.
  - example: /api/communities/<ID> is mandatory and /api/communities/<name> is optional
## Searching/Listing

Example of searching: /api/communities?name=EUDAT&from=10&size=50
- Mandatory: Each searching/listing of resources should indicate if there are further resources. (see #757). Possibilities:
  - Have a boolean indicating if there are remaining resources.
  - Have a link indicating previous and next page.
    - Problem is that we can't then change the number of resources per page.
- Optional: Return the total number of matching resources.

**Header vs Content** (**TODO**):
We can send those information in the header or in the returned json object. Which one do we choose?

**Pagination:** (**TODO**)
Two designs are possible (see #681):
- the old one which ask for a given page with a fixed number of page.
- have two parameters `from` and `size` which enable to ask for any number of items from any starting point.
# More detailed design
## Users

see: #764
- `/api/users` (LATER)
  - [GET] search for users. Available filters are:
    - name: for autocomplete.
- `/api/users/<ID>`
  - [GET] get a user profile information.

One can create a user account through the web UI only. REST API does not allow this.
It will ask for a captcha and send the captcha token.

user format:

```
{ id: <USER_ID>, name: "...", email: "..." }
```
## Records

see: #757
- `/api/records`
  - [GET] search for records. Filtered with queries (see Invenio-queryparser). 
  - [POST] create a record
- `/api/records/<ID>`
  - [GET] get a record.

record format:

```
{id: <RECORD_ID>, published_by: <USER_ID>, files_count: 42, metadata: [ { schema: <SCHEMA_ID>, fields: {} } ] }
```

**Design details**
Records have blocks of Metadata, each one having their own schema. Records's schemas do not change.
When a new draft record is created, the user selects the schemas he wants to add.

**Access control**
- Enable embargo mode configuration. see #768 
## Communities
- `/api/communities`
  - [GET] search for communities.
- `/api/communities`
  - [POST] create a community
- `/api/communities/<community_id>`
  - [GET] get a community metadata
  - [PATCH] modify a community

Community format:

```
{ id: <COMMUNITY_ID>, name: "...", desc: "...", schemas: [ <SCHEMA_ID> ] }
```

A community has a list of schemas which can be used when submitting a new record.
## Schemas
- `/api/schemas` (LATER)
  - [GET] search for schemas
-  `/api/schemas`
  - [POST] create a new schema
- `/api/schemas/<ID>`
  - [GET] get a schema
- `/api/schemas/<ID>/deprecate?new_version=<ID>`
  - [POST] deprecate a schema in favor of a new one. `new_version` is optional

A schema cannot be modified. Only a new schema with a new ID can be created.
A schema can be deprecated. Then it cannot be used to create new records. When it is deprecated, a new schema ID can be given as the new version.

schema format:

```
{ id: <SCHEMA_ID>, managed_by: <ROLE>, is_deprecated: true/false, new_version: <SCHEMA_ID>, fields: [ { name: "...", type: "...", desc: "...", required: true/false, cardinality: 34 , controlled_vocabulary: [list of allowed values] } ] }
```
## Files and FileContainers
- `/api/records/<ID>/files`
  - [GET] search for files. This will be useful if there are many files in the record. Possible filters are:
    - parent_id: id of the file container.
    - recursive: list all the files in the container and child containers recursively.
    - name: file or container name
- `/api/records/<ID>/files/<ID>`
  - [GET] get a file metadata
  - [DELETE] delete a file/container (only possible for draft records). If it is a container it deletes recursively its children.
  - [PATCH] change file/container name
- `/api/records/<ID>/files<ID>/content`
  - [GET] get a file's content

file format:

```
{ ID, name, parent_id: <CONTAINER_ID>, size }
```

file container format:

```
{ ID, name, parent_id: <CONTAINER_ID> }
```
## References (Work In Progress)
- `/api/records/<ID>/references`
  - [GET] list a record's references
- `/api/records/ID/references/<ID>`
  - [GET] get a record reference

reference format:

```
{ id: <REFERENCE_ID>, type: "...", to: <RECORD_ID> }
```
## Authentication

REST API should be used with some application token.
We are not sure yet how the UI could login.

There will surely be some endpoint like this one:
`/signin`

**Comment by emanueldima** [comment]
We've agreed that the status of a record can change according to a finite state automaton, but how exactly the REST API would allow the status change has been ambiguous so far. I propose to use a dedicated REST endpoint for the status and allow changes to it via a PATCH method, e.g.:

````
PATCH /api/records/123/status  HTTP/1.1
Content-Type: application/json
{"status":"submitted"}
````

Getting the status from this endpoint should also be possible: `GET /api/records/123/status  HTTP/1.1` returns `{"status":"submitted"}`

See also : http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api

**Comment by nharraud** [comment]
The problem I see with a specific endpoint for the status is that we will also want the record status when we get the whole record. We don't want to have to do two GET operations to retrieve both pieces of information as it takes more resource and, more important, we might get a record half updated.
Maybe we can have the record status as a field inside the record itself but outside of the publisher's metadata. like this:
```
{
  id: <RECORD_ID>,
  status: accepted
  published_by: <USER_ID>,
  accepted_by: <USER_ID>,
  files_count: 42,
  metadata: [ { schema: <SCHEMA_ID>, fields: {} } ]
}
```

Regarding the change of status I see three ways of doing it:
- describe the resulting state as you propose
- describe the action changing the status (`accept` instead of `status="accepted"`)
- describe a list of actions

I know that there is a lot of debate on how to request actions on resources. Big services have different preferences:
- Github API has no verb in their endpoints and describes only the resulting state (ex: pull request state updated with PATCH and the new state, https://developer.github.com/v3/pulls/#update-a-pull-request)
- Heroku API has no verb in their endpoints except for one regenerating authorization. They add fields in their PATCH requests which are more than just fields to replace. (https://devcenter.heroku.com/articles/platform-api-reference#oauth-authorization-regenerate)
- Paypal has verbs in their endpoints (*refund* or *pay*, https://developer.paypal.com/docs/api/#execute-an-approved-paypal-payment)
- Stripe has verbs in endpoints (*pay* an invoice, https://stripe.com/docs/api#pay_invoice)
- DigitalOcean has an endpoint for all actions on each resource and the name of the action in the request body (https://developers.digitalocean.com/documentation/v2/#droplet-actions)
- Twitter has verbs in every endpoint, even when a DELETE should be used (https://dev.twitter.com/rest/reference/post/statuses/destroy/%3Aid)

I personally like the way the Mailchimp people describe their API: https://github.com/mailchimp/APIv3-examples/wiki/What-is-REST%3F
They just say what is restful and what is not, justifying their choices with concrete examples.

I will now try to do the same by listing the pro and cons of each solution.

Using PATCH with new state
---------------------------------------

The advantage is that it makes one of our scenarios more easy:
The user:
- creates a deposition
- fills the fields
- submits the new record for approval.

The last step can be done with only one HTTP PATCH request by sending all the metadata fields and the new status at the same time.

The first drawback of this solution is that it makes the PATCH code handler and its documentation more complicated. The more our workflow will evolve the more conflicting cases, like dependencies between fields, will appear and we will have to handle and document them.

The second drawback is that we won't be able to change the workflow easily. If for example a record needs to be accepted by multiple people before going in "accepted" status we can't just make a PATCH with the new status. This is just an example, I know that we don't have this use case listed in our requirements. **(1)**

Sending just the action
------------------------------

Multiple ways of doing it are possible:
- with POST and a dedicated endpoint like `POST /api/records/123/actions/submit`.
- with PATCH and the action described in the body like:
```
PATCH /records/<RECORD_ID>
{
  action: reject,
  message: "this is a spam"
}
```

The drawback is that we cannot submit a record with modifications in one request. We have to first do the PATCH with the updated metadata and then do the submit. Also update fields requests would be more complicated:
```
PATCH /records/<RECORD_ID>
{
  action: update-metadata,
  fields: {
    title: "test"
  }
}
```

The first advantage is that what we describe is the action, not the result. The result might change later if we want (see **(1)**). For example, if the user has some special privileges which enable him to bypass the review, the record could go directly in `accepted` state after a `submit`.

The second advantage is that the code and documentation are simpler. Each endpoint has its own.

Sending a list of actions
--------------------------------

The PATCH RFC says `The PATCH method requests that a set of changes described in the
request entity be applied to the resource identified by the Request URI.` (http://tools.ietf.org/html/rfc5789). It does not say that we can only list modified fields.

Thus we could have something like:
```
PATCH /records/<RECORD_ID>
[
  {
    action: update-metadata,
    fields: {
      title: "test"
    }
  }, {
    action: submit
  }
]
```

This would enable us to have multiple actions performed in one request.

It does not have the drawback **(1)**

It would make backend code easy to maintain by just dispatching the actions according to the action.

The drawback is that the documentation might be a little more complex.

The biggest drawback is that we don't have rollbacks in Invenio and thus we cannot respect the PATCH RFC which says `The server MUST apply the entire set of changes atomically and never provide (e.g., in response to a GET during this operation) a partially modified representation.`

Conclusion
---------------

No real conclusion. These are just suggestions. After thinking for some time I personally prefer the second solution with a PATCH and the action described in the body.

The PATCH RFC has some very clear documentation for the error handling. If the action is not possible on the record (ex: `save` on an already `accepted` record) we could return a `409 CONFLICT` status error as they suggest. And `403` if the user is not allowed to do this request (ex: a user accepting a record although he is not the community manager)

What do you think?

**Comment by emanueldima** [comment]
I believe having a separate `action` field in the content creates more trouble than it's worth (creates more structure in the json body and requires its own controlled vocabulary). The `/status` endpoint avoids this issue; we should also return the record status when GETting the record, so to avoid a second GET call to `/status`. The record already contains a set of fields that are retrievable but not directly settable (`id`, `published_by`, `creation_date`, etc.) so it's not a singular case. And changing the status of a record is something that happens rarely, and in my opinion should have a dedicated HTTP request in any case -- I don't see a reason to optimize for performance here, but for clarity.

**Comment by nharraud** [comment]
Yes but this solution would also create clarity issues. A field which you can set on one endpoint but not on another. If we start like this we will have other cases too in the future and it will be really complicated to explain that here you can request a PATCH but not here, even though it's the same field. This does not seem to be a very common approach and might be confusing for other developers.

Also what we would be doing by setting the record status is in fact an action setting automatically other fields at the same time like "creation_date" or "published_by". These fields are implicit. Thus making the patch look like a json diff but performing more than that can also be confusing.

Using actions rather than setting final state is not only for performance, but also for coherence. Setting the whole "tags" list, for example, each time one adds or remove a tag would create conflicts when multiple users change the tags at the same time. On the other hand, having actions like "add_tag" or "remove_tag" prevents those issues. Thus if we have actions in some place we can also have them for records too.

If you prefer not having the action in the body bug having a dedicated endpoint, we can do the same with the action in the URI like many other services. The patterns I have seen in most of them are
`http://<RESOURCE_NAME>/<ID>/<ACTION_NAME>` and `http://<RESOURCE_NAME>/<ID>/actions/<ACTION_NAME>`

**Comment by emanueldima** [comment]
No, I think having verbs in the URL is a bigger mistake. I would rather go with your previous list-of-actions-in-PATCH-body suggestion, that's perfectly compatible with the PATCH RFC.

**Comment by nharraud** [comment]
I agree that verbs in the URL is often frowned upon by "totally restful" supporters, even if it is still used a lot.

The list-of-actions-in-PATCH-body would be compatible with the RFC if the backend could apply them atomically and revert all actions if one failed, which is sadly not the case right now. It might be in the future.
That's why I would prefer one action only per request for the time being, even if it is less performant. We can accept list of actions later by just detecting if the body is an object or an array.

Does it mean that you would accept having the action name in the body? If so I can rewrite this issue by removing all verbs from URI and using only PATCH.

I see that I have also misused verbs for resource creation. I will replace all `POST /api/<RESOURCE>/create` with `POST /api/<RESOURCE>` if that's ok with you.

**Comment by emanueldima** [comment]
Yes, I agree with action(s) in the body, but this shouldn't be decided by just the two of us. @SarahBA  @cjhak @dblommesteijn @llehtine what do you think? I'd like to know we have a final decision, I need to stop thinking about this one.

**Comment by SarahBA** [comment]
I also prefer the idea of having actions in PATCH body rather than having an endpoint. But I think it should follow one action for a request.

**Comment by nharraud** [comment]
After doing some more research something started to bother me and I reread the PATCH RFC again. I saw this sentence which I missed before: `The set of changes is represented in a format called a "patch document" identified by a media type`. If I understand this correctly, it means that I was just wrong and that one is not supposed to use patch with custom actions. PATCH is just here for modifying the resource with formats like json-patch.
This makes POST more appropriate if we send actions.

We can also go back to your proposal @emanueldima but then we have to add fields like the reason of rejection to records.

**Comment by emanueldima** [comment]
We can just define our own json patch format with a custom media type. Easier to process than a json-patch file.

**Comment by nharraud** [comment]
I don't think documenting our ever-changing list of available actions can pass as a rigorous media type. existing media types like json/xml/json-api/yaml are very precise and don't change.

**Comment by emanueldima** [comment]
Our patch file can be a subset of json with a well defined structure and controlled vocabulary for elements; or we can use json-patch, fine with me. Both give me enough rest :+1:

**Comment by nharraud** [comment]
I suppose json-patch might work (it is used by Paypal) or just listing the fields which have to be replaced, which is the solution you proposed at the beginning and also the one used by Github. We already have trouble defining API, I prefer not to try defining a custom format.

One question for @cjhak. Can we reject use cases where multiple people have to validate a record before it is accepted/marked as reviewed? If we do, it simplifies things a lot and also means that we can just replace the status in records as proposed by @emanueldima.

Sorry for adding more questions.

**Comment by cjhak** [comment]
@nharraud I'm not sure what use cases you are thinking of. We most likely need to support use cases where a record has to be accepted by a datamanager before publication, if that is what you mean.

**Comment by nharraud** [comment]
@cjhak Yes, that's what I mean. If this is the only use case and it won't change then everything is simple :)
However, if I'm not mistaken, you told during the last hackaton that long term plan is to have curation, which means one or more curators. That's why I'm asking if we agree that there will be no use cases where, for example, multiple persons have to validate a record before it is published.

**Comment by cjhak** [comment]
@nharraud I think we can assume that once a record is accepted it is also published (i.e. an individual record does not need to be accepted twice).

At the CERN hackaton we discussed the possibility that it could be rejected, edited (potentially in a loop  rejected and edited again) and then accepted though. It should still only need to be accepted once.

**Comment by nharraud** [comment]
@cjhak  Ok, so we can just replace the status.

@emanueldima As we don't use verbs in URL I suppose we go for PATCH then. Adding one endpoint for the status still seems strange to me. GET should return the same fields as PATCH/PUT requests, which means also fields like "rejection message". On the other hand this would make the replication of status in record look strange as they are not grouped together.

If you prefer to have another endpoint I have thought of another way to do it. Don't hesitate to tell me if you think it's over-engineered.
We could add resources called "status_updates" or "status_changes" which would be accessible at this endpoint:
`/records/<ID>/status_updates/<ID>`

When the admin wants to reject a record he calls:
`POST /records/<ID>/status_updates { "action": "reject", reason: "This is a spam" }`

By getting this status_update he would receive:
```
GET /records/<ID>/status_updates/<ID>
{
  action: "reject",
  reason: "This is a spam",
  by: <USER_ID>
  date: <DATE>
}
```
The status_updates are immutable. Only new ones can be created.
The user can also list the status updates: `GET /records/<ID>/status_updates/`

The POST request creating the status_update would also update the record status as a denormalized field.

The main advantage is that it is simple to document (or at least it seems simple to me), it enables easy access control by not having to check which fields are modified by a PATCH and is REST compliant (no verbs in URL and POST is allowed to have side effects).
We also get the status history for free without cluttering the record.

What do you think?

**Comment by emanueldima** [comment]
I'm not sure, the problem is that these status updates look now like an audit log, but the purpose of the endpoint is completely different. If later we'd want to add such an audit log, providing information about record modifications (who, when, what changed), then the users might get confused. 

I see that the problem is related to the messages. We don't yet have support for reviews and comments on records, and this might solve our problem: state changes can be accompanied by comments, which will be visible to all, just like the discussions in a github issue. The submitter/reviewer could effect the state change and comment at the same time (for this we must support actions in one request, which is probably doable).

**Comment by nharraud** [comment]
As I said, the last solution I proposed might be over-engineered. I saw something similar in the Github API https://developer.github.com/v3/repos/statuses/. Users create status updates with `POST /repos/:owner/:repo/statuses/:sha` and then get the global status with `GET /repos/:owner/:repo/commits/:ref/status`.

If we allow comments and reviews on record without status updates, they will surely need their own endpoints. Then I don't see how we can do both status update and comment in one request. Could you give an example please?

As you took Github issues as an example I went to see how their API is done. They have one endpoint for comments (https://developer.github.com/v3/issues/comments/) and another for the issue itself (https://developer.github.com/v3/issues/). The issues endpoint also enables "state" change with PATCH.
As @cjhak explained that our use case is simple we could drop the idea of sending "actions" instead of "state" and just keep it simple by doing like Github.

But maybe I missed something? What would be the advantage of having the record status as a separate resource?

**Comment by emanueldima** [comment]
You're right, I didn't think it through. We should have a /comments endpoint anyway but it's not possible to update it in a single call. 

I wanted to have status changed in another endpoint because changing a status is a semantically different action. Any record field can be initially changed at will, but after someone changes the status the normal patch actions are no longer allowed. But now that I see it's that much of a headache to decide on this issue, I'm willing to accept the simpler solution: allow status change in /records/ID, and allow metadata and status changes in a single call.

**Comment by nharraud** [comment]
I agree that there will be more checks to do with only one endpoint but I'm willing to accept that too. I don't think that our first API will be perfect. We will surely see limitations during the implementation and have to release new versions at some point.

Some APIs use PATCH as an idempotent operation but this is not mandatory. The RFC says "PATCH is neither safe nor idempotent". So we can just document that PATCH is non-idempotent in our API. Even with a different endpoint the record's metadata would be frozen after a change of state so further PATCH would be forbidden.

This discussion made me think that we will have to design how the released records can be edited, reviewed again and versioned. But maybe later. Let's first have all the 1.x features working again with the new API.

**Comment by nharraud** [comment]
B2SHARE V2.0.0 is released with the new REST API.
