### ISSUE TITLE
Data exchange with communities and other services

### ISSUE THREAD

**Issue by stranak** [EUDAT-B2SHARE/b2share#77]
For example Invenio implements [SWORD protocol](http://swordapp.org/about/) in [BibSword](http://invenio-demo.cern.ch/help/admin/bibsword-client-admin-guide) module and can use it to push data to arXive.org. 

Can / Should we support pushing data to community repositories in a similar fashion? (How) do we fill in metadata that the community may require in addition to our B2SHARE metadata?

**Comment by thijscobben** [comment]
I created a new issue https://github.com/EUDAT-B2SHARE/b2share/issues/1643
