### ISSUE TITLE
User friendly linking to user profile page

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#770]
Feedback from Mark:

"What I am somewhat missing, that you are able to select your profile from the top of the web page. Currently if I want to go to my own profile page I had to go to the B2SHARE home page and then select my name in the line of “logged in as Mark van de Sanden”. Normally you see a login or profile menu in the top bar of the web page."

**Comment by emanueldima** [comment]
solved in v2.0.0-beta2
