### ISSUE TITLE
UI available via git repo

### ISSUE THREAD

**Issue by dblommesteijn** [EUDAT-B2SHARE/b2share#779]
I've create two new repositories for UI & B2share 2.0 development: [ui-frontend](https://github.com/EUDAT-B2SHARE/ui-frontend), [ui-server](https://github.com/EUDAT-B2SHARE/ui-server). Both are available in the EUDAT-B2SHARE organisation.

**Comment by emanueldima** [comment]
ui-frontend is not the official UI of the b2share2 and ui-server has been replaced with functionality inside b2share. Closing this one.
