### ISSUE TITLE
implement records schema handling

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#780]
As discussed with Emanuel.

The schemas used in Invenio are jsonschemas, which are quite flexible. See http://spacetelescope.github.io/understanding-json-schema/index.html

Any very custom validation could be handled by hard coded validators corresponding to custom string field formats (see http://spacetelescope.github.io/understanding-json-schema/reference/string.html#format).

Jsonschemas are used in 2 places:
- in the record validation.
- in the elasticsearch mapping generation. This is needed so that elasticsearch knows the type of each field.

**Record jsonschema generation**
As we want multiple schemas per record we will have to generate the whole record schemas dynamically. It can be done easily by using an "array" type for the "metadata" field. We would then specify the different types of sub-schemas as items type (see http://spacetelescope.github.io/understanding-json-schema/reference/array.html#items). For these sub-schemas we can just use references.

**Jsonschema refrences**
Python has a great library for validating jsonschemas: https://pypi.python.org/pypi/jsonschema
It is the one currently used by Invenio.
One of the good things with this library is that it is possible to implement how we want the jsonschema references to be resolved (https://python-jsonschema.readthedocs.org/en/latest/references/).

We can just store the schemas in the database and give a resolver to which will search for the schemas in the database. Or we could just use the api endpoints as id. It would also work great.

**Elasticsearch mapping**
There is a project for generating elasticsearch mappings from jsonschemas. It will be shortly moved to the Inveniosoftware organization. In the mean time it can be found here: https://github.com/nharraud/jsonschema-to-elasticmapping
This library does not depend on Invenio. It will be shortly used by Invenio-search (https://github.com/inveniosoftware/invenio-search) to generate elasticsearch mappings.

An api endpoint can be added to invenio-search in order to update elasticsearch mapping when a new schema is created.

**Comment by emanueldima** [comment]
It's now implemented (beta1)
