### ISSUE TITLE
B2Access / googleauth

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#786]
Hi,

We tested B2Access with the google authentication, and noticed one thing which might be problematic. When you log in with B2access google auth, your nickname is going to be set to your email-address. So if you write some reviews etc. the mail-address will be visible on the web-page, which probably is not good, as it could be harvested by the spam-bots.

**Comment by llehtine** [comment]
And the same issue could be true with normal deposits also, as you always get the e-mail address visible even if you are not logged in on the "Uploaded by" and "Contact email"-fields.

**Comment by emanueldima** [comment]
@llehtine Lassi, you have direct access to the test server and can debug it. If I'm not mistaken, we can change the user info that the b2access returns, see the `account_info` function in the `invenio/modules/oauthclient/contrib/unity.py` module, lines 86-87.

**Comment by llehtine** [comment]
I've changed it on test-server now to get the value from cn-variable, so you would get your full name as a nickname. Should I change it also on git? I guess this is more of a general question, that do we want to show up email-addresses on web-page, where they could possibly be harvested

**Comment by cjhak** [comment]
In the case where users have registred manually in B2SHARE (like all current users), do we have any other choice than to show e-mails e.g. in the field "Uploaded by"?

**Comment by llehtine** [comment]
Only option would be the nickname, but as it is the login-name but for users created manually it could be not-so-informative. Also when taking it from the cn-field @ unity login, there could be duplicates (same name for two different persons). For contact email you can anyway define anything you want for the deposits. I'm just worried about that if people use their google account to authenticate, and then comment on something they might not want their e-mail address to be visible in site and they don't have any way to prevent that.

**Comment by cjhak** [comment]
Closing, as it seems sufficiently fixed for 1.6.x. We should still bear the issue in mind for B2SHARE 2.0 though, depending on how log on and user management will work in the future.
