### ISSUE TITLE
Re-direct B2SHARE users registered in B2SHARE to register in B2ACCESS upon login.

### ISSUE THREAD

**Issue by cjhak** [EUDAT-B2SHARE/b2share#796]
The possibility to log in directly to B2SHARE without using B2ACCESS should be removed. Existing registred users who try to login that way need to be re-directed to B2ACCESS to register anew and also informed that they should contact us (post to help-desk?) if they have material uploaded with their old accounts so the user accounts can be merged.

**Comment by nharraud** [comment]
I don't think they need to inform us if they have material uploaded with their old account. The "migration" would be like that:
1/ user logs in with his old account. => the user sees a page which asks him to log in with B2Access
2/ the user logs into B2Access => we replace the old authentication with the new one for this user, keeping the same account.

What we need to know is if some users created both an account with B2Access and the old B2Share account system. Those accounts need to be merged.

I would simplify the message as "Please contact us if you don't seem to have access to all your records or for any other problem". If we start talking about multiple accounts people might get lost as they don't know how B2Share and B2Access work.

**Comment by cjhak** [comment]
@nharraud I agree completely with your suggested solution.

**Comment by nharraud** [comment]
I implemented something a little less agressive by letting users access their account with username and password even if they have connected a B2Access account. At each login the user is informed that the username/password mechanism will be disabled soon. A link is provided to connect the account to B2Access when it is not already done.
