### ISSUE TITLE
User guide: a record owner can NOT edit own records if the records are open access

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#813]
There was couple of helpdesk-tickets complaining that the owner of record can't edit the records they have uploaded. It seems that currently it's not possible to edit records with open access even by the owner (admin is allowed to edit records, though)

**Comment by llehtine** [comment]
https://github.com/EUDAT-B2SHARE/b2share/pull/814

**Comment by emanueldima** [comment]
But this is by design. If a record is public it has a PID and it should not be modified, except to fix typos. That's why only the community administrators can edit it. The owner can edit the record only if the record is private.

**Comment by llehtine** [comment]
Ok, then it's a feature :) I update the helpdesk-ticket.

**Comment by llehtine** [comment]
Comment from the user:


On Fr, 2015-12-11 at 11:48 +0100, Lassi Lehtinen via RT wrote:
> Update from the development team; it's not a bug, it's a feature.
Could you mention that more prominently on the upload page ?
I went through b2share-guide and could not find this.

> Open access deposits which have PID should not be editable aftwards.
Makes sense, but maybe we are not the only ones not getting it right
the first time. So a feature request would be to have a button
for a deposit that says "Create PID and make Deposit persistent and
unmutable".

**Comment by emanueldima** [comment]
in 2.0.1 the metadata can be edited while the data cannot.
