### ISSUE TITLE
Help balloons flickering when hovering with mouse over textboxes

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#818]
Help balloons are flickering when hovering with mouse over textboxes. Happening atleast with firefox in Linux.

**Comment by emanueldima** [comment]
On which page?

**Comment by llehtine** [comment]
On the deposit-page, when you are filling metadata for the new item

**Comment by emanueldima** [comment]
Only happens in Firefox. Chrome and Safari work fine.

**Comment by emanueldima** [comment]
won't fix in v1, N/A in v2
