### ISSUE TITLE
v2: Request data access page

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#853]
see spec: https://github.com/EUDAT-B2SHARE/b2share/wiki/Spec

**Comment by nharraud** [comment]
Zenodo will soon contribute back their own access request module [zenodo/zenodo-accessrequests](https://github.com/zenodo/zenodo-accessrequests).

It looks like there isn't much to do to make it usable for B2Share:
- Add a REST API
- factorize a few lines of code to enable our own PIDs and permissions.

This module generates private links giving access to the data during a fixed period of time. It would work better than simple notification emails for use cases where
- the amount of data is huge.
- the scientist discarded the data and the only copy is on B2Share. It would require the researcher to download the data from B2Share just to send it back to the requesting person.

**Comment by emanueldima** [comment]
we have basic UI and server support for this issue (similar to what we have in v1: https://github.com/EUDAT-B2SHARE/b2share/pull/1094) but using the zenodo access module would be better.
