### ISSUE TITLE
New documentation structure

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#860]
In a meeting with the documentation team we decided that:

1. The FAQ page will be removed and its content will be present at the beginning of the User guide

2. The User Guide and What is B2SHARE will be linked to eudat.eu/userdoc

3. The Terms of Service and REST API will be the only remaining doc pages hosted on the B2SHARE site.

**Comment by SarahBA** [comment]
closed by https://github.com/EUDAT-B2SHARE/b2share/pull/859
