### ISSUE TITLE
Login button placements

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#861]
Position of username and password form:
 - the position of username and password form to sign in should be in center

And also, after the user is signed successfully, the system is still showing up username and password form

https://helpdesk.eudat.eu/Ticket/Display.html?id=10530

**Comment by llehtine** [comment]
Also, the signup-button should be available on every-page:
https://helpdesk.eudat.eu/Ticket/Display.html?id=10529

**Comment by emanueldima** [comment]
see also #770

**Comment by llehtine** [comment]
For the first issues (https://helpdesk.eudat.eu/Ticket/Display.html?id=10530), the b2s-accounts.css was missing from the correct path. Copied it manually, so it should look ok now.

**Comment by emanueldima** [comment]
solved in v2.0.0-beta2
