### ISSUE TITLE
Drop-down feature for user-guide

### ISSUE THREAD

**Issue by llehtine** [EUDAT-B2SHARE/b2share#862]
From the user ticket: "Currently there are too much information in the user guides. It
would be better if user guides provide indexing or drop-down
feature. The complete information will be shown after the user
clicked the title of the information."

https://helpdesk.eudat.eu/Ticket/Display.html?id=10533

**Comment by hevp** [comment]
This has been resolved in the conversion to the [EUDAT website](https://eudat.eu/services/userdoc/b2share-usage). All pages provide a table of contents enabling quick navigation to the reader.
