### ISSUE TITLE
An edit record operation should have an 'Edit Message' metadata field.

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#873]
The 'Edit Message' field should be optional and should be used by the user editing a record to specify the extent and reason for the edit operation.

**Comment by thijscobben** [comment]
Note that this can also be done via B2NOTE. Or the comments/description field of a record.
Also note that this only makes sense if some kind of journal is displayed on the record page and/or the JSON API. Not making the field obligatory does not seem to add a lot of value.
