### ISSUE TITLE
v2: Internal data structures

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#914]
What are the data we must store in the database? What is the format of the data?
1. Communities: 
   - we have: id, created, updated, json_schema, name, description and logo
   - we need community specific options: 
     - community scientific domain specification?
     - allow comments/reviews/annotations for the records of the community
2. Records:
   - we have: id, ...
   - we need: 
     - statistics (number of views per record), 
     - comments and ratings
     - an audit log
3. Files:
   - we have: ?
   - we need: 
     - statistics (number of views/downloads)
     - an audit log

**Comment by emanueldima** [comment]
Questions about comments and ratings, from @nharraud :

2.1/ Who can comment, review, rate and/or annotate records (what roles: admin, community manager, creator, simple users, other roles)?
2.2/ any curator role?
2.3/ When can they be created (what record status: draft, published, rejected)? Are the reviews used by community managers to tell the creator how he should improve the record before it is published?
2.4/ What is their visibility?
2.5/ Does the visibility change when the record change its status?
2.6/ Can they be edited later? If yes, do we keep the whole history for them too? Can they be deleted?
2.7/ How would they be queried? Does one need to specify the record ID and version to get its comments, reviews and annotations? Or should it be possible to list them just with a record ID without specifying the version?
2.8/ Does the rating remain the same from one record version to another? It would seem the best solution.
2.9/ Is it possible to change the rate you gave to a record?

**Comment by nharraud** [comment]
@emanueldima Won't we need at least a mechanism which would enable community managers to explain why they refused a record, or what needs to be modified before the record is accepted?

**Comment by emanueldima** [comment]
@nharraud Yes, indeed we need that, and indeed this comment/review system is the best fit for this task. But this also implies having a basic access control, because the owner of a records would not like this review to be publicised, and that makes this system more complicated to implement. Unless Invenio already provides a solution.

**Comment by nharraud** [comment]
@emanueldima  The [inveniosoftware/invenio-deposit](https://github.com/inveniosoftware/invenio-deposit) module is the one enabling the submission of record with draft/published status but it does not have review/comment mechanism. It would have to be added on top of it.

**Comment by emanueldima** [comment]
N/A any more
