### ISSUE TITLE
v2: rpm package in Dockerfile

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#917]
**Problem:**
The RPM package `http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm` does not seem to exist. I get 404 error. As it is used by `dockerize/Dockerfile`, the docker build fails.

**Comment by emanueldima** [comment]
@nharraud Please test https://github.com/EUDAT-B2SHARE/b2share/pull/919

**Comment by emanueldima** [comment]
Seems to be solved for now, but it can happen again in the future. The version of epel was bumped without keeping the old one available.
