### ISSUE TITLE
demo: use lowest versions of dependency packages

### ISSUE THREAD

**Issue by nharraud** [EUDAT-B2SHARE/b2share#918]
**Problem:**

Invenio is still in alpha version and refactoring are done from time to time with no backward compatibility. B2Share's setup.py does not fix the dependency versions so that it can always use the last released ones, thus it will break at each refactoring.
We should at least make sure that the demo is never broken.

**Solution:**

Use the lowest versions of dependency packages, the same way as travis does for the *lowest* variant.

**Comment by emanueldima** [comment]
Fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/920
