### ISSUE TITLE
v2: many 404 errors on fresh docker-compose deployment

### ISSUE THREAD

**Issue by BeneDicere** [EUDAT-B2SHARE/b2share#921]
Hi,
when following the INSTALL document on a remote machine (physical, docker-compose up) we get many 404 errors and there are missing items in the UI. Is this expected behaviour or is there something missing in the repo?
best
![404](https://cloud.githubusercontent.com/assets/5327850/14635078/276c7214-0625-11e6-9281-9d6dd99c0e62.png)

**Comment by emanueldima** [comment]
Should be solved by https://github.com/EUDAT-B2SHARE/b2share/pull/920 and  https://github.com/EUDAT-B2SHARE/b2share/pull/924

**Comment by BeneDicere** [comment]
can confirm this
