### ISSUE TITLE
v2: make b2access oauth URL configurable

### ISSUE THREAD

**Issue by BeneDicere** [EUDAT-B2SHARE/b2share#925]
Hi,
at least for testing purposes it could be required that we can not use the main b2access endpoint but the b2access testing servers. For this, one has to change the b2access oauth URL statically configured in 'b2share/oauth/b2access.py'. Is it possible to implement it in a way that we can configure it using the container environment? Otherwise we would have to fork the project.
best

**Comment by emanueldima** [comment]
Yes, we intend to do that, but probably we'll only reach this phase in RC-1. The current oauth configuration is not yet functional.

**Comment by emanueldima** [comment]
We now have a configuration file that can be edited, and this file contains the details for b2access connections. See https://github.com/EUDAT-B2SHARE/b2share/blob/evolution/INSTALL.rst#121-b2access-configuration for details.
