### ISSUE TITLE
Home page not adapted to login status

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#972]
![screenshot 2016-06-21 11 25 02](https://cloud.githubusercontent.com/assets/7724267/16224632/2c6f874c-37a3-11e6-8f47-2dc0d0e2749b.png)
Even if authenticated I am prompted to login.

**Comment by emanueldima** [comment]
fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/1215
