### ISSUE TITLE
schemas: Validate community schemas and block schemas before accepting them

### ISSUE THREAD

**Issue by emanueldima** [EUDAT-B2SHARE/b2share#987]
We already have a metaschema for validating the block schemas: 
https://github.com/EUDAT-B2SHARE/b2share/blob/evolution/b2share/modules/schemas/validate.py#L31

At the API level, in BlockSchema, we should have a validation step.

**Comment by thijscobben** [comment]
Hi,

Just a quick notification: Please note I am also working with that file for
validation of block_schema part of schema addition via CLI .

T.

2016-07-06 11:54 GMT+02:00 Emanuel Dima <notifications@github.com>:

**Comment by thijscobben** [comment]
almost done

**Comment by nharraud** [comment]
inveniosoftware/doschema

**Comment by nharraud** [comment]
Next steps (after the structural validation implemented by @emanueldima and @thijscobben) of the validation will be handled in issue #1076.

**Comment by emanueldima** [comment]
superceded by https://github.com/EUDAT-B2SHARE/b2share/issues/1392
