### ISSUE TITLE
Remove dropdown for publication state

### ISSUE THREAD

**Issue by thijscobben** [EUDAT-B2SHARE/b2share#989]
See screenshot this is now obsolete or at least the 'submitted' state is obsolete?
I think now we use the "Submit for publication" checkbox underneath the form?
<img width="1082" alt="screen shot 2016-07-06 at 15 00 17" src="https://cloud.githubusercontent.com/assets/7724267/16618802/899e4054-438b-11e6-9483-5ff57c74b347.png">

**Comment by emanueldima** [comment]
fixed by https://github.com/EUDAT-B2SHARE/b2share/pull/993
